package it.f0x.catalog

import android.app.Activity
import android.content.Intent
import android.os.Bundle
import dev.forgekit.ForgeKitSurfaceView

/**
 * Generated by `forgekit create` (spec Phase 2 §10.1). Hosts the ForgeKit
 * render surface as the activity's entire content view and forwards the
 * lifecycle callbacks the Choreographer render loop needs.
 *
 * Deep links (task 07): cold-start delivery forwards `intent?.data` from
 * [onCreate]; a running instance receives a link via [onNewIntent] instead
 * (this activity's manifest entry declares `android:launchMode="singleTop"`
 * precisely so a warm relaunch reuses this instance rather than creating a
 * new one). Both funnel into [ForgeKitSurfaceView.onDeepLink], which queues
 * the link until the native handle exists if it arrives first (cold-start
 * routinely races ahead of `nativeInit`, since that only runs once the
 * `SurfaceHolder` callback fires).
 */
class MainActivity : Activity() {
    private lateinit var surfaceView: ForgeKitSurfaceView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        surfaceView = ForgeKitSurfaceView(this)
        setContentView(surfaceView)
        surfaceView.onDeepLink(intent?.data?.toString())
    }

    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        setIntent(intent)
        surfaceView.onDeepLink(intent.data?.toString())
    }

    override fun onResume() {
        super.onResume()
        surfaceView.onResume()
    }

    override fun onPause() {
        surfaceView.onPause()
        super.onPause()
    }

    override fun onDestroy() {
        surfaceView.onDestroy()
        super.onDestroy()
    }
}