// Generated by `frust create`. AGP 9's built-in Kotlin support means no
// separate `org.jetbrains.kotlin.android` plugin is applied —
// `com.android.application` alone is enough.
//
// This is the full Frust build-mode matrix: debug,
// profile, and release build types, key.properties release signing, optional
// per-ABI splits, version plumbing via local.properties, and a
// `-P`-parameterized cargo-ndk step. Every input the Frust CLI passes is a
// Gradle `-P` project property or a `local.properties`/`key.properties` entry
// — there are no additional scaffold placeholders here, only build-time
// values with Kotlin-side defaults, so an Android-Studio-driven build (no CLI)
// still works with sensible defaults.
import java.util.Properties
import java.io.FileInputStream
import java.util.Base64
import com.android.build.api.variant.FilterConfiguration.FilterType.ABI

plugins {
    id("com.android.application")
}

// `local.properties` carries CLI-written version plumbing (never committed);
// `key.properties` carries release-signing material (never committed — see
// frust.toml's [signing] section and the app's .gitignore). Both are
// optional: absent files yield empty `Properties` and the defaults below apply.
val localProperties = Properties().apply {
    val f = rootProject.file("local.properties")
    if (f.exists()) FileInputStream(f).use { load(it) }
}
val keystoreProperties = Properties().apply {
    val f = rootProject.file("key.properties")
    if (f.exists()) FileInputStream(f).use { load(it) }
}

// Reads a Gradle `-P` project property with a Kotlin-side default, so every
// CLI-driven knob has a working default for Android-Studio-driven builds.
fun prop(name: String, default: String): String =
    (project.findProperty(name) as String?) ?: default

// Version plumbing (Flutter-canonical mechanism, Frust keys). The CLI
// writes `frust.versionName`/`frust.versionCode` into local.properties;
// defaults keep a hand-run Gradle build working.
val versionNameValue = localProperties.getProperty("frust.versionName", "1.0")
val versionCodeValue = localProperties.getProperty("frust.versionCode", "1").toInt()

// ABI selection + split toggle. `frust.targetPlatforms` is a CSV of Android
// ABIs (default single-ABI arm64-v8a, matching `frust run`'s per-device
// build); `frust.splitPerAbi` gates per-ABI APK splits (off by default — a
// universal APK/AAB is produced instead).
val abis = prop("frust.targetPlatforms", "arm64-v8a")
    .split(",").map { it.trim() }.filter { it.isNotEmpty() }
val splitPerAbi = prop("frust.splitPerAbi", "false").toBoolean()

// `--define K=V` values, base64(`K=V;K=V`) so an arbitrary value survives the
// shell/`-P` boundary. Decoded and set as env vars on the cargo-ndk exec below
// so the Rust side's `option_env!("K")` can read them at compile time.
val definesB64 = prop("frust.defines", "")

// Cargo `--features` selected by the CLI per build mode (release-lean plan):
// base64(`feat,feat`), decoded and appended to the cargo-ndk build below as
// `--features <csv>`. The CLI passes `frust/perf-trace` for debug/profile
// (instrumentation compiled IN) and `lean` for release (the log ceiling);
// empty default so an Android-Studio-driven build (no CLI) adds no features.
// Rides a `-P` property — NOT an env var — so a feature flag can never fall
// foul of the release env-drop Known Issue by construction.
val cargoFeaturesB64 = prop("frust.cargoFeatures", "")

android {
    namespace = "it.f0x.huddle"
    compileSdk = 36

    defaultConfig {
        applicationId = "it.f0x.huddle"
        minSdk = 26
        targetSdk = 36
        versionCode = versionCodeValue
        versionName = versionNameValue
    }

    signingConfigs {
        // Only wire a release signing config when key.properties is present;
        // otherwise release falls back to debug signing (with a warning) so an
        // unsigned local build still succeeds. `frust build` (CLI) makes a
        // missing keystore a hard error — this fallback is the escape hatch for
        // Android-Studio-driven builds.
        if (keystoreProperties.isNotEmpty()) {
            create("release") {
                keyAlias = keystoreProperties["keyAlias"] as String
                keyPassword = keystoreProperties["keyPassword"] as String
                storeFile = (keystoreProperties["storeFile"] as String?)?.let { rootProject.file(it) }
                storePassword = keystoreProperties["storePassword"] as String
            }
        }
    }

    buildTypes {
        getByName("release") {
            val releaseSigning = signingConfigs.findByName("release")
            if (releaseSigning != null) {
                signingConfig = releaseSigning
            } else {
                signingConfig = signingConfigs.getByName("debug")
                logger.warn(
                    "Frust: release build is debug-signed; create " +
                        "android/key.properties — see frust.toml [signing]",
                )
            }
            // R8 + resource shrink: the Kotlin/Java side is
            // small (this app's `MainActivity` plus the `:frust-embedding`
            // module) so the dex win is modest, but shipping unminified
            // release code is not the
            // Frust default. `proguard-rules.pro` carries the two keep
            // rules R8 needs beyond AGP's own default rule set (JNI-bound
            // classes it can't otherwise prove are live) — see that file's
            // comments.
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
        // Profile: release codegen with a debug-signed, non-debuggable package
        // for on-device performance measurement. Its cargo profile
        // (`--profile profile`) keeps symbols/tracing on — see cargoNdkBuild.
        // `initWith(release)` copies every build-type property, including
        // `isMinifyEnabled`/`isShrinkResources`/`proguardFiles` above, so
        // profile stays representative of release's minified/shrunk shape —
        // no separate opt-in needed here.
        create("profile") {
            initWith(getByName("release"))
            signingConfig = signingConfigs.getByName("debug")
            matchingFallbacks += listOf("release", "debug")
            isDebuggable = false
        }
        // `debug` is implicit (AGP-provided) and unchanged: no minification,
        // so no keep-rule risk while iterating.
    }

    // Per-ABI APK splits, off by default. When enabled, one APK per ABI is
    // produced instead of a universal APK.
    splits {
        abi {
            isEnable = splitPerAbi
            reset()
            include(*abis.toTypedArray())
            isUniversalApk = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    // Native libraries are packaged from this app's `build/android/jniLibs`,
    // where `cargoNdkBuild` below stages them (`-o`) — nothing is written
    // under `src/main/jniLibs` any more, so the source tree stays free of
    // build output and `frust clean` can remove the `.so`s with everything
    // else. Paths in this file resolve against the module directory
    // (`android/app/`), so `../../` is the app root.
    //
    // `setSrcDirs` REPLACES AGP's default `src/main/jniLibs` with our build
    // directory exclusively — the source tree is never a packaging input. A
    // project migrated from the old layout may have stale `.so`s in
    // `src/main/jniLibs` left over; those are not packaged (only our build
    // directory is), but they linger until `frust clean` removes them. The ABI
    // split/versionCode block below is unaffected — it reads the variant's ABI
    // filters and the staged `.so` files, not the source set.
    sourceSets.getByName("main").jniLibs.setSrcDirs(listOf("../../build/android/jniLibs"))

    // Example flavor scaffold — uncomment and mirror frust.toml's [flavors].
    // flavorDimensions += "env"
    // productFlavors {
    //     create("dev")  { dimension = "env"; applicationIdSuffix = ".dev" }
    //     create("prod") { dimension = "env" }
    // }
}

// Frust's Android embedding: the Kotlin host (`FrustActivity`,
// `FrustSurfaceView`, `FrustViewHost`, the vendored accesskit delegate) this
// app's `MainActivity` extends, plus the JNI declarations the Rust side
// exports against. Included by path — see `settings.gradle.kts` and
// `gradle.properties`' `frust.embedding.dir`.
//
// `androidx.core` (edge-to-edge, inset merging, bar-icon contrast) and
// `androidx.activity` (`ComponentActivity`, `onBackPressedDispatcher`) are
// re-exported transitively by the module's `api` declarations, so this app
// declares neither directly.
dependencies {
    implementation(project(":frust-embedding"))
    // frust:plugin-dependencies — plugin-contributed dependencies go below.
}

// Per-ABI versionCode offsets, applied only when splits are enabled so each
// split APK gets a distinct, monotonic versionCode. Mapping and formula are the
// official Android docs' "Configure multiple APKs" example
// (developer.android.com/build/configure-apk-splits#configure-APK-versions):
// armeabi-v7a→1, arm64-v8a→2, x86→3, x86_64→4, code = abiCode * 1000 + base.
// (The Flutter-lore mapping is a different set — this is the documented one.)
androidComponents {
    onVariants { variant ->
        if (splitPerAbi) {
            val abiCodes = mapOf(
                "armeabi-v7a" to 1,
                "arm64-v8a" to 2,
                "x86" to 3,
                "x86_64" to 4,
            )
            variant.outputs.forEach { output ->
                val abiName = output.filters.find { it.filterType == ABI }?.identifier
                if (abiName != null) {
                    val abiCode = abiCodes[abiName] ?: 0
                    output.versionCode.set(abiCode * 1000 + versionCodeValue)
                }
            }
        }
    }
}

// Builds the Rust `.so`(s) via `cargo ndk` before every Gradle build.
// `workingDir` is the Rust app root (two levels up from `android/app/`); `-o`
// points at that same app root's `build/android/jniLibs`, the app-owned build
// directory registered as a `jniLibs` source directory in the `android` block
// above — so the resulting `<abi>/libhuddle.so` is packaged by
// Gradle without any of it landing in `src/main/`. Keep the two paths in step:
// staging somewhere Gradle does not read produces an APK that installs and
// then crashes on `System.loadLibrary`, not a build failure.
//
// The cargo profile is chosen from the invoked task names (debug → `build`,
// profile → `build --profile profile`, release → `build --release`) so the
// single `cargoNdkBuild` task hooked into `preBuild` produces the right
// artifact for whichever variant is being assembled. Targets come from
// `frust.targetPlatforms` (repeated `-t <abi>`), defaulting to arm64-v8a —
// the same single-ABI debug build `frust run` has always produced.
//
// `frust run`/`frust build` run their own preflight (Rust target,
// cargo-ndk, JDK, adb); this task assumes the toolchain is on `PATH` and fails
// loudly (inherited from the shell) if it isn't.
val cargoProfileArgs: List<String> = run {
    val requested = gradle.startParameter.taskNames.joinToString(" ").lowercase()
    when {
        requested.contains("release") -> listOf("build", "--release")
        requested.contains("profile") -> listOf("build", "--profile", "profile")
        else -> listOf("build")
    }
}
val cargoTargetArgs: List<String> = abis.flatMap { listOf("-t", it) }

// Decode the base64 `--features` CSV (empty → no extra features).
val cargoFeatureArgs: List<String> =
    if (cargoFeaturesB64.isEmpty()) {
        emptyList()
    } else {
        listOf("--features", String(Base64.getDecoder().decode(cargoFeaturesB64)))
    }

val cargoNdkBuild = tasks.register<Exec>("cargoNdkBuild") {
    workingDir = file("../..")
    commandLine(
        buildList {
            add("cargo")
            add("ndk")
            addAll(cargoTargetArgs)
            add("-o")
            add(file("../../build/android/jniLibs").absolutePath)
            addAll(cargoProfileArgs)
            addAll(cargoFeatureArgs)
        },
    )
    // Thread `--define`s through as env vars so `option_env!("K")` sees them.
    if (definesB64.isNotEmpty()) {
        String(Base64.getDecoder().decode(definesB64))
            .split(";")
            .filter { it.isNotEmpty() }
            .forEach { kv ->
                val idx = kv.indexOf('=')
                if (idx > 0) environment(kv.substring(0, idx), kv.substring(idx + 1))
            }
    }
}

tasks.named("preBuild") {
    dependsOn(cargoNdkBuild)
}