//! Points a generated project's Android and iOS host projects at the native
//! modules shipped inside the crates cargo resolves for it: the embeddings in
//! the shell crates, and the Gradle modules and Swift packages of every
//! plugin the project depends on.
//!
//! The Android embedding is a Gradle library module in
//! `frust-shell-android/platform/android/frust-embedding`, the iOS one a Swift
//! package in `frust-shell-ios/platform/ios/FrustEmbedding`; a plugin's live
//! under its own package (`frust-iap/platform/android`,
//! `frust-iap/platform/ios/FrustIap`). Where those crates live depends on how
//! the project depends on the framework — a checkout's crate directory under
//! `--frust-path`, the unpacked release under cargo's registry cache
//! otherwise — and moves whenever the resolved version does (`cargo update`)
//! or the project moves to another machine. So no location is ever written
//! into a tracked file: [`sync`] asks [`crate::packages`] (one `cargo
//! metadata` run) and writes the answers into the two machine-local places
//! the host build tools read them from:
//!
//! - `android/local.properties` (gitignored): [`EMBEDDING_DIR_KEY`] and one
//!   [`plugin_module_key`] per plugin Gradle module, each an absolute module
//!   directory. The generated `settings.gradle.kts` resolves every
//!   `projectDir` through its `frustLocalDir(key)` helper, which fails naming
//!   `frust run`/`frust build` when the file or key is missing.
//! - one symlink per local Swift package next to `Runner.xcodeproj`
//!   (`ios/FrustEmbedding`, `ios/FrustIap`, …, all gitignored), which the
//!   project's package references name by the relative path
//!   `FrustEmbedding`, `FrustIap`, ….
//!
//! Idempotent: an up-to-date project is left byte-identical, and the returned
//! [`Report`] says per module what (if anything) changed. A project without
//! an `android/` or `ios/` directory is skipped for that platform, and cargo is
//! not asked about a package only a skipped platform needs.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use toml_edit::DocumentMut;

use crate::android_build::local_properties::{self, Change, Missing};
use crate::host_path;
use crate::packages::{CargoLocator, PackageLocator, PackagesError};
use crate::plugin::{NativeKind, NativeModule, apply::plugin_is_installed, known_plugins};
use crate::process::RealProcessRunner;

/// The package shipping the Android embedding module.
pub const ANDROID_SHELL_PACKAGE: &str = "frust-shell-android";
/// The package shipping the iOS embedding Swift package.
pub const IOS_SHELL_PACKAGE: &str = "frust-shell-ios";
/// The Android embedding module's directory inside [`ANDROID_SHELL_PACKAGE`].
pub const ANDROID_EMBEDDING_REL: &str = "platform/android/frust-embedding";
/// The iOS embedding package's directory inside [`IOS_SHELL_PACKAGE`].
pub const IOS_EMBEDDING_REL: &str = "platform/ios/FrustEmbedding";
/// The `android/local.properties` key `settings.gradle.kts` resolves the
/// `:frust-embedding` module directory from.
pub const EMBEDDING_DIR_KEY: &str = "frust.embedding.dir";
/// The project-relative path of the machine-local properties file [`sync`]
/// keeps every Android module directory in.
pub const LOCAL_PROPERTIES: &str = "android/local.properties";
/// The project-relative path of the tracked Gradle properties file. It
/// carries no machine path in a project generated today; one generated by an
/// earlier template may still hold [`EMBEDDING_DIR_KEY`] there for its
/// `settings.gradle.kts` to read, and [`sync`] keeps that existing value
/// current rather than strand the project (it never adds the key).
pub const GRADLE_PROPERTIES: &str = "android/gradle.properties";
/// The project-relative path of the symlink the iOS project's embedding
/// package reference (`relativePath = "FrustEmbedding"`) resolves through.
pub const IOS_EMBEDDING_LINK: &str = "ios/FrustEmbedding";

/// The `android/local.properties` key holding plugin Gradle module
/// `gradle_name`'s directory: `frust.plugin.frust-iap.dir` for `:frust-iap`.
pub fn plugin_module_key(gradle_name: &str) -> String {
    format!("frust.plugin.{}.dir", gradle_name.trim_start_matches(':'))
}

/// The project-relative path of the symlink a local Swift package's
/// reference (`relativePath = "<package_name>"`) resolves through:
/// `ios/FrustIap` for `FrustIap`.
pub fn swift_package_link(package_name: &str) -> String {
    format!("ios/{package_name}")
}

/// Why the wiring could not be brought up to date.
#[derive(Debug, thiserror::Error)]
pub enum SyncError {
    /// cargo could not say where a shell or plugin crate lives.
    #[error("could not locate the frust shell and plugin crates: {0}")]
    Locate(#[from] PackagesError),
    /// The located crate does not carry the native directory it should — an
    /// incomplete package, which Gradle or Xcode would otherwise report far
    /// less clearly.
    #[error(
        "`{package}` resolved to '{}', which has no native module at '{}'",
        package_dir.display(),
        embedding_dir.display()
    )]
    EmbeddingMissing {
        package: &'static str,
        package_dir: PathBuf,
        embedding_dir: PathBuf,
    },
    /// Reading or writing a project file failed.
    #[error("{action} '{}': {source}", path.display())]
    Io {
        action: &'static str,
        path: PathBuf,
        source: io::Error,
    },
}

/// What [`sync`] did for one location.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Wiring {
    /// The project has no directory for this platform (or, for
    /// [`Report::legacy_gradle_property`], no such key to refresh).
    Skipped,
    /// Already pointed at `target`; nothing was written.
    Unchanged { target: PathBuf },
    /// Now points at `target`. `previous` is the value or link target it
    /// replaced, `None` when the key or link did not exist yet.
    Updated {
        target: PathBuf,
        previous: Option<String>,
    },
    /// `path` exists but is not a symlink (a vendored copy, say) — user
    /// content, so it is left alone.
    Occupied { path: PathBuf, target: PathBuf },
    /// This host could not create the symlink (no symlink support, or a
    /// Windows account without the privilege). The rest of the sync stands.
    Unsupported { target: PathBuf, reason: String },
}

impl Wiring {
    /// Whether this location was written.
    pub fn changed(&self) -> bool {
        matches!(self, Self::Updated { .. })
    }
}

/// One plugin native module's wiring in a [`Report`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ModuleWiring {
    /// The plugin's registry id (`"iap"`).
    pub plugin_id: &'static str,
    /// The module wired.
    pub module: NativeModule,
    /// What happened to its key or link.
    pub wiring: Wiring,
}

/// The outcome of one [`sync`]: the two embeddings, every plugin module, and
/// the legacy `gradle.properties` key.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Report {
    /// The Android embedding's [`EMBEDDING_DIR_KEY`] in [`LOCAL_PROPERTIES`].
    pub android: Wiring,
    /// The iOS embedding's [`IOS_EMBEDDING_LINK`].
    pub ios: Wiring,
    /// One entry per plugin Gradle module / Swift package wired, in registry
    /// order.
    pub plugins: Vec<ModuleWiring>,
    /// [`EMBEDDING_DIR_KEY`] in [`GRADLE_PROPERTIES`], refreshed only where an
    /// earlier template put it; [`Wiring::Skipped`] when absent.
    pub legacy_gradle_property: Wiring,
}

impl Report {
    fn skipped() -> Self {
        Self {
            android: Wiring::Skipped,
            ios: Wiring::Skipped,
            plugins: Vec::new(),
            legacy_gradle_property: Wiring::Skipped,
        }
    }

    /// Whether anything was written.
    pub fn changed(&self) -> bool {
        self.android.changed()
            || self.ios.changed()
            || self.legacy_gradle_property.changed()
            || self.plugins.iter().any(|m| m.wiring.changed())
    }

    /// One human-readable line per location that was written or needs
    /// attention; empty when nothing changed and nothing is wrong. Skipped
    /// and unchanged locations say nothing.
    pub fn lines(&self) -> Vec<String> {
        let mut lines = Vec::new();
        let android = match (&self.legacy_gradle_property, &self.android) {
            (Wiring::Updated { target, .. }, _) => Some(format!(
                "Android embedding: {GRADLE_PROPERTIES} -> {} (kept for this project's older \
                 settings.gradle.kts; {LOCAL_PROPERTIES} carries it too)",
                target.display()
            )),
            (_, wiring) => describe("Android embedding", LOCAL_PROPERTIES, wiring),
        };
        lines.extend(android);
        lines.extend(describe("iOS embedding", IOS_EMBEDDING_LINK, &self.ios));
        for module in &self.plugins {
            let (label, location) = match module.module.kind {
                NativeKind::GradleModule { gradle_name } => (
                    format!("Android module `{gradle_name}`"),
                    LOCAL_PROPERTIES.to_string(),
                ),
                NativeKind::SwiftPackage { package_name } => (
                    format!("iOS package `{package_name}`"),
                    swift_package_link(package_name),
                ),
            };
            lines.extend(describe(&label, &location, &module.wiring));
        }
        lines
    }
}

fn describe(label: &str, location: &str, wiring: &Wiring) -> Option<String> {
    match wiring {
        Wiring::Skipped | Wiring::Unchanged { .. } => None,
        Wiring::Updated { target, .. } => {
            Some(format!("{label}: {location} -> {}", target.display()))
        }
        Wiring::Occupied { path, target } => Some(format!(
            "{label}: '{}' is not a symlink, left as is (expected a link to '{}')",
            path.display(),
            target.display()
        )),
        Wiring::Unsupported { target, reason } => Some(format!(
            "{label}: could not link {location} -> '{}': {reason}",
            target.display()
        )),
    }
}

/// Where `project_dir`'s Android and iOS embeddings resolve, without writing
/// anything — what [`sync`] would point the project at. Both are located
/// whether or not the project has the platform's directory, so a report (the
/// CLI's `doctor`) can show them for any project.
pub fn resolve(
    locator: &dyn PackageLocator,
    project_dir: &Path,
) -> Result<EmbeddingDirs, SyncError> {
    let dirs = locator.locate_many(project_dir, &[ANDROID_SHELL_PACKAGE, IOS_SHELL_PACKAGE])?;
    let [android, ios]: [PathBuf; 2] =
        dirs.try_into()
            .map_err(|dirs: Vec<PathBuf>| PackagesError::MetadataUnreadable {
                project_dir: project_dir.to_path_buf(),
                reason: format!("expected 2 package directories, got {}", dirs.len()),
            })?;
    Ok(EmbeddingDirs {
        android: native_dir(ANDROID_SHELL_PACKAGE, &android, ANDROID_EMBEDDING_REL)?,
        ios: native_dir(IOS_SHELL_PACKAGE, &ios, IOS_EMBEDDING_REL)?,
    })
}

/// The embedding directories [`resolve`] found.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmbeddingDirs {
    /// The Android embedding Gradle module.
    pub android: PathBuf,
    /// The iOS embedding Swift package.
    pub ios: PathBuf,
}

/// Brings `project_dir`'s Android and iOS wiring up to date with the crates
/// `cargo metadata` resolves for it (`--locked` when the project has a
/// `Cargo.lock`).
pub fn sync(project_dir: &Path) -> Result<Report, SyncError> {
    sync_with(&CargoLocator::new(&RealProcessRunner), project_dir)
}

/// [`sync`] through an injected locator.
///
/// Every package — the shell crate of each present platform and every
/// installed plugin's package with a module for one — is located in one
/// [`PackageLocator::locate_many`] call, and every native directory is
/// verified before anything is written, so a failure leaves the project as
/// it was.
pub fn sync_with(locator: &dyn PackageLocator, project_dir: &Path) -> Result<Report, SyncError> {
    let has_android = project_dir.join("android").is_dir();
    let has_ios = project_dir.join("ios").is_dir();
    let mut report = Report::skipped();
    if !has_android && !has_ios {
        return Ok(report);
    }

    let modules: Vec<(&'static str, NativeModule)> = installed_native_modules(project_dir)
        .into_iter()
        .filter(|(_, module)| match module.kind {
            NativeKind::GradleModule { .. } => has_android,
            NativeKind::SwiftPackage { .. } => has_ios,
        })
        .collect();

    let mut packages: Vec<&'static str> = Vec::new();
    if has_android {
        packages.push(ANDROID_SHELL_PACKAGE);
    }
    if has_ios {
        packages.push(IOS_SHELL_PACKAGE);
    }
    for (_, module) in &modules {
        if !packages.contains(&module.package) {
            packages.push(module.package);
        }
    }
    let package_dirs = locator.locate_many(project_dir, &packages)?;
    let package_dir = |package: &str| -> &Path {
        let at = packages
            .iter()
            .position(|p| *p == package)
            .expect("every wanted package was located");
        &package_dirs[at]
    };

    let android_target = has_android
        .then(|| {
            native_dir(
                ANDROID_SHELL_PACKAGE,
                package_dir(ANDROID_SHELL_PACKAGE),
                ANDROID_EMBEDDING_REL,
            )
        })
        .transpose()?;
    let ios_target = has_ios
        .then(|| {
            native_dir(
                IOS_SHELL_PACKAGE,
                package_dir(IOS_SHELL_PACKAGE),
                IOS_EMBEDDING_REL,
            )
        })
        .transpose()?;
    let mut module_targets = Vec::with_capacity(modules.len());
    for (_, module) in &modules {
        module_targets.push(native_dir(
            module.package,
            package_dir(module.package),
            module.dir_in_package,
        )?);
    }

    let mut module_wirings: Vec<Option<Wiring>> = vec![None; modules.len()];
    if let Some(target) = android_target {
        let mut entries = vec![(EMBEDDING_DIR_KEY.to_string(), target.clone())];
        let mut slots = Vec::new();
        for (at, ((_, module), module_target)) in modules.iter().zip(&module_targets).enumerate() {
            if let NativeKind::GradleModule { gradle_name } = module.kind {
                entries.push((plugin_module_key(gradle_name), module_target.clone()));
                slots.push(at);
            }
        }
        let mut written = write_properties(
            &project_dir.join(LOCAL_PROPERTIES),
            &entries,
            Missing::Append,
        )?
        .into_iter();
        report.android = written.next().expect("one change per entry");
        for (at, wiring) in slots.into_iter().zip(written) {
            module_wirings[at] = Some(wiring);
        }
        report.legacy_gradle_property = write_properties(
            &project_dir.join(GRADLE_PROPERTIES),
            &[(EMBEDDING_DIR_KEY.to_string(), target)],
            Missing::Skip,
        )?
        .remove(0);
    }
    if let Some(target) = ios_target {
        report.ios = link_dir(&project_dir.join(IOS_EMBEDDING_LINK), &target)?;
        for (at, ((_, module), module_target)) in modules.iter().zip(&module_targets).enumerate() {
            if let NativeKind::SwiftPackage { package_name } = module.kind {
                let link = project_dir.join(swift_package_link(package_name));
                module_wirings[at] = Some(link_dir(&link, module_target)?);
            }
        }
    }

    report.plugins = modules
        .into_iter()
        .zip(module_wirings)
        .map(|((plugin_id, module), wiring)| ModuleWiring {
            plugin_id,
            module,
            wiring: wiring.expect("every module belongs to a present platform"),
        })
        .collect();
    Ok(report)
}

/// Every native module of every registry plugin `project_dir`'s `Cargo.toml`
/// depends on (a `[dependencies]` entry by name or `package = …`, either
/// dependency form, never an `optional` one — cargo leaves a disabled
/// optional dependency out of the resolve, so it could not be located),
/// paired with its plugin's id. Base and optional-feature modules alike: an
/// unused key or link is harmless, a missing one fails the build. An
/// unreadable or unparseable manifest names no plugin — the locate that
/// follows reports the manifest problem itself.
fn installed_native_modules(project_dir: &Path) -> Vec<(&'static str, NativeModule)> {
    let Ok(text) = fs::read_to_string(project_dir.join("Cargo.toml")) else {
        return Vec::new();
    };
    let Ok(doc) = text.parse::<DocumentMut>() else {
        return Vec::new();
    };
    known_plugins()
        .into_iter()
        .filter(|spec| plugin_is_installed(spec, &doc))
        .flat_map(|spec| {
            spec.native_modules()
                .into_iter()
                .map(move |module| (spec.id, module))
        })
        .collect()
}

/// Whether `module`'s machine-local slot — its `local.properties` key or its
/// `ios/` link — exists at all in `project_dir`, whatever it points at.
pub(crate) fn module_slot_present(project_dir: &Path, module: &NativeModule) -> bool {
    match module.kind {
        NativeKind::GradleModule { gradle_name } => local_properties::read_value(
            &project_dir.join(LOCAL_PROPERTIES),
            &plugin_module_key(gradle_name),
        )
        .ok()
        .flatten()
        .is_some(),
        NativeKind::SwiftPackage { package_name } => {
            fs::symlink_metadata(project_dir.join(swift_package_link(package_name))).is_ok()
        }
    }
}

/// Writes each `(module, directory)` into `project_dir`'s machine-local
/// wiring — Gradle modules as [`plugin_module_key`] entries in one
/// [`LOCAL_PROPERTIES`] merge, Swift packages as [`swift_package_link`]
/// symlinks — returning one [`Wiring`] per module in order. The plugin-add
/// counterpart of [`sync`] for modules just added; it neither locates nor
/// verifies the directories (its caller does).
pub(crate) fn wire_modules(
    project_dir: &Path,
    modules: &[(NativeModule, PathBuf)],
) -> Result<Vec<Wiring>, SyncError> {
    let mut wirings: Vec<Option<Wiring>> = vec![None; modules.len()];
    let mut entries = Vec::new();
    let mut slots = Vec::new();
    for (at, (module, dir)) in modules.iter().enumerate() {
        match module.kind {
            NativeKind::GradleModule { gradle_name } => {
                entries.push((plugin_module_key(gradle_name), dir.clone()));
                slots.push(at);
            }
            NativeKind::SwiftPackage { package_name } => {
                let link = project_dir.join(swift_package_link(package_name));
                wirings[at] = Some(link_dir(&link, dir)?);
            }
        }
    }
    if !entries.is_empty() {
        let written = write_properties(
            &project_dir.join(LOCAL_PROPERTIES),
            &entries,
            Missing::Append,
        )?;
        for (at, wiring) in slots.into_iter().zip(written) {
            wirings[at] = Some(wiring);
        }
    }
    Ok(wirings
        .into_iter()
        .map(|w| w.expect("one wiring per module"))
        .collect())
}

/// `rel` under `package_dir`, verified to exist and made absolute and
/// canonical, so the value written does not depend on the directory a build
/// tool resolves it from.
fn native_dir(package: &'static str, package_dir: &Path, rel: &str) -> Result<PathBuf, SyncError> {
    let dir = package_dir.join(rel);
    if !dir.is_dir() {
        return Err(SyncError::EmbeddingMissing {
            package,
            package_dir: package_dir.to_path_buf(),
            embedding_dir: dir,
        });
    }
    Ok(host_path::canonicalize_simplified(&dir).unwrap_or(dir))
}

/// Merges `entries` (keys to directories, rendered forward-slashed) into the
/// properties file at `path`, one [`Wiring`] per entry.
fn write_properties(
    path: &Path,
    entries: &[(String, PathBuf)],
    missing: Missing,
) -> Result<Vec<Wiring>, SyncError> {
    let values: Vec<String> = entries
        .iter()
        .map(|(_, target)| host_path::to_portable_string(target))
        .collect();
    let pairs: Vec<(&str, &str)> = entries
        .iter()
        .zip(&values)
        .map(|((key, _), value)| (key.as_str(), value.as_str()))
        .collect();
    let changes =
        local_properties::merge(path, &pairs, missing).map_err(|source| SyncError::Io {
            action: "updating",
            path: path.to_path_buf(),
            source,
        })?;
    Ok(changes
        .into_iter()
        .zip(entries)
        .map(|(change, (_, target))| match change {
            Change::Unchanged => Wiring::Unchanged {
                target: target.clone(),
            },
            Change::Set { previous } => Wiring::Updated {
                target: target.clone(),
                previous,
            },
            Change::Absent => Wiring::Skipped,
        })
        .collect())
}

/// Points the symlink at `link` to `target`: created when absent, replaced
/// when it points elsewhere, left alone when it already points there (the
/// two compared after [`host_path::same_path`]'s normalisation, so a
/// Windows verbatim or differently-cased read-back still matches) or when
/// `link` is a real file or directory.
fn link_dir(link: &Path, target: &Path) -> Result<Wiring, SyncError> {
    let previous = match fs::symlink_metadata(link) {
        Err(err) if err.kind() == io::ErrorKind::NotFound => None,
        Err(source) => {
            return Err(SyncError::Io {
                action: "inspecting",
                path: link.to_path_buf(),
                source,
            });
        }
        Ok(meta) if !meta.file_type().is_symlink() => {
            return Ok(Wiring::Occupied {
                path: link.to_path_buf(),
                target: target.to_path_buf(),
            });
        }
        Ok(_) => {
            let current = fs::read_link(link).map_err(|source| SyncError::Io {
                action: "reading the symlink",
                path: link.to_path_buf(),
                source,
            })?;
            if host_path::same_path(&current, target) {
                return Ok(Wiring::Unchanged {
                    target: target.to_path_buf(),
                });
            }
            remove_link(link).map_err(|source| SyncError::Io {
                action: "replacing the symlink",
                path: link.to_path_buf(),
                source,
            })?;
            Some(current.display().to_string())
        }
    };

    match create_dir_link(target, link) {
        Ok(()) => Ok(Wiring::Updated {
            target: target.to_path_buf(),
            previous,
        }),
        Err(err) if is_unsupported(&err) => Ok(Wiring::Unsupported {
            target: target.to_path_buf(),
            reason: err.to_string(),
        }),
        Err(source) => Err(SyncError::Io {
            action: "creating the symlink",
            path: link.to_path_buf(),
            source,
        }),
    }
}

#[cfg(unix)]
fn create_dir_link(target: &Path, link: &Path) -> io::Result<()> {
    std::os::unix::fs::symlink(target, link)
}

#[cfg(windows)]
fn create_dir_link(target: &Path, link: &Path) -> io::Result<()> {
    std::os::windows::fs::symlink_dir(target, link)
}

#[cfg(not(any(unix, windows)))]
fn create_dir_link(_target: &Path, _link: &Path) -> io::Result<()> {
    Err(io::Error::new(
        io::ErrorKind::Unsupported,
        "this platform has no symlinks",
    ))
}

/// A directory symlink is removed as a directory on Windows and as a file
/// everywhere else.
fn remove_link(link: &Path) -> io::Result<()> {
    if cfg!(windows) {
        fs::remove_dir(link).or_else(|_| fs::remove_file(link))
    } else {
        fs::remove_file(link)
    }
}

/// Whether a symlink-creation failure means "this host cannot do it" rather
/// than a fault in the project: no symlink support at all, or Windows'
/// `ERROR_PRIVILEGE_NOT_HELD` (1314) for an account without Developer Mode.
fn is_unsupported(err: &io::Error) -> bool {
    err.kind() == io::ErrorKind::Unsupported || (cfg!(windows) && err.raw_os_error() == Some(1314))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::packages::StubLocator;
    use std::sync::atomic::{AtomicU32, Ordering};

    fn temp_dir(tag: &str) -> PathBuf {
        static COUNTER: AtomicU32 = AtomicU32::new(0);
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        let dir = std::env::temp_dir().join(format!(
            "frust-drive-platform-wiring-{tag}-{}-{n}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        host_path::canonicalize_simplified(&dir).unwrap()
    }

    /// A fake checkout holding both shell crates with their embeddings and
    /// the `iap` plugin crate with both of its native modules, plus the stub
    /// answering for it.
    fn checkout(root: &Path) -> (PathBuf, PathBuf, PathBuf, StubLocator) {
        let android = root.join("crates/frust-shell-android");
        let ios = root.join("crates/frust-shell-ios");
        let iap = root.join("plugins/iap");
        fs::create_dir_all(android.join(ANDROID_EMBEDDING_REL)).unwrap();
        fs::create_dir_all(ios.join(IOS_EMBEDDING_REL)).unwrap();
        fs::create_dir_all(iap.join(IAP_ANDROID_REL)).unwrap();
        fs::create_dir_all(iap.join(IAP_IOS_REL)).unwrap();
        let stub = StubLocator::new()
            .with(ANDROID_SHELL_PACKAGE, &android)
            .with(IOS_SHELL_PACKAGE, &ios)
            .with("frust-iap", &iap);
        (android, ios, iap, stub)
    }

    const IAP_ANDROID_REL: &str = "platform/android";
    const IAP_IOS_REL: &str = "platform/ios/FrustIap";

    const LOCAL: &str = "sdk.dir=/opt/android-sdk\r\n# a comment\nfrust.versionName=1.0\n";

    /// A project with `android/` (holding an Android-Studio-style
    /// [`LOCAL`] and a template `gradle.properties` without the key) and
    /// `ios/`, depending on no plugin.
    fn project(root: &Path) -> PathBuf {
        let project = root.join("app");
        fs::create_dir_all(project.join("android")).unwrap();
        fs::create_dir_all(project.join("ios/Runner.xcodeproj")).unwrap();
        fs::write(project.join(LOCAL_PROPERTIES), LOCAL).unwrap();
        fs::write(
            project.join(GRADLE_PROPERTIES),
            "org.gradle.jvmargs=-Xmx2048m\nandroid.useAndroidX=true\n",
        )
        .unwrap();
        fs::write(
            project.join("Cargo.toml"),
            "[package]\nname = \"app\"\n\n[dependencies]\n\
             frust = { package = \"frust-ui\", version = \"0.5.0\" }\n",
        )
        .unwrap();
        project
    }

    /// [`project`] depending on `frust-iap` in `form`.
    fn project_with_iap(root: &Path, form: &str) -> PathBuf {
        let project = project(root);
        let manifest = project.join("Cargo.toml");
        let text = fs::read_to_string(&manifest).unwrap();
        fs::write(&manifest, format!("{text}{form}\n")).unwrap();
        project
    }

    #[cfg(unix)]
    #[test]
    fn sync_writes_local_properties_and_links_the_ios_package() {
        let root = temp_dir("fresh");
        let (android, ios, _, stub) = checkout(&root);
        let project = project(&root);
        let gradle_before = fs::read(project.join(GRADLE_PROPERTIES)).unwrap();

        let report = sync_with(&stub, &project).unwrap();
        let android_target = android.join(ANDROID_EMBEDDING_REL);
        let ios_target = ios.join(IOS_EMBEDDING_REL);
        assert_eq!(
            report.android,
            Wiring::Updated {
                target: android_target.clone(),
                previous: None,
            }
        );
        assert_eq!(
            report.ios,
            Wiring::Updated {
                target: ios_target.clone(),
                previous: None,
            }
        );
        assert_eq!(report.legacy_gradle_property, Wiring::Skipped);
        assert!(report.plugins.is_empty());
        assert!(report.changed());

        // Every existing byte, CRLF ending included, is kept; the key is
        // appended. The tracked gradle.properties is not touched at all.
        assert_eq!(
            fs::read_to_string(project.join(LOCAL_PROPERTIES)).unwrap(),
            format!("{LOCAL}frust.embedding.dir={}\n", android_target.display())
        );
        assert_eq!(
            fs::read(project.join(GRADLE_PROPERTIES)).unwrap(),
            gradle_before
        );
        assert_eq!(
            fs::read_link(project.join(IOS_EMBEDDING_LINK)).unwrap(),
            ios_target
        );

        let lines = report.lines();
        assert_eq!(lines.len(), 2, "{lines:?}");
        assert!(lines[0].starts_with("Android embedding: android/local.properties -> "));
        assert!(lines[1].starts_with("iOS embedding: ios/FrustEmbedding -> "));
        let _ = fs::remove_dir_all(&root);
    }

    /// A plugin the manifest depends on — in either dependency form, or
    /// renamed — gets its Gradle module key and its Swift package link, all
    /// from the one `locate_many` call.
    #[cfg(unix)]
    #[test]
    fn installed_plugins_get_their_keys_and_links() {
        for form in [
            "frust-iap = \"0.5.0\"",
            "frust-iap = { version = \"0.5.0\" }",
            "store = { package = \"frust-iap\", path = \"../plugins/iap\" }",
        ] {
            let root = temp_dir("plugins");
            let (_, _, iap, stub) = checkout(&root);
            let project = project_with_iap(&root, form);

            let report = sync_with(&stub, &project).unwrap();
            assert_eq!(stub.calls(), 1, "{form}");
            let android_dir = iap.join(IAP_ANDROID_REL);
            let ios_dir = iap.join(IAP_IOS_REL);
            let wired: Vec<(&str, &Wiring)> = report
                .plugins
                .iter()
                .map(|m| (m.plugin_id, &m.wiring))
                .collect();
            assert_eq!(
                wired,
                [
                    (
                        "iap",
                        &Wiring::Updated {
                            target: android_dir.clone(),
                            previous: None
                        }
                    ),
                    (
                        "iap",
                        &Wiring::Updated {
                            target: ios_dir.clone(),
                            previous: None
                        }
                    ),
                ],
                "{form}"
            );
            assert_eq!(
                local_properties::read_value(
                    &project.join(LOCAL_PROPERTIES),
                    "frust.plugin.frust-iap.dir"
                )
                .unwrap(),
                Some(android_dir.display().to_string())
            );
            assert_eq!(
                fs::read_link(project.join("ios/FrustIap")).unwrap(),
                ios_dir
            );
            let lines = report.lines();
            assert_eq!(lines.len(), 4, "{lines:?}");
            assert!(
                lines[2].starts_with("Android module `:frust-iap`: android/local.properties -> "),
                "{lines:?}"
            );
            assert!(
                lines[3].starts_with("iOS package `FrustIap`: ios/FrustIap -> "),
                "{lines:?}"
            );
            let _ = fs::remove_dir_all(&root);
        }
    }

    /// An optional dependency is not in cargo's resolve unless a feature
    /// enables it, so it is never asked about; a dependency-only plugin has
    /// no module to wire.
    #[test]
    fn optional_and_module_less_plugins_are_not_located() {
        let root = temp_dir("optional");
        let (android, ios, _, _) = checkout(&root);
        let project = project_with_iap(
            &root,
            "frust-iap = { version = \"0.5.0\", optional = true }\n\
             frust-clipboard = \"0.5.0\"",
        );
        // A stub that knows only the shells: asking about frust-iap would
        // fail the whole sync.
        let stub = StubLocator::new()
            .with(ANDROID_SHELL_PACKAGE, &android)
            .with(IOS_SHELL_PACKAGE, &ios);
        let report = sync_with(&stub, &project).unwrap();
        assert!(report.plugins.is_empty(), "{report:?}");
        let _ = fs::remove_dir_all(&root);
    }

    #[cfg(unix)]
    #[test]
    fn a_second_sync_changes_nothing() {
        let root = temp_dir("idempotent");
        let (_, _, _, stub) = checkout(&root);
        let project = project_with_iap(&root, "frust-iap = \"0.5.0\"");
        sync_with(&stub, &project).unwrap();
        let before = fs::read(project.join(LOCAL_PROPERTIES)).unwrap();

        let report = sync_with(&stub, &project).unwrap();
        assert!(
            matches!(report.android, Wiring::Unchanged { .. }),
            "{report:?}"
        );
        assert!(matches!(report.ios, Wiring::Unchanged { .. }), "{report:?}");
        assert!(
            report
                .plugins
                .iter()
                .all(|m| matches!(m.wiring, Wiring::Unchanged { .. })),
            "{report:?}"
        );
        assert!(!report.changed());
        assert!(report.lines().is_empty());
        assert_eq!(fs::read(project.join(LOCAL_PROPERTIES)).unwrap(), before);
        let _ = fs::remove_dir_all(&root);
    }

    /// What `cargo update` does to a registry project: the crates resolve
    /// somewhere new, and the next sync follows them — keys and links alike.
    #[cfg(unix)]
    #[test]
    fn a_moved_package_replaces_the_values_and_the_links() {
        let root = temp_dir("moved");
        let (old_android, old_ios, _, stub) = checkout(&root.join("old"));
        let project = project_with_iap(&root, "frust-iap = \"0.5.0\"");
        sync_with(&stub, &project).unwrap();

        let (android, ios, iap, moved) = checkout(&root.join("new"));
        let report = sync_with(&moved, &project).unwrap();
        assert_eq!(
            report.ios,
            Wiring::Updated {
                target: ios.join(IOS_EMBEDDING_REL),
                previous: Some(old_ios.join(IOS_EMBEDDING_REL).display().to_string()),
            }
        );
        assert_eq!(
            report.android,
            Wiring::Updated {
                target: android.join(ANDROID_EMBEDDING_REL),
                previous: Some(
                    old_android
                        .join(ANDROID_EMBEDDING_REL)
                        .display()
                        .to_string()
                ),
            }
        );
        assert!(report.plugins.iter().all(|m| m.wiring.changed()));
        assert_eq!(
            fs::read_link(project.join("ios/FrustIap")).unwrap(),
            iap.join(IAP_IOS_REL)
        );
        let properties = fs::read_to_string(project.join(LOCAL_PROPERTIES)).unwrap();
        assert_eq!(properties.matches("frust.embedding.dir=").count(), 1);
        assert_eq!(properties.matches("frust.plugin.frust-iap.dir=").count(), 1);
        assert!(properties.starts_with(LOCAL), "{properties}");
        let _ = fs::remove_dir_all(&root);
    }

    /// A value carrying `java.util.Properties` specials — a Windows drive
    /// colon, a backslash, non-ASCII — is written escaped and reads back as
    /// the directory itself.
    #[cfg(unix)]
    #[test]
    fn values_are_written_with_properties_escapes() {
        let root = temp_dir("escapes");
        let odd = root.join("zoë: #1!/crates/frust-shell-android");
        fs::create_dir_all(odd.join(ANDROID_EMBEDDING_REL)).unwrap();
        let project = root.join("app");
        fs::create_dir_all(project.join("android")).unwrap();
        fs::write(project.join("Cargo.toml"), "[package]\nname = \"app\"\n").unwrap();
        let stub = StubLocator::new().with(ANDROID_SHELL_PACKAGE, &odd);

        let report = sync_with(&stub, &project).unwrap();
        let target = odd.join(ANDROID_EMBEDDING_REL);
        assert!(report.android.changed());
        let text = fs::read_to_string(project.join(LOCAL_PROPERTIES)).unwrap();
        assert!(text.is_ascii(), "{text}");
        assert!(text.contains("zo\\u00EB\\: \\#1\\!/"), "{text}");
        assert_eq!(
            local_properties::read_value(&project.join(LOCAL_PROPERTIES), EMBEDDING_DIR_KEY)
                .unwrap(),
            Some(target.display().to_string())
        );
        assert!(
            !sync_with(&stub, &project).unwrap().changed(),
            "an escaped value compares unescaped, so a second sync is a no-op"
        );
        let _ = fs::remove_dir_all(&root);
    }

    /// A project generated by an earlier template reads the embedding from
    /// `gradle.properties`: an existing key there is kept current (never
    /// added to a project that lacks it), and `local.properties` gains it too.
    #[test]
    fn a_legacy_gradle_property_is_refreshed_in_place() {
        let root = temp_dir("legacy");
        let (android, _, _, stub) = checkout(&root);
        let project = project(&root);
        let legacy = "org.gradle.jvmargs=-Xmx2048m\r\n# frust.embedding.dir=commented/out\n\
                      frust.embedding.dir=placeholder\n";
        fs::write(project.join(GRADLE_PROPERTIES), legacy).unwrap();

        let report = sync_with(&stub, &project).unwrap();
        let target = android.join(ANDROID_EMBEDDING_REL);
        assert_eq!(
            report.legacy_gradle_property,
            Wiring::Updated {
                target: target.clone(),
                previous: Some("placeholder".into()),
            }
        );
        assert_eq!(
            fs::read_to_string(project.join(GRADLE_PROPERTIES)).unwrap(),
            legacy.replace(
                "frust.embedding.dir=placeholder",
                &format!("frust.embedding.dir={}", target.display())
            )
        );
        assert!(report.android.changed());
        assert!(
            report.lines()[0].starts_with("Android embedding: android/gradle.properties -> "),
            "{:?}",
            report.lines()
        );
        assert!(
            !sync_with(&stub, &project).unwrap().changed(),
            "the legacy key is idempotent too"
        );
        let _ = fs::remove_dir_all(&root);
    }

    /// A platform directory that is absent is skipped, and cargo is not asked
    /// about its packages — a project with neither never reaches the locator.
    #[test]
    fn absent_platform_directories_are_skipped_without_locating() {
        let root = temp_dir("skipped");
        let project = root.join("desktop_only");
        fs::create_dir_all(&project).unwrap();
        fs::write(
            project.join("Cargo.toml"),
            "[package]\nname = \"app\"\n[dependencies]\nfrust-iap = \"0.5.0\"\n",
        )
        .unwrap();
        let failing = StubLocator::failing("must not be asked");
        let report = sync_with(&failing, &project).unwrap();
        assert_eq!(report.android, Wiring::Skipped);
        assert_eq!(report.ios, Wiring::Skipped);
        assert_eq!(failing.calls(), 0);

        // Android only: neither the iOS shell nor the plugin's iOS package
        // is involved, and the plugin's Gradle module is still wired.
        fs::create_dir_all(project.join("android")).unwrap();
        let android_dir = root.join("crates/frust-shell-android");
        fs::create_dir_all(android_dir.join(ANDROID_EMBEDDING_REL)).unwrap();
        let iap = root.join("plugins/iap");
        fs::create_dir_all(iap.join(IAP_ANDROID_REL)).unwrap();
        let android_only = StubLocator::new()
            .with(ANDROID_SHELL_PACKAGE, &android_dir)
            .with("frust-iap", &iap);
        let report = sync_with(&android_only, &project).unwrap();
        assert!(report.android.changed());
        assert_eq!(report.ios, Wiring::Skipped);
        assert_eq!(report.plugins.len(), 1, "{report:?}");
        assert!(!project.join("ios").exists());
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn locate_failures_and_incomplete_packages_are_errors() {
        let root = temp_dir("errors");
        let project = project_with_iap(&root, "frust-iap = \"0.5.0\"");
        let err = sync_with(&StubLocator::failing("offline"), &project).unwrap_err();
        assert!(matches!(err, SyncError::Locate(_)), "{err:?}");
        assert!(err.to_string().contains("offline"), "{err}");

        // The shells are complete but the plugin package lacks its module:
        // nothing at all is written, not even the embedding key.
        let (android, ios, _, _) = checkout(&root);
        let bare = root.join("bare");
        fs::create_dir_all(&bare).unwrap();
        let stub = StubLocator::new()
            .with(ANDROID_SHELL_PACKAGE, &android)
            .with(IOS_SHELL_PACKAGE, &ios)
            .with("frust-iap", &bare);
        let err = sync_with(&stub, &project).unwrap_err();
        assert!(
            matches!(err, SyncError::EmbeddingMissing { package, .. } if package == "frust-iap"),
            "{err:?}"
        );
        assert_eq!(
            fs::read_to_string(project.join(LOCAL_PROPERTIES)).unwrap(),
            LOCAL,
            "a failed sync writes nothing"
        );
        assert!(fs::symlink_metadata(project.join(IOS_EMBEDDING_LINK)).is_err());
        let _ = fs::remove_dir_all(&root);
    }

    /// A real directory where a link belongs is user content — reported,
    /// never removed.
    #[test]
    fn a_real_directory_in_place_of_the_link_is_left_alone() {
        let root = temp_dir("occupied");
        let (_, _, _, stub) = checkout(&root);
        let project = project(&root);
        fs::create_dir_all(project.join(IOS_EMBEDDING_LINK).join("Sources")).unwrap();

        let report = sync_with(&stub, &project).unwrap();
        assert!(matches!(report.ios, Wiring::Occupied { .. }), "{report:?}");
        assert!(project.join(IOS_EMBEDDING_LINK).join("Sources").is_dir());
        assert!(report.lines()[1].contains("is not a symlink"));
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn resolve_reports_both_embeddings_without_writing() {
        let root = temp_dir("resolve");
        let (android, ios, _, stub) = checkout(&root);
        let project = root.join("no_platform_dirs");
        fs::create_dir_all(&project).unwrap();
        assert_eq!(
            resolve(&stub, &project).unwrap(),
            EmbeddingDirs {
                android: android.join(ANDROID_EMBEDDING_REL),
                ios: ios.join(IOS_EMBEDDING_REL),
            }
        );
        assert!(!project.join("android").exists() && !project.join("ios").exists());
        assert!(matches!(
            resolve(&StubLocator::failing("offline"), &project),
            Err(SyncError::Locate(_))
        ));
        let _ = fs::remove_dir_all(&root);
    }

    /// `wire_modules` (the plugin-add path) writes the same key and link
    /// `sync` would, and reports an already-current slot unchanged.
    #[cfg(unix)]
    #[test]
    fn wire_modules_writes_keys_and_links_for_the_given_modules() {
        let root = temp_dir("wire-modules");
        let (_, _, iap, _) = checkout(&root);
        let project = project(&root);
        let iap_spec = known_plugins()
            .into_iter()
            .find(|spec| spec.id == "iap")
            .unwrap();
        let modules: Vec<(NativeModule, PathBuf)> = iap_spec
            .native_modules()
            .into_iter()
            .map(|m| (m, iap.join(m.dir_in_package)))
            .collect();
        assert_eq!(modules.len(), 2);
        assert!(
            modules
                .iter()
                .all(|(m, _)| !module_slot_present(&project, m))
        );

        let first = wire_modules(&project, &modules).unwrap();
        assert!(first.iter().all(Wiring::changed), "{first:?}");
        assert!(
            modules
                .iter()
                .all(|(m, _)| module_slot_present(&project, m))
        );
        assert_eq!(
            fs::read_link(project.join("ios/FrustIap")).unwrap(),
            iap.join(IAP_IOS_REL)
        );
        let second = wire_modules(&project, &modules).unwrap();
        assert!(
            second.iter().all(|w| matches!(w, Wiring::Unchanged { .. })),
            "{second:?}"
        );
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn keys_and_links_are_named_after_the_module() {
        assert_eq!(
            plugin_module_key(":frust-secure-storage"),
            "frust.plugin.frust-secure-storage.dir"
        );
        assert_eq!(swift_package_link("FrustCamera"), "ios/FrustCamera");
    }
}
