import UIKit
import QuartzCore
import CFrustFFI

// Generated by `frust create` (platform-views task 09). Hosts native UIKit
// sibling views alongside the Frust render surface, driven by the
// per-frame command channel `frust_platform_view_commands_json` exposes.
// The iOS mirror of Android's `dev.frust.FrustViewHost`.
//
// Lifecycle: `FrustViewController` owns one host, constructed once
// `frust_init` has a handle, and calls `poll(handle:)` from its
// `CADisplayLink` callback right after `frust_render_frame`. A poll reads
// the JSON backlog accumulated since the last acknowledged generation,
// applies every create/reposition/dispose command inside a single
// `CATransaction` (implicit animations disabled — a reposition must snap,
// not tween), and records the new generation as acknowledged.
//
// Coordinate boundary: rects arrive in PHYSICAL pixels (the physical-at-FFI
// convention shared with Android). UIKit lays out in logical points, so
// every rect is divided by the container's `contentScaleFactor` at the
// boundary (see [pointsRect]).
//
// Z-order: in translucent (Mode B) apps the native views sit BELOW the
// Frust surface (which is non-opaque, so they show through); in opaque
// (Mode A) apps they sit ABOVE it. The choice is fixed per-app by the
// controller's `translucentSurface` const in v1 (per-slot z policy is
// future work).
final class FrustViewHost {
    /// A live slot: the `wrapper` is the sibling added to the hierarchy (it
    /// carries position + clip), `content` is the factory-produced view
    /// inside it, and `factory` is retained for its `updateParams`/
    /// `disposeView` hooks.
    private struct Slot {
        let wrapper: UIView
        let content: UIView
        let factory: FrustPlatformViewFactory
        /// Mode B input forwarding (native-widgets spike 3): whether a touch
        /// landing inside this slot's rect should fall through the Frust
        /// surface to [content] (see `FrustView.hitTest`).
        let interactive: Bool
        /// The z-shield list (logical points, same space as [wrapper]'s
        /// frame): regions where Frust content drawn over the slot keeps
        /// winning input. Replaced wholesale by every `update` command.
        var shields: [CGRect]
    }

    /// Mode B input forwarding (native-widgets spike 3): whether a touch at
    /// `point` (in the shared superview's coordinate space — the Frust
    /// surface fills it at origin zero, so `FrustView`-local and superview
    /// space coincide) belongs to an interactive hosted view. `true` ⇒ the
    /// Frust surface's `hitTest` returns nil and UIKit routes the whole
    /// gesture to the sibling natively.
    func interactiveSlotContains(_ point: CGPoint) -> Bool {
        for slot in slots.values {
            guard slot.interactive, !slot.wrapper.isHidden else { continue }
            guard slot.wrapper.frame.contains(point) else { continue }
            if slot.shields.contains(where: { $0.contains(point) }) { continue }
            return true
        }
        return false
    }

    /// The Frust surface view (a `FrustView`); hosted wrappers are inserted
    /// as its siblings in the same superview, so this is `unowned` — the
    /// controller outlives the host and owns the view.
    private unowned let containerView: UIView
    /// `true` when the app requested a translucent surface (Mode B): hosted
    /// views go BELOW the Frust surface. `false` (Mode A): ABOVE.
    private let translucent: Bool

    private var slots: [UInt64: Slot] = [:]
    /// Slots whose factory failed to resolve — remembered so a repeated
    /// `create` for the same id doesn't re-log every frame. Never crashes
    /// the frame loop (a bad `viewType` is an app bug, not a fatal one).
    private var deadSlots: Set<UInt64> = []
    /// Resolved factories, cached per `viewType` (`NSClassFromString` +
    /// instantiation is done once per type, not per slot).
    private var factoryCache: [String: FrustPlatformViewFactory] = [:]

    /// The last generation whose command batch has been applied. Passed back
    /// into `frust_platform_view_commands_json` so the Rust side can return
    /// the cheap null "no change" fast path when nothing new has happened.
    private(set) var ackedGeneration: UInt64 = 0

    init(containerView: UIView, translucent: Bool) {
        self.containerView = containerView
        self.translucent = translucent
    }

    /// Pull and apply this frame's platform-view command batch. Cheap when
    /// idle: a null return (nothing changed since [ackedGeneration]) is the
    /// common case and does no work. Called on the main thread (the
    /// `CADisplayLink` callback), so all UIKit mutation below is main-thread.
    func poll(handle: UnsafeMutableRawPointer) {
        guard let raw = frust_platform_view_commands_json(handle, ackedGeneration) else { return }
        defer { frust_string_free(raw) }
        let data = Data(bytes: raw, count: strlen(raw))
        guard
            let root = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any],
            let generation = (root["generation"] as? NSNumber)?.uint64Value
        else { return }
        let commands = (root["commands"] as? [[String: Any]]) ?? []

        // One transaction for the whole batch, with implicit animations
        // disabled: a reposition snaps to its new frame rather than tweening
        // (frust owns all motion; a UIKit auto-animation would fight it).
        CATransaction.begin()
        CATransaction.setDisableActions(true)
        for command in commands {
            apply(command)
        }
        CATransaction.commit()

        ackedGeneration = generation
    }

    private func apply(_ command: [String: Any]) {
        guard let op = command["op"] as? String,
            let slotId = (command["slot"] as? NSNumber)?.uint64Value
        else { return }
        switch op {
        case "create":
            applyCreate(slotId: slotId, command: command)
        case "update":
            applyUpdate(slotId: slotId, command: command)
        case "updateParams":
            applyUpdateParams(slotId: slotId, command: command)
        case "dispose":
            applyDispose(slotId: slotId)
        default:
            break  // Unknown op (forward-compat): ignore rather than crash.
        }
    }

    private func applyCreate(slotId: UInt64, command: [String: Any]) {
        guard slots[slotId] == nil else { return }
        guard let viewType = command["viewType"] as? String else { return }
        let params = (command["params"] as? String) ?? ""

        guard let factory = resolveFactory(viewType) else {
            // Dead slot: log once, never crash the frame loop.
            if deadSlots.insert(slotId).inserted {
                NSLog("Frust: no platform-view factory for `\(viewType)` (slot \(slotId)) — skipping")
            }
            return
        }

        let content = factory.createView(paramsJson: params)
        let wrapper = UIView()
        wrapper.isHidden = true  // Shown by the first `update` with visible=true.
        wrapper.addSubview(content)

        // Mode B (translucent): behind the Frust surface. Mode A: in front.
        if translucent {
            containerView.superview?.insertSubview(wrapper, belowSubview: containerView)
        } else {
            containerView.superview?.insertSubview(wrapper, aboveSubview: containerView)
        }
        slots[slotId] = Slot(
            wrapper: wrapper,
            content: content,
            factory: factory,
            interactive: (command["interactive"] as? Bool) ?? false,
            shields: []
        )
    }

    private func applyUpdate(slotId: UInt64, command: [String: Any]) {
        guard let slot = slots[slotId] else { return }
        let scale = containerView.contentScaleFactor
        guard let rect = pointsRect(command["rect"], scale: scale) else { return }
        let clip = pointsRect(command["clip"], scale: scale)
        let visible = (command["visible"] as? Bool) ?? true

        // The wrapper carries the clip window; the content is positioned
        // relative to it. With no clip (or a clip that fully contains the
        // rect) the wrapper IS the rect and no masking is needed — masking
        // only when clip < rect avoids a gratuitous offscreen clip pass.
        if let clip, clip != rect {
            slot.wrapper.frame = clip
            slot.wrapper.layer.masksToBounds = true
            slot.content.frame = CGRect(
                x: rect.origin.x - clip.origin.x,
                y: rect.origin.y - clip.origin.y,
                width: rect.width,
                height: rect.height
            )
        } else {
            slot.wrapper.frame = rect
            slot.wrapper.layer.masksToBounds = false
            slot.content.frame = slot.wrapper.bounds
        }
        slot.wrapper.isHidden = !visible

        // The z-shield list rides every update in the same physical-px space
        // as `rect` — converted to points and replaced wholesale.
        let shieldArrays = (command["shields"] as? [Any]) ?? []
        slots[slotId]?.shields = shieldArrays.compactMap { pointsRect($0, scale: scale) }
    }

    private func applyUpdateParams(slotId: UInt64, command: [String: Any]) {
        guard let slot = slots[slotId], let params = command["params"] as? String else { return }
        slot.factory.updateParams?(slot.content, paramsJson: params)
    }

    private func applyDispose(slotId: UInt64) {
        deadSlots.remove(slotId)
        guard let slot = slots.removeValue(forKey: slotId) else { return }
        slot.factory.disposeView?(slot.content)
        slot.wrapper.removeFromSuperview()
    }

    /// Resolve (and cache) the factory for a `viewType`. `viewType` is the
    /// ObjC runtime class name of an `@objc(...)`-annotated `NSObject`
    /// factory (see `FrustPlatformViewFactory`'s doc). A failure returns
    /// `nil` — the caller marks the slot dead, never crashes.
    ///
    /// **Check order is part of the contract, not an implementation
    /// detail:** `NSClassFromString` resolves the class object, then
    /// `class_conformsToProtocol` verifies `FrustPlatformViewFactory`
    /// conformance on the *class object* — BOTH BEFORE `init()` ever runs.
    /// iOS has no package-prefix convention (bare `@objc` names are the
    /// contract — `docs/CODE_STANDARDS.md`'s Naming Conventions), so
    /// conformance-before-init is the whole fix: instantiating an
    /// arbitrary attacker-influenced class name before checking what it is
    /// lets a no-arg `init()`'s side effects run unconditionally.
    private func resolveFactory(_ viewType: String) -> FrustPlatformViewFactory? {
        if let cached = factoryCache[viewType] {
            return cached
        }
        guard
            let cls = NSClassFromString(viewType) as? NSObject.Type,
            class_conformsToProtocol(cls, FrustPlatformViewFactory.self)
        else {
            return nil
        }
        guard let factory = cls.init() as? FrustPlatformViewFactory else {
            return nil
        }
        factoryCache[viewType] = factory
        return factory
    }

    /// Convert a `[x, y, w, h]` PHYSICAL-pixel JSON array into a logical-point
    /// `CGRect` (dividing by the display scale — the physical-at-FFI boundary).
    /// `nil` for a missing/`null`/malformed value (e.g. a `null` clip).
    private func pointsRect(_ value: Any?, scale: CGFloat) -> CGRect? {
        guard let array = value as? [Any], array.count == 4 else { return nil }
        let numbers = array.compactMap { ($0 as? NSNumber)?.doubleValue }
        guard numbers.count == 4, scale > 0 else { return nil }
        return CGRect(
            x: numbers[0] / scale,
            y: numbers[1] / scale,
            width: numbers[2] / scale,
            height: numbers[3] / scale
        )
    }
}

#if DEBUG
    /// A debug-only factory shipped with the template so a generated app can
    /// exercise the platform-view path end-to-end without writing a factory:
    /// set a `platform_view` widget's `viewType` to `"FrustTestLabelFactory"`.
    /// The label self-updates a counter on its own timer — independent of the
    /// Frust frame loop — which is how task 11's trace check proves a hosted
    /// view redraws with ZERO frust frames. Guarded by `#if DEBUG` and kept in
    /// this file (not a third pbxproj source) so a release build drops it.
    @objc(FrustTestLabelFactory)
    final class FrustTestLabelFactory: NSObject, FrustPlatformViewFactory {
        func createView(paramsJson: String) -> UIView {
            return FrustTestLabel(paramsJson: paramsJson)
        }
    }

    /// A `UILabel` that redraws itself every 0.5s off a `Timer` — no Frust
    /// frame involved. Displays its creation `paramsJson` plus a live counter.
    private final class FrustTestLabel: UILabel {
        private let paramsJson: String
        private var counter = 0
        private var timer: Timer?

        init(paramsJson: String) {
            self.paramsJson = paramsJson
            super.init(frame: .zero)
            numberOfLines = 0
            textAlignment = .center
            textColor = .white
            backgroundColor = UIColor.systemBlue.withAlphaComponent(0.6)
            render()
            let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
                guard let self else { return }
                self.counter += 1
                self.render()
            }
            RunLoop.main.add(timer, forMode: .common)
            self.timer = timer
        }

        required init?(coder: NSCoder) {
            fatalError("init(coder:) has not been implemented")
        }

        private func render() {
            text = "\(paramsJson)\n#\(counter)"
        }

        deinit {
            timer?.invalidate()
        }
    }
#endif
