import UIKit
import QuartzCore

// Generated by `frust create` (spec Phase 3 §10.2). A UIView whose backing
// layer is a `CAMetalLayer`, so Frust's wgpu/Metal renderer can draw
// directly into it (the layer pointer is handed to `frust_init`).
final class FrustView: UIView {
    override class var layerClass: AnyClass {
        return CAMetalLayer.self
    }

    var metalLayer: CAMetalLayer {
        // Safe: `layerClass` guarantees the backing layer is a CAMetalLayer.
        return layer as! CAMetalLayer
    }

    // MARK: - Text input (spec §9, Phase 4B)
    //
    // Frust adopts the *full* `UITextInput` protocol (Flutter-style) so the
    // system gives us autocorrect, the predictive bar, CJK marked text, and
    // dictation — a `UIKeyInput`-only view gets none of those. The protocol
    // conformance lives in `FrustTextInput.swift`; the stored state it needs
    // lives here (extensions cannot add stored properties).
    //
    // The mirror is a UTF-16 `NSMutableString` (UIKit's native text unit). Every
    // mutation updates the mirror + selection/marked ranges, then `syncToRust()`
    // round-trips the whole value through the FFI (`frust_ime_apply` →
    // `frust_ime_state_json`) and reconciles against what Rust produced.

    /// The platform-owned mirror of the focused field's text (UTF-16).
    let mirror = NSMutableString()
    /// The current selection as a UTF-16 range (`length == 0` is a caret).
    var selectedRange = NSRange(location: 0, length: 0)
    /// The composing (marked) region, or `NSNotFound` location when not composing.
    var markedRange = NSRange(location: NSNotFound, length: 0)
    /// UITextInput's change-notification sink (weak per the protocol contract).
    weak var inputDelegate: UITextInputDelegate?
    /// Off-the-shelf tokenizer (word/line granularity for selection gestures).
    lazy var tokenizer: UITextInputTokenizer = UITextInputStringTokenizer(textInput: self)
    /// Styling for marked text (unused; kept to satisfy the protocol).
    var markedTextStyle: [NSAttributedString.Key: Any]?
    /// The last caret rectangle Rust published (logical px == view points on iOS),
    /// used to approximate `caretRect(for:)` / `firstRect(for:)` geometry.
    var lastCaretRect: CGRect?

    // UITextInputTraits: `autocorrectionType = .yes` is required for the system to
    // actually offer autocorrect — adopting the protocol alone is insufficient.
    var autocorrectionType: UITextAutocorrectionType = .yes
    var keyboardType: UIKeyboardType = .default
    var returnKeyType: UIReturnKeyType = .done

    /// A custom editor view must opt in to becoming first responder for the
    /// keyboard to appear.
    override var canBecomeFirstResponder: Bool { true }

    /// Set by the view controller: performs the Rust FFI round-trip
    /// (`frust_ime_apply` with the given UTF-16 mirror state, then
    /// `frust_ime_state_json`) and returns the reconciled editing state Rust
    /// produced (already parsed + freed), or `nil` when there is no live handle.
    var imeRoundTrip: (
        (_ text: String, _ selBase: Int, _ selExt: Int, _ compBase: Int, _ compExt: Int)
            -> [String: Any]?
    )?

    // Touch delivery (spec §9). We own the gesture logic in Rust, so we handle
    // the raw UIResponder touch callbacks directly rather than attaching
    // UIGestureRecognizers. The controller sets `onTouch` to bridge into the
    // `frust_dispatch_touch` FFI call; `phase` is the fixed ABI shared with
    // the Rust side (0 = began, 1 = moved, 2 = ended, 3 = cancelled).
    var onTouch: ((UInt32, CGPoint) -> Void)?

    /// Mode B input forwarding (native-widgets spike 3): set by the
    /// controller to `FrustViewHost.interactiveSlotContains`. When a touch
    /// lands inside an interactive hosted slot's rect (outside its
    /// z-shields), this view's `hitTest` returns nil so UIKit falls through
    /// to the native sibling BELOW and routes the whole gesture there —
    /// touch-DOWN decides ownership, natively, with real UIControl
    /// semantics. Everywhere else the surface behaves exactly as before.
    var interactiveSlotHitTest: ((CGPoint) -> Bool)?

    override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        if let probe = interactiveSlotHitTest, probe(point) {
            return nil
        }
        return super.hitTest(point, with: event)
    }

    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        forward(touches, phase: 0)
    }

    override func touchesMoved(_ touches: Set<UITouch>, with event: UIEvent?) {
        forward(touches, phase: 1)
    }

    override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {
        forward(touches, phase: 2)
    }

    override func touchesCancelled(_ touches: Set<UITouch>, with event: UIEvent?) {
        forward(touches, phase: 3)
    }

    /// Forward the first touch's location (logical points, in this view's space)
    /// to the Rust side. First-touch only in v1 — multi-touch is future work.
    private func forward(_ touches: Set<UITouch>, phase: UInt32) {
        guard let touch = touches.first else { return }
        onTouch?(phase, touch.location(in: self))
    }
}
