import UIKit
import QuartzCore

// Generated by `frust create`. A UIView hosting a `CAMetalLayer` sublayer
// that fills its bounds, so Frust's wgpu/Metal renderer can draw directly into
// it (the layer pointer is handed to `frust_init`).
//
// It is also the app's single `UITextInput` responder (see Text input below
// and `FrustTextInput.swift`) and — through the
// `UIResponderStandardEditActions` methods at the bottom of this file — the
// responder UIKit's own edit menu and a hardware keyboard's Cmd+C/X/V/A route
// their clipboard verbs to.

/// Which clipboard verbs the focused field says apply to its current selection
/// — the enabled set UIKit's edit menu is answered from, not a menu layout.
///
/// Mirrors the Rust-side `SelectionToolbarActions` the framework publishes and
/// `frust_selection_toolbar_json` reports; `FrustViewController`'s per-frame
/// poll keeps it current and `FrustView.canPerformAction(_:withSender:)`
/// answers from it. The *field's* call, not the menu's: an obscured field
/// refuses copy and cut, a read-only one refuses cut and paste — so the system
/// menu offers exactly the verbs the framework itself would have offered.
struct FrustEditActions {
    var copy = false
    var cut = false
    var paste = false
    var selectAll = false

    /// Nothing applies — what the flags read while no field has a selection.
    static let none = FrustEditActions()
}

/// The `cmd` codes `frust_edit_command` takes.
///
/// **DO NOT renumber.** A fixed numeric ABI shared with the Rust glue
/// (`frust_shell_ios`'s `edit_command_from_code`), exactly like the touch
/// phases `FrustView.forward(_:phase:)` sends; changing a value on one side
/// alone silently re-points a verb at a different one. Only `paste` carries a
/// payload — copy and cut carry nothing, because the *widget* owns the
/// selection and answers by filling the slot `frust_take_clipboard_write`
/// drains.
enum FrustEditCommand {
    static let copy: UInt8 = 0
    static let cut: UInt8 = 1
    static let paste: UInt8 = 2
    static let selectAll: UInt8 = 3
}

/// The Metal layer's delegate: answers every action lookup with `NSNull`, so
/// no property change on the layer — its frame here on the main thread, or
/// `drawableSize`/`opaque`/`pixelFormat` from the render thread — ever runs an
/// implicit animation.
///
/// A backing layer gets this for free from its `UIView`; a standalone
/// sublayer would otherwise animate every animatable change over 0.25 s. It is
/// deliberately *not* the view: a layer whose delegate is a `UIView` is one
/// UIKit forbids touching off the main thread (see `FrustView.metalLayer`).
/// Stateless, so it is safe to consult from the render thread.
private final class FrustMetalLayerActions: NSObject, CALayerDelegate {
    func action(for layer: CALayer, forKey event: String) -> CAAction? {
        NSNull()
    }
}

final class FrustView: UIView {
    /// The layer Frust renders into — a sublayer at index 0 of this view's
    /// own (plain) backing layer, kept at the view's bounds by
    /// `layoutSubviews`.
    ///
    /// **Must not become the backing layer (`layerClass`).** The renderer
    /// configures this layer from its render thread (wgpu's
    /// `Surface::configure` sets `opaque`, `pixelFormat`, `drawableSize`,
    /// `colorspace`, … on first install, on every `frust_resize`, and on
    /// surface self-heal), and UIKit rejects any property write to a view's
    /// backing layer off the main thread ("Modifying properties of a view's
    /// layer off the main thread is not allowed"). A sublayer whose delegate
    /// is not a view is outside that rule. Z-order is unaffected: hosted
    /// native views are siblings of this view (`FrustViewHost`), never
    /// subviews, so nothing else shares this layer tree.
    let metalLayer = CAMetalLayer()

    /// Retained here because `CALayer.delegate` is weak.
    private let metalLayerActions = FrustMetalLayerActions()

    override init(frame: CGRect) {
        super.init(frame: frame)
        installMetalLayer()
    }

    required init?(coder: NSCoder) {
        super.init(coder: coder)
        installMetalLayer()
    }

    private func installMetalLayer() {
        metalLayer.delegate = metalLayerActions
        metalLayer.frame = bounds
        layer.insertSublayer(metalLayer, at: 0)
        // Required for `touchesBegan`/`touchesMoved`/… to ever report more
        // than one simultaneous `UITouch` — UIKit drops every contact past
        // the first on a view that doesn't opt in. See Touch delivery below.
        isMultipleTouchEnabled = true
    }

    /// Keeps the Metal layer at the view's bounds. Runs before the
    /// controller's `viewDidLayoutSubviews`, so the frame is current by the
    /// time `updateSurface` sizes the drawable from those same bounds.
    override func layoutSubviews() {
        super.layoutSubviews()
        metalLayer.frame = bounds
    }

    // MARK: - Text input
    //
    // Frust adopts the *full* `UITextInput` protocol (Flutter-style) so the
    // system gives us autocorrect, the predictive bar, CJK marked text, and
    // dictation — a `UIKeyInput`-only view gets none of those. The protocol
    // conformance lives in `FrustTextInput.swift`; the stored state it needs
    // lives here (extensions cannot add stored properties).
    //
    // The mirror is a UTF-16 `NSMutableString` (UIKit's native text unit). Every
    // mutation updates the mirror + selection/marked ranges, then `syncToRust()`
    // round-trips the whole value through the FFI (`frust_ime_apply` →
    // `frust_ime_state_json`) and reconciles against what Rust produced.

    /// The platform-owned mirror of the focused field's text (UTF-16).
    let mirror = NSMutableString()
    /// The current selection as a UTF-16 range (`length == 0` is a caret).
    var selectedRange = NSRange(location: 0, length: 0)
    /// The composing (marked) region, or `NSNotFound` location when not composing.
    var markedRange = NSRange(location: NSNotFound, length: 0)
    /// UITextInput's change-notification sink (weak per the protocol contract).
    weak var inputDelegate: UITextInputDelegate?
    /// Off-the-shelf tokenizer (word/line granularity for selection gestures).
    lazy var tokenizer: UITextInputTokenizer = UITextInputStringTokenizer(textInput: self)
    /// Styling for marked text (unused; kept to satisfy the protocol).
    var markedTextStyle: [NSAttributedString.Key: Any]?
    /// The last caret rectangle Rust published (logical px == view points on iOS),
    /// used to approximate `caretRect(for:)` / `firstRect(for:)` geometry.
    var lastCaretRect: CGRect?

    // UITextInputTraits: `autocorrectionType = .yes` is required for the system to
    // actually offer autocorrect — adopting the protocol alone is insufficient.
    var autocorrectionType: UITextAutocorrectionType = .yes
    var keyboardType: UIKeyboardType = .default
    var returnKeyType: UIReturnKeyType = .done

    // UITextInputTraits: the security/suggestion knobs the published
    // `ImeState.content_type` hint drives (see
    // `FrustViewController.applyImeContentType`, called from `syncImeFocus`
    // right before `becomeFirstResponder`, so the keyboard is configured
    // correctly from the first character rather than being reconfigured
    // mid-session). `isSecureTextEntry` is the load-bearing one — it is what
    // suppresses the QuickType suggestion bar and keyboard learning
    // (FINDINGS #31); a field that publishes no hint keeps UIKit's own
    // defaults (visible entry, spell-check on).
    var isSecureTextEntry: Bool = false
    var spellCheckingType: UITextSpellCheckingType = .default
    var textContentType: UITextContentType?

    // UITextInputTraits: smart-punctuation + autocapitalization knobs (task
    // F1), driven by `applyImeContentType` the same way as the properties
    // above. `UITextInputTraits` members are `@objc optional`, so unlike a
    // stock `UITextField`/`UITextView` this custom `UITextInput` gets no
    // automatic suppression from `isSecureTextEntry` alone — each trait needs
    // its own stored property here or `applyImeContentType`'s assignment to
    // it does not compile.
    //
    // The initial values below are pre-first-classification placeholders
    // only, not a contract: nothing reads them before `syncImeFocus`'s first
    // call classifies the field (before `becomeFirstResponder()`), and
    // `applyImeContentType` (task F2) assigns all eight of the traits it
    // manages — this pair plus `isSecureTextEntry`/`textContentType`/
    // `autocorrectionType`/`spellCheckingType` above — explicitly in every
    // one of its switch arms, so whatever is stored here is overwritten
    // unconditionally the moment a content type is known. (`autocorrectionType`
    // above is itself stored as `.yes`, not `UITextAutocorrectionType.default`
    // — proof these starting values were never meant to read as "Apple's
    // documented defaults, left standing".)
    var smartQuotesType: UITextSmartQuotesType = .default
    var smartDashesType: UITextSmartDashesType = .default
    var smartInsertDeleteType: UITextSmartInsertDeleteType = .default
    var autocapitalizationType: UITextAutocapitalizationType = .sentences

    /// Whether the focused field wants the input surface *without* an
    /// on-screen keyboard — the `"suppressSoftKeyboard"` flag
    /// `frust_ime_state_json` publishes from
    /// `frust_core::event::ImeState::suppress_soft_keyboard`.
    ///
    /// A field whose text cannot be changed is still focusable and still
    /// copyable, and on iOS the first responder is exactly what carries
    /// `copy:`/`cut:`/`paste:`/`selectAll:` and the system edit menu (the
    /// `UIResponderStandardEditActions` section at the bottom of this file).
    /// So such a field must *stay* first responder; what it must not do is
    /// raise a keyboard for text it cannot accept. `inputView` below is what
    /// separates the two — this is a keyboard suppression, never a focus
    /// refusal, and `canBecomeFirstResponder` stays `true` regardless.
    ///
    /// `FrustViewController.syncImeFocus` assigns this from the parsed state
    /// **before** `becomeFirstResponder()`, for the same reason the
    /// content-type traits above are assigned there: UIKit reads the
    /// responder's input view when it stands the keyboard up, not
    /// continuously afterward.
    var suppressSoftKeyboard = false

    /// The empty stand-in `inputView` hands UIKit while suppressed. Built
    /// once and reused, so a re-query never yields a different view for the
    /// same state; zero-sized by default, which is all this needs to be.
    private lazy var suppressedInputView = UIView()

    /// The custom keyboard-replacement view UIKit stands up for this
    /// responder, or `nil` to use the system keyboard.
    ///
    /// A non-nil empty view is the documented UIKit contract for "first
    /// responder, no system keyboard" — the only way to keep the responder,
    /// and with it the edit actions and the system edit menu, while nothing
    /// rises from the bottom of the screen. Unsuppressed this returns `nil`
    /// and the system keyboard behaves exactly as it always has.
    ///
    /// UIKit re-reads this only across a first-responder transition, which is
    /// why `FrustViewController.syncImeFocus` cycles the responder when the
    /// flag *changes* — and, just as deliberately, only then.
    override var inputView: UIView? {
        return suppressSoftKeyboard ? suppressedInputView : nil
    }

    /// A custom editor view must opt in to becoming first responder for the
    /// keyboard to appear.
    override var canBecomeFirstResponder: Bool { true }

    /// Set by the view controller: performs the Rust FFI round-trip
    /// (`frust_ime_apply` with the given UTF-16 mirror state, then
    /// `frust_ime_state_json`) and returns the reconciled editing state Rust
    /// produced (already parsed + freed), or `nil` when there is no live handle.
    var imeRoundTrip: (
        (_ text: String, _ selBase: Int, _ selExt: Int, _ compBase: Int, _ compExt: Int)
            -> [String: Any]?
    )?

    // MARK: - Clipboard / system edit menu
    //
    // iOS draws the selection toolbar itself, and that is a platform
    // requirement rather than a preference: a paste escapes the "pasted from"
    // banner (iOS 14+) and the per-app paste-permission alert (iOS 16+) ONLY
    // when it is system-initiated — a tap in UIKit's own edit menu, or a
    // hardware Cmd+V through the responder chain. Both arrive here, in the
    // `UIResponderStandardEditActions` methods at the bottom of this file.
    //
    // So the Rust side declares the *native* selection-toolbar policy at
    // `frust_init`: a focused field publishes where its selection is and which
    // verbs apply, and floats no toolbar of its own. This view holds the last
    // published answer (`editActions`/`editMenuAnchor`, refreshed by
    // `FrustViewController`'s per-frame `frust_selection_toolbar_json` poll)
    // and presents UIKit's menu against it.

    /// The verbs the focused field currently allows, as of the controller's
    /// last poll. `canPerformAction(_:withSender:)` answers from this, which is
    /// what UIKit builds its menu from — and what it resolves a hardware
    /// Cmd+C/X/V/A against, with no menu anywhere in sight.
    ///
    /// A **level**, refreshed for as long as a field holds focus and reset to
    /// `.none` only when none does. It is deliberately not tied to a menu being
    /// presented: see this file's `UIResponderStandardEditActions` section.
    var editActions: FrustEditActions = .none

    /// The selection's bounding rect in this view's coordinates (logical
    /// points), or `nil` when no field is focused. The Rust side publishes it in
    /// absolute window space and this view fills the window, so it needs no
    /// conversion.
    ///
    /// The caret's own rect while the selection is collapsed, which is where a
    /// paste-only menu belongs.
    var editMenuAnchor: CGRect?

    /// Set by the view controller: bridges one edit verb into the
    /// `frust_edit_command` FFI call. `cmd` is the fixed ABI above; `text` is
    /// the pasted payload and is non-nil for `FrustEditCommand.paste` only.
    ///
    /// A closure rather than a direct FFI call for `onTouch`/`imeRoundTrip`'s
    /// reason: the native handle lives on the controller, and keeping this view
    /// free of `CFrustFFI` keeps the whole FFI surface on one side of the file
    /// boundary.
    var onEditCommand: ((UInt8, String?) -> Void)?

    /// The iOS 16+ `UIEditMenuInteraction`, stored type-erased.
    ///
    /// `UIEditMenuInteraction` is iOS 16+ and a stored property cannot be
    /// marked potentially unavailable, so the type is erased here and recovered
    /// by the `@available` computed property below — the standard workaround,
    /// not an abstraction.
    private var editMenuInteractionStorage: AnyObject?

    /// The lazily-added edit-menu interaction (iOS 16+).
    ///
    /// Added on first use rather than in an initializer so an app that never
    /// focuses a text field never installs it at all.
    ///
    /// **Presented programmatically, never by a gesture.** Unlike
    /// `UIContextMenuInteraction`, this interaction exposes no presentation
    /// gesture recognizer to configure: `presentEditMenu(with:)` is the whole
    /// public way to raise the menu. That is exactly what this framework wants
    /// — the long-press that decides a selection is detected in Rust, and the
    /// menu follows from the request that detection publishes, so nothing here
    /// competes with the raw touches this view forwards (see Touch delivery
    /// below).
    @available(iOS 16.0, *)
    private var editMenuInteraction: UIEditMenuInteraction {
        if let existing = editMenuInteractionStorage as? UIEditMenuInteraction {
            return existing
        }
        let interaction = UIEditMenuInteraction(delegate: self)
        addInteraction(interaction)
        editMenuInteractionStorage = interaction
        return interaction
    }

    /// Present the system edit menu at [editMenuAnchor], or do nothing when no
    /// anchor has been published.
    ///
    /// The controller calls this only when the framework's published request
    /// actually changed (it diffs the request's generation), so this never
    /// re-presents a standing menu once per vsync.
    func presentSystemEditMenu() {
        guard let anchor = editMenuAnchor else { return }
        if #available(iOS 16.0, *) {
            // `sourcePoint` positions the menu; the delegate's
            // `targetRectFor` below supplies the rect it must avoid covering,
            // which is the selection itself.
            let configuration = UIEditMenuConfiguration(
                identifier: nil,
                sourcePoint: CGPoint(x: anchor.midX, y: anchor.midY)
            )
            editMenuInteraction.presentEditMenu(with: configuration)
        } else {
            presentLegacyEditMenu(at: anchor)
        }
    }

    /// Put the system edit menu away — the selection collapsed, the field
    /// blurred, or the request was otherwise withdrawn.
    ///
    /// Never instantiates the interaction: with nothing installed there is by
    /// definition nothing presented to dismiss.
    func dismissSystemEditMenu() {
        if #available(iOS 16.0, *) {
            (editMenuInteractionStorage as? UIEditMenuInteraction)?.dismissMenu()
        } else {
            dismissLegacyEditMenu()
        }
    }

    /// The iOS 15 menu, which predates `UIEditMenuInteraction`.
    ///
    /// The whole declaration is marked deprecated-as-of-16 so its use of
    /// `UIMenuController` — deprecated in exactly that release — compiles
    /// without a warning, rather than suppressing the diagnostic at each call.
    /// `UIMenuController` shows nothing for a view that is not first responder,
    /// which the focused-field path already guarantees; the become is a
    /// defensive no-op in that case.
    @available(iOS, introduced: 15.0, deprecated: 16.0,
               message: "iOS 16+ presents the menu through UIEditMenuInteraction")
    private func presentLegacyEditMenu(at anchor: CGRect) {
        if !isFirstResponder {
            becomeFirstResponder()
        }
        UIMenuController.shared.showMenu(from: self, rect: anchor)
    }

    /// The iOS 15 half of [dismissSystemEditMenu] — see
    /// [presentLegacyEditMenu] for the deprecation annotation.
    @available(iOS, introduced: 15.0, deprecated: 16.0,
               message: "iOS 16+ dismisses the menu through UIEditMenuInteraction")
    private func dismissLegacyEditMenu() {
        UIMenuController.shared.hideMenu()
    }

    // Touch delivery. We own the gesture logic in Rust, so we handle
    // the raw UIResponder touch callbacks directly rather than attaching
    // UIGestureRecognizers — including the one `UIEditMenuInteraction` would
    // have installed for itself (disabled above). The controller sets
    // `onTouch` to bridge into the `frust_dispatch_touch` FFI call; `phase` is
    // the fixed ABI shared with the Rust side (0 = began, 1 = moved, 2 = ended,
    // 3 = cancelled); `pointer_id` is the per-sequence slot `forward(_:phase:)`
    // assigns below (0 for a gesture's first-down touch, counting up for each
    // additional live contact — the convention the Android shell shares).
    var onTouch: ((UInt32, UInt32, CGPoint) -> Void)?

    /// Per-gesture touch identity → slot map. `UITouch` isn't `Hashable`, but
    /// UIKit reuses the same instance for a contact's whole
    /// began/moved/…/ended lifetime, so `ObjectIdentifier(touch)` is a stable
    /// key for exactly that long. Cleared once no touch remains live, so the
    /// next gesture's first-down touch restarts at slot 0 — the identity a
    /// bare single-touch gesture has always reported.
    private var touchSlots: [ObjectIdentifier: UInt32] = [:]
    /// Tracks which slots are free in the current gesture. Index = slot number;
    /// value = whether free. When all contacts are up, this is cleared and slot
    /// assignment resets to 0 naturally (see [slot(for:)]).
    private var freeSlots: [Bool] = []

    /// The stable slot for `touch`: its existing one if this isn't the first
    /// callback to see it, otherwise the lowest currently-free slot (first-down
    /// touch of a gesture is always 0; see [touchSlots]).
    private func slot(for touch: UITouch) -> UInt32 {
        let id = ObjectIdentifier(touch)
        if let existing = touchSlots[id] {
            return existing
        }
        let assigned: UInt32
        if let free = freeSlots.firstIndex(of: true) {
            freeSlots[free] = false
            assigned = UInt32(free)
        } else {
            assigned = UInt32(freeSlots.count)
            freeSlots.append(false)
        }
        touchSlots[id] = assigned
        return assigned
    }

    /// Mode B input forwarding: set by the
    /// controller to `FrustViewHost.interactiveSlotContains`. When a touch
    /// lands inside an interactive hosted slot's rect (outside its
    /// z-shields), this view's `hitTest` returns nil so UIKit falls through
    /// to the native sibling BELOW and routes the whole gesture there —
    /// touch-DOWN decides ownership, natively, with real UIControl
    /// semantics. Everywhere else the surface behaves exactly as before.
    var interactiveSlotHitTest: ((CGPoint) -> Bool)?

    override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        if let probe = interactiveSlotHitTest, probe(point) {
            return nil
        }
        return super.hitTest(point, with: event)
    }

    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        forward(touches, phase: 0)
    }

    override func touchesMoved(_ touches: Set<UITouch>, with event: UIEvent?) {
        forward(touches, phase: 1)
    }

    override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {
        forward(touches, phase: 2)
    }

    override func touchesCancelled(_ touches: Set<UITouch>, with event: UIEvent?) {
        forward(touches, phase: 3)
    }

    /// Forward every touch in `touches` (logical points, in this view's
    /// space) to the Rust side, each tagged with its stable per-sequence
    /// slot (see [slot(for:)]).
    ///
    /// A `touchesEnded`/`touchesCancelled` callback additionally retires the
    /// touch's slot by marking it free — it can be reused by a later touch.
    /// Once no touch is left live, resets [freeSlots] so the next gesture's
    /// first contact is slot 0 again.
    private func forward(_ touches: Set<UITouch>, phase: UInt32) {
        for touch in touches {
            let touchSlot = slot(for: touch)
            onTouch?(phase, touchSlot, touch.location(in: self))
            if phase == 2 || phase == 3 {
                let id = ObjectIdentifier(touch)
                touchSlots.removeValue(forKey: id)
                // Mark the slot as free
                if touchSlot < UInt32(freeSlots.count) {
                    freeSlots[Int(touchSlot)] = true
                }
            }
        }
        if touchSlots.isEmpty {
            freeSlots.removeAll()
        }
    }
}

// MARK: - UIResponderStandardEditActions

// The clipboard verbs, implemented on the responder rather than in the
// `UITextInput` conformance — they are not `UITextInput` members. Implementing
// them is what puts Copy/Cut/Paste/Select All in UIKit's own edit menu (the
// protocol's methods are optional, and UIKit hides the ones a responder does
// not implement), and it is half of what makes a hardware keyboard's
// Cmd+C/X/V/A work: both routes resolve through this same responder chain.
//
// The other half is `editActions` being a LEVEL. UIKit asks
// `canPerformAction(_:withSender:)` whenever it likes — for a hardware chord
// there is no menu, no gesture and no presentation first — so the Rust side
// publishes the focused field's verbs on every frame it holds focus, bar or no
// bar, and the controller pushes them here on every poll. Answering out of a
// value that only arrived while a menu was up would leave every hardware chord
// refused: `canPerformAction` would say `false` and UIKit would route the key
// elsewhere. Cmd+V is the one that costs the most — it is one of the two paste
// routes iOS exempts from its per-app paste-permission alert.
//
// None of them touches the mirror in `FrustTextInput.swift`. Each hands the
// verb to the focused Rust widget, which owns the selection and the text; the
// resulting change comes back through the per-frame IME reconcile the
// controller already runs, exactly like a text change no UIKit callback
// originated.
extension FrustView {
    /// Answer UIKit's "may I offer this?" from the verbs the focused field
    /// published, so the system menu shows what the framework would have shown.
    ///
    /// Everything outside the four verbs is refused — the menu is the
    /// framework's clipboard vocabulary and nothing else, and a responder that
    /// answered `true` for an action it does not implement would show a dead
    /// item.
    ///
    /// Paste additionally requires the pasteboard to actually hold a string.
    /// `hasStrings` is *metadata*: reading it discloses no content and raises
    /// no notice or permission alert (unlike reading `string`), so this is a
    /// free way to avoid offering a Paste that would do nothing — the same
    /// thing UIKit does for its own text fields.
    override func canPerformAction(_ action: Selector, withSender sender: Any?) -> Bool {
        switch action {
        case #selector(UIResponderStandardEditActions.copy(_:)):
            return editActions.copy
        case #selector(UIResponderStandardEditActions.cut(_:)):
            return editActions.cut
        case #selector(UIResponderStandardEditActions.paste(_:)):
            return editActions.paste && UIPasteboard.general.hasStrings
        case #selector(UIResponderStandardEditActions.selectAll(_:)):
            return editActions.selectAll
        default:
            return false
        }
    }

    override func copy(_ sender: Any?) {
        onEditCommand?(FrustEditCommand.copy, nil)
    }

    override func cut(_ sender: Any?) {
        onEditCommand?(FrustEditCommand.cut, nil)
    }

    /// Read the pasteboard and hand the text to the focused widget.
    ///
    /// **This read is the exempt one.** `UIPasteboard.general.string` raises
    /// iOS's paste notice (14+) and its per-app permission alert (16+) unless
    /// the read happens inside a system-initiated action — which is precisely
    /// what this method is, whether UIKit called it from its own edit menu or
    /// from a hardware Cmd+V. That exemption is the reason the whole native
    /// menu route exists.
    ///
    /// An empty pasteboard dispatches nothing rather than an empty paste (which
    /// would replace a selection with nothing — a delete the user did not ask
    /// for). `canPerformAction` above normally keeps Paste out of the menu
    /// entirely in that case; this guard covers the race where the pasteboard
    /// was cleared between the menu being built and the item being tapped.
    override func paste(_ sender: Any?) {
        guard let text = UIPasteboard.general.string else { return }
        onEditCommand?(FrustEditCommand.paste, text)
    }

    override func selectAll(_ sender: Any?) {
        onEditCommand?(FrustEditCommand.selectAll, nil)
    }
}

// MARK: - UIEditMenuInteractionDelegate

@available(iOS 16.0, *)
extension FrustView: UIEditMenuInteractionDelegate {
    /// The rect the menu must not cover — the selection itself, in this view's
    /// coordinates.
    ///
    /// Returning the selection's bounds (rather than the configuration's bare
    /// source point) is what makes UIKit flip the menu above or below the
    /// selection instead of placing it on top of the text the user just
    /// highlighted.
    ///
    /// `CGRect.null` is this method's documented "use the default" answer — an
    /// empty rect centred on `configuration.sourcePoint` — which is the right
    /// fallback for the should-not-happen case of a menu presented with no
    /// anchor published.
    func editMenuInteraction(
        _ interaction: UIEditMenuInteraction,
        targetRectFor configuration: UIEditMenuConfiguration
    ) -> CGRect {
        editMenuAnchor ?? .null
    }
}
