import UIKit
import QuartzCore
import CFrustFFI

// Generated by `frust create`. Hosts the Frust
// render surface and drives it from a `CADisplayLink`, bridging UIKit's
// view/scene lifecycle (touch + text input) to the `frust_*` FFI calls.
//
// Contract enforced here (mirrored on the Rust side, belt-and-suspenders):
//   - `frust_init` is called exactly once, on the first valid layout;
//     every later size change goes through `frust_resize`.
//   - The display link (and the native renderer via `frust_pause`) is
//     paused when the app resigns active — submitting Metal work from a
//     backgrounded app can get the process killed.
//   - `frust_destroy` reclaims the native handle before the view is gone.
open class FrustViewController: UIViewController {
    /// Opt into a translucent (non-opaque) render surface so native sibling
    /// views hosted BELOW the Frust surface (Mode B — see `FrustViewHost`)
    /// show through it. Override with `true` in an
    /// app's `FrustViewController` subclass (the iOS mirror of Android's
    /// `FrustActivity.translucentSurface`) to enable translucency; `false` by
    /// default so a fresh scaffold's surface is fully opaque and unchanged.
    /// Read once, before `frust_init` (via `frust_set_surface_mode`), and never
    /// mutated — the surface's alpha mode is fixed for the process lifetime, so
    /// an override must be a constant, not per-frame state.
    ///
    /// **This value is the whole Mode B switch: it must drive
    /// `CAMetalLayer.isOpaque`, the `FrustViewHost` subview ordering, AND the
    /// `frust_set_surface_mode` declaration below, together.** Flipping only
    /// some of them is a defect — the Rust side trusts
    /// `frust_set_surface_mode(1)` as proof the layer is *already*
    /// translucent; calling it without `isOpaque = false` already set clears
    /// to a transparent base and punches an otherwise-opaque layer, painting
    /// black rectangles instead of the intended hole.
    /// This is also why there is no app-Rust equivalent call — only this
    /// host-side seam may declare translucency.
    open var translucentSurface: Bool { false }

    /// Opt into presenting the Frust surface inside the same `CATransaction`
    /// that commits hosted platform-view geometry, so a native sibling view
    /// and the Frust content under/over it move together while scrolling.
    /// Override with `true` in an app's `FrustViewController` subclass when it
    /// hosts `platform_view` slots inside a scroller — the case the desync is
    /// visible in. `false` by default: an app with no hosted views gains
    /// nothing and would pay a `waitUntilScheduled` on the main thread every
    /// frame. Read once, before the first frame, and never mutated.
    ///
    /// **iOS's correction is the mirror of Android's, and this is the only
    /// knob for it.** iOS's native sibling *lags* Frust's content, so the fix
    /// is to hold frust's *present* back to meet the geometry — not to delay
    /// the view (Android's frame-id gate does that, for the opposite sign of
    /// error). Do not try to share one "platform-view sync" switch across the
    /// two platforms.
    ///
    /// **This value must drive `CAMetalLayer.presentsWithTransaction` AND the
    /// `frust_set_present_sync` declaration together**, in the one branch
    /// below — the same all-or-nothing rule `translucentSurface` carries.
    /// Setting only the layer flag stops presentation dead (the render thread
    /// hands the drawable over on a thread that commits no transaction, so it
    /// never reaches the compositor — measured); declaring only the Rust
    /// half just defers each present by a tick for no benefit. The
    /// render-thread split stays ON either way — this is *not* a
    /// `FRUST_NO_RENDER_THREAD` switch.
    open var synchronizesPresentWithPlatformViews: Bool { false }

    private var forgeView: FrustView { view as! FrustView }
    private var displayLink: CADisplayLink?
    private var handle: UnsafeMutableRawPointer?
    /// Hosts native UIKit sibling views driven by the platform-view command
    /// channel. Constructed once `frust_init` has a
    /// handle; polled each `CADisplayLink` tick after `frust_render_frame`.
    private var platformViewHost: FrustViewHost?
    private var lastDrawableSize: CGSize = .zero
    // `frust_init` failure is session-permanent by design: the shell has
    // no transient failure mode (the one observed cause, a simulator GPU
    // missing a required Metal feature, cannot change mid-process). Once
    // `frust_init` returns nil, latch here so every later UIKit layout
    // pass (rotation, keyboard, autolayout churn, ...) is a no-op instead of
    // re-running a doomed synchronous `pollster::block_on` adapter/device
    // request and re-logging the failure. If a transient failure mode is
    // ever introduced on the Rust side, this is the place to revisit.
    private var initFailed = false

    /// Whether [synchronizesPresentWithPlatformViews] was armed — latched in
    /// `viewDidLoad`, in the same branch that declared it to Rust and set the
    /// layer flag, so the per-tick `renderFrame` path reads a stored `Bool`
    /// instead of re-dispatching an overridable property every frame (and so
    /// the "read once, never mutated" contract is structural rather than a
    /// comment).
    private var presentSyncArmed = false

    /// A deep link delivered (by `SceneDelegate`) before `frust_init` has
    /// returned a handle — cold-start links routinely arrive this early,
    /// since `connectionOptions.urlContexts` is available in
    /// `scene(_:willConnectTo:options:)`, well before the first
    /// `viewDidLayoutSubviews` triggers `updateSurface()`/`frust_init`.
    /// Held here and flushed the moment `handle` becomes non-nil (the same
    /// queue-until-handle-ready contract, mirroring Android's
    /// `FrustSurfaceView.pendingDeepLink`).
    private var pendingDeepLink: String?

    /// The wire `"contentType"` value last pushed into `forgeView`'s
    /// `UITextInputTraits` by `applyImeContentType`, or `nil` when nothing has
    /// been applied since the field last went inactive. Tracked so
    /// `syncImeFocus` can detect a **steady-active** field whose
    /// classification changed (e.g. `"normal"` → `"password"` without an
    /// intervening blur, or focus moving directly from one field to a
    /// differently-classified one while `forgeView` — the single shared
    /// responder for the whole tree — never actually leaves first-responder
    /// status) and re-apply the traits **plus re-seed the mirror**, mirroring Android's
    /// `FrustSurfaceView.pollImeAfterDispatch`/`lastKnownState.contentType`
    /// comparison. Without this, the *previous* field's traits — in
    /// particular `isSecureTextEntry` — stay live for the rest of the
    /// session (FINDINGS #31, reintroduced on this exact edge).
    private var lastAppliedContentType: String?

    /// The keyboard's current occlusion of this view's bottom edge, in
    /// logical points (`FlutterViewController.mm:1593-1622` model). Computed as
    /// the intersection of the keyboard's end frame with `view.bounds`, so
    /// an undocked/split or off-screen keyboard doesn't over-report. Kept
    /// separate from `view.safeAreaInsets` (which UIKit does not include the
    /// keyboard in) so [pushInsets] can recombine both on every push.
    private var keyboardViewInsetBottom: CGFloat = 0

    /// The last system-UI slot generation observed by [pollSystemUiState]
    /// (the `frust::set_system_ui_mode` override). Starts at `0`, matching the
    /// slot's initial (never-requested) generation, so an app that never
    /// calls the API never flips [statusBarHidden]/[homeIndicatorAutoHidden]
    /// away from their platform-default `false`.
    private var lastSystemUiGeneration: UInt64 = 0

    /// Decoded `frust::set_system_ui_mode` state. Both
    /// default `false` — the platform's own default (status bar visible,
    /// home indicator not auto-hidden) — until [pollSystemUiState] observes
    /// a real generation. Read back by [prefersStatusBarHidden] /
    /// [prefersHomeIndicatorAutoHidden] below.
    private var statusBarHidden = false
    private var homeIndicatorAutoHidden = false

    /// UIKit's designated initializer, re-declared `public` so an app module can
    /// construct (or subclass) this controller across the package boundary — a
    /// type's members are `internal` by default and would otherwise be invisible
    /// outside `FrustEmbedding`. Behavior is UIKit's: this is a plain forward.
    public override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }

    /// Required companion of the initializer above (declaring any initializer
    /// stops Swift from inheriting the superclass's). Forwards to UIKit so a
    /// storyboard/nib-instantiated controller keeps working exactly as before.
    public required init?(coder: NSCoder) {
        super.init(coder: coder)
    }

    /// The UIKit lifecycle overrides below (through `traitCollectionDidChange`)
    /// are `public override`, not bare `override`. **The `public` is load-bearing,
    /// not stylistic:** an override must be at least as accessible as the member
    /// it overrides, and UIKit declares all of these `open`. Left at Swift's
    /// default `internal` — which is what they were while this file was app-owned
    /// — the package does not compile, with one `error: overriding instance method
    /// must be as accessible as the declaration it overrides` per member. That
    /// failure only appears when the package is built on its own, so do not
    /// "tidy" the keyword away because an app target still happens to build.
    ///
    /// **`public` rather than `open` is deliberate: these are NOT extension
    /// points.** `open` would let an app subclass override them, and each one
    /// carries a framework invariant that an override would silently break —
    /// `loadView` installs the `FrustView` everything else assumes; the four
    /// `view*` hooks and `traitCollectionDidChange` forward into Rust
    /// (`frust_init` / `updateSurface` / `pushInsets` / `frust_set_appearance`),
    /// so a missing `super` breaks insets, resize or theming with no diagnostic;
    /// and `prefersStatusBarHidden` / `prefersHomeIndicatorAutoHidden` are
    /// computed from `set_system_ui_mode` state, so an override fights the
    /// framework rather than extending it.
    ///
    /// The intended override surface is the curated one declared `open`:
    /// `translucentSurface` here, `makeRootViewController()` on
    /// `FrustSceneDelegate`, and the `application`/`scene` hooks on the two
    /// delegates. Widening a member from `public` to `open` later is source
    /// compatible; narrowing `open` back to `public` is a breaking change for
    /// every app that subclassed. So: add a specific `open` hook when a real app
    /// needs one — don't open the UIKit lifecycle wholesale.
    public override func loadView() {
        view = FrustView()
    }

    public override func viewDidLoad() {
        super.viewDidLoad()
        // Perf instrumentation: marks
        // viewDidLoad's entry on the same console stream the Rust side's
        // `frust-perf startup ...`/`frust-perf frame ...` lines land
        // on (captured together via `simctl launch --console-pty`/Xcode),
        // so the app-launch-to-view-load gap is measurable from one stream
        // — mirrors the Android shell's `MainActivity.onCreate` log line.
        // Unconditional (not gated on FRUST_TRACE): this is
        // host-app Swift code the Rust `perf::enabled()` switch doesn't
        // reach, and a single log line at launch has no measurable cost.
        NSLog("frust-perf vc-load")
        let scale = UIScreen.main.scale
        view.contentScaleFactor = scale
        forgeView.metalLayer.contentsScale = scale

        // Translucent surface opt-in: latch the process-global surface mode
        // BEFORE the first `frust_init`
        // (`updateSurface` runs later, from `viewDidLayoutSubviews`) and make
        // both the view and its CAMetalLayer non-opaque so native sibling
        // views hosted behind the surface (Mode B) composite through. No-op
        // in the default opaque scaffold (`translucentSurface == false`).
        if translucentSurface {
            frust_set_surface_mode(1)
            forgeView.isOpaque = false
            forgeView.metalLayer.isOpaque = false
        }

        // Present-sync opt-in: latch the process-global declaration BEFORE
        // the first `frust_init` (like the surface mode above) and set the layer flag that
        // makes Metal defer the drawable to a CATransaction — together, in this
        // one branch. From here the render thread stops presenting and parks
        // each finished frame for `renderFrame` to present below. No-op in the
        // default scaffold (`synchronizesPresentWithPlatformViews == false`).
        if synchronizesPresentWithPlatformViews {
            frust_set_present_sync(1)
            forgeView.metalLayer.presentsWithTransaction = true
            presentSyncArmed = true
        }

        // Bridge the view's raw touch callbacks into the native tree.
        // `location` is already logical points, so it is passed through without
        // any scale division (contrast Android's physical-pixel touch path).
        forgeView.onTouch = { [weak self] phase, location in
            guard let self, let handle = self.handle else { return }
            frust_dispatch_touch(handle, phase, Float(location.x), Float(location.y))
            // A touch may have focused/blurred an editable widget; reconcile the
            // keyboard/first-responder state with what the tree now reports.
            self.syncImeFocus()
        }

        // Bridge the view's UITextInput mirror into the native IME: push
        // the whole editing value, then read back the reconciled state as JSON.
        forgeView.imeRoundTrip = { [weak self] text, selBase, selExt, compBase, compExt in
            guard let self, let handle = self.handle else { return nil }
            text.withCString { cstr in
                frust_ime_apply(
                    handle, cstr, Int32(selBase), Int32(selExt), Int32(compBase), Int32(compExt))
            }
            return self.fetchImeState()
        }

        NotificationCenter.default.addObserver(
            self,
            selector: #selector(appWillResignActive),
            name: UIApplication.willResignActiveNotification,
            object: nil
        )
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(appDidBecomeActive),
            name: UIApplication.didBecomeActiveNotification,
            object: nil
        )

        // Insets: the keyboard's occlusion isn't part of `UIView.safeAreaInsets`, so
        // it's tracked separately via these notifications and recombined
        // with the current safe area on every `pushInsets()` call.
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(keyboardWillChangeFrame(_:)),
            name: UIResponder.keyboardWillChangeFrameNotification,
            object: nil
        )
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(keyboardWillHide(_:)),
            name: UIResponder.keyboardWillHideNotification,
            object: nil
        )

        // Reduce motion: `UIAccessibility.isReduceMotionEnabled` is NOT a
        // `UITraitCollection` trait, so `traitCollectionDidChange` never fires
        // for it — this notification is the only live-change signal. The
        // initial value is seeded in `updateSurface`, right after `frust_init`
        // returns a handle (this observer is registered well before that, but
        // `pushReduceMotion` needs a handle).
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(reduceMotionDidChange),
            name: UIAccessibility.reduceMotionStatusDidChangeNotification,
            object: nil
        )
    }

    public override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        updateSurface()
    }

    /// SafeArea change (rotation, notch/Dynamic Island layout change, a
    /// sibling view controller's chrome). Pushed unconditionally;
    /// `IosAppHandle::set_insets` (Rust side) no-op-guards an unchanged value.
    public override func viewSafeAreaInsetsDidChange() {
        super.viewSafeAreaInsetsDidChange()
        pushInsets()
    }

    // MARK: - Insets

    @objc private func keyboardWillChangeFrame(_ notification: Notification) {
        updateKeyboardInset(from: notification)
    }

    @objc private func keyboardWillHide(_ notification: Notification) {
        keyboardViewInsetBottom = 0
        pushInsets()
    }

    /// Computes the keyboard's occlusion of this view as the intersection of
    /// its end frame (delivered in screen/window coordinates) with
    /// `view.bounds`, converted into the view's coordinate space first
    /// (`FlutterViewController.mm:1593-1622`'s model — no animation
    /// interpolation in this v1 port).
    private func updateKeyboardInset(from notification: Notification) {
        guard
            let endFrameValue = notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey]
                as? NSValue
        else { return }
        let localFrame = view.convert(endFrameValue.cgRectValue, from: nil)
        let intersection = localFrame.intersection(view.bounds)
        keyboardViewInsetBottom = intersection.isNull ? 0 : intersection.height
        pushInsets()
    }

    /// Pushes the current `view_padding` (from `UIView.safeAreaInsets`) and
    /// `view_insets` (the keyboard occlusion tracked above) to
    /// `frust_set_insets`. Values are logical points — no scale
    /// multiplication (`frust_set_insets`'s contract mirrors
    /// `frust_dispatch_touch`'s no-scale asymmetry). A missing handle is
    /// a no-op; the next call after `frust_init` succeeds (see
    /// `updateSurface`) re-pushes the current state.
    private func pushInsets() {
        guard let handle else { return }
        let insets = view.safeAreaInsets
        frust_set_insets(
            handle,
            Float(insets.left), Float(insets.top), Float(insets.right), Float(insets.bottom),
            0, 0, 0, Float(keyboardViewInsetBottom)
        )
    }

    public override func viewWillTransition(
        to size: CGSize,
        with coordinator: UIViewControllerTransitionCoordinator
    ) {
        super.viewWillTransition(to: size, with: coordinator)
        coordinator.animate(alongsideTransition: nil) { [weak self] _ in
            self?.updateSurface()
        }
    }

    /// Sizes the drawable to the view's pixel bounds and either creates the
    /// native renderer (first valid layout) or resizes it (thereafter).
    private func updateSurface() {
        guard !initFailed else { return }

        let scale = view.contentScaleFactor
        let bounds = view.bounds.size
        let pixelSize = CGSize(
            width: bounds.width * scale,
            height: bounds.height * scale
        )
        guard pixelSize.width > 0, pixelSize.height > 0 else { return }

        let layer = forgeView.metalLayer
        layer.contentsScale = scale
        layer.drawableSize = pixelSize

        let width = UInt32(pixelSize.width)
        let height = UInt32(pixelSize.height)

        if handle == nil {
            handle = frust_init(
                Unmanaged.passUnretained(layer).toOpaque(),
                width,
                height,
                Float(scale)
            )
            guard handle != nil else {
                initFailed = true
                displayLink?.invalidate()
                displayLink = nil
                NSLog("Frust: GPU init failed — rendering disabled for this session")
                return
            }
            // Attach the AccessKit adapter to this view. The
            // adapter dynamically subclasses the FrustView to implement UIKit's
            // accessibility methods, so it needs the *view* pointer (not the
            // CAMetalLayer frust_init got). Do it here — once, before the view
            // is shown/focused — which is the window AccessKit's SubclassingAdapter
            // requires. Passed unretained: Rust holds the adapter only for the
            // handle's lifetime and restores the view's class on frust_destroy,
            // before this controller (and its view) is released.
            frust_init_accessibility(handle, Unmanaged.passUnretained(forgeView).toOpaque())
            // Seed the theme's brightness from the platform's current
            // appearance before the first frame; live changes
            // arrive later via `traitCollectionDidChange`.
            frust_set_appearance(handle, traitCollection.userInterfaceStyle == .dark ? 1 : 0)
            // Seed the reduce-motion accessibility preference beside the
            // appearance; live changes arrive via
            // `reduceMotionStatusDidChangeNotification` (see `viewDidLoad`),
            // never via `traitCollectionDidChange`.
            pushReduceMotion()
            // Push the initial insets — the first
            // `viewSafeAreaInsetsDidChange` may have already fired before
            // `handle` existed, so `pushInsets()`'s guard silently dropped
            // it; push once explicitly now that a handle is live.
            pushInsets()
            // Stand up the platform-view host now that a handle exists:
            // it hosts native sibling views and is
            // polled from `renderFrame` after each `frust_render_frame`.
            platformViewHost = FrustViewHost(
                containerView: forgeView, translucent: translucentSurface)
            // Mode B input forwarding: let the
            // surface's hitTest consult the host's interactive-slot rects.
            forgeView.interactiveSlotHitTest = { [weak self] point in
                self?.platformViewHost?.interactiveSlotContains(point) ?? false
            }
            startDisplayLink()
            // Flush a deep link that arrived before this handle existed
            // (see `pendingDeepLink`'s doc comment) — a cold-start link
            // must not be silently dropped just because it raced ahead of
            // `frust_init`.
            if let pending = pendingDeepLink {
                pendingDeepLink = nil
                deliverDeepLink(pending)
            }
        } else if pixelSize != lastDrawableSize {
            frust_resize(handle, width, height, Float(scale))
        }
        lastDrawableSize = pixelSize
    }

    // MARK: - Deep links

    /// Deliver a platform deep link — called by `SceneDelegate` for both the
    /// cold-start link (`connectionOptions.urlContexts`, in
    /// `scene(_:willConnectTo:options:)`) and a running-app link
    /// (`scene(_:openURLContexts:)`) uniformly. Queues until `frust_init`
    /// has returned a handle if the link arrives first (see
    /// `pendingDeepLink`).
    public func handleDeepLink(_ url: URL) {
        deliverDeepLink(url.absoluteString)
    }

    private func deliverDeepLink(_ url: String) {
        guard let handle else {
            pendingDeepLink = url
            return
        }
        url.withCString { cstr in
            frust_on_deep_link(handle, cstr)
        }
    }

    // MARK: - Text input

    /// Read the focused field's IME surface from Rust as a parsed dictionary,
    /// freeing the returned C string (the Rust side transfers ownership).
    private func fetchImeState() -> [String: Any]? {
        guard let handle, let raw = frust_ime_state_json(handle) else { return nil }
        defer { frust_string_free(raw) }
        let data = Data(bytes: raw, count: strlen(raw))
        return (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
    }

    /// Reconcile keyboard/first-responder state **and the platform text
    /// mirror** with the tree: a newly-focused field seeds the mirror and shows
    /// the keyboard; a blurred field resigns; a **steady-active** field (still
    /// first responder, no focus edge) whose `"contentType"` classification
    /// changed re-seeds the mirror, re-applies the traits and cycles the
    /// responder so the keyboard actually picks them up (see
    /// `applyImeContentType`'s doc for why a cycle, not just a trait
    /// assignment, is required); and any other steady-active tick reconciles
    /// the mirror against the published state.
    ///
    /// The two steady-active branches are the fix for the case a
    /// per-focus-edge-only application misses entirely: `forgeView` is the
    /// *one* shared responder for the whole tree, so focus moving from field A
    /// to field B — with the same *or* a different content type — never trips
    /// `!forgeView.isFirstResponder`, because the responder never actually
    /// stops being first responder in between. Two distinct defects follow
    /// from that, and both are handled here:
    ///
    /// 1. **Traits.** A `"normal"` field's traits (autocorrect on, no secure
    ///    entry) would stay live while the user types into what Rust reports as
    ///    a `"password"` field — FINDINGS #31 reintroduced on this exact edge.
    /// 2. **Text.** `forgeView.mirror` would still hold **field A's text**, so
    ///    the first keystroke in B round-trips `A_text + char` through
    ///    `frust_ime_apply`, which applies to whatever widget is focused now
    ///    with no widget-identity validation — silently replacing B's content
    ///    with A's. Re-seeding/reconciling the mirror on *both* steady-active
    ///    branches is what closes that; a trait-only fix does not.
    ///
    /// The re-seed on the content-type branch deliberately happens **before**
    /// `resignFirstResponder()`: a resign can commit an open composition via
    /// `unmarkText()`, which itself calls `syncToRust()` — pushing whatever the
    /// mirror holds into the newly-focused widget. Seeding first means that
    /// push (if it happens at all) carries B's own text, and in practice the
    /// seed also clears `markedRange` to `NSNotFound` whenever Rust reports no
    /// composing region, so `unmarkText()`'s own guard returns early. Belt and
    /// braces, because the ordering is the difference between a no-op echo and
    /// overwriting a field with another field's contents.
    ///
    /// Mirrors Android's `FrustSurfaceView.pollImeAfterDispatch` branch for
    /// branch: show/hide edge → `requestFocus`/`restartInput`/`showSoftInput`;
    /// content-type change → `restartInput` (which re-invokes
    /// `onCreateInputConnection`, recomputing `EditorInfo` *and* re-seeding the
    /// connection's mirror from `lastKnownState` — the pairing this function's
    /// `seedMirror` + `applyImeContentType` reproduces); otherwise steady
    /// active → `reconcileTo`, the divergence-guarded mirror reconcile.
    ///
    /// **Call sites** (also mirroring Android's): the `onTouch` bridge, and
    /// every `renderFrame` tick — see the call in `renderFrame` for the
    /// per-frame cost and why the frame tick, not `imeRoundTrip`, is the
    /// second site.
    ///
    /// Being per-frame makes the first branch a self-healing retry: if
    /// `becomeFirstResponder()` is refused (the view is not yet in a window,
    /// say), the next tick tries again. That is safe because both steps it
    /// repeats — `seedMirror` and `applyImeContentType` — are idempotent
    /// writes of the same published state, and the retry stops the moment the
    /// responder is accepted. It also means a purely programmatic focus (no
    /// touch anywhere) now raises the keyboard, which the touch-only call site
    /// never did.
    private func syncImeFocus() {
        guard let state = fetchImeState() else { return }
        let active = (state["active"] as? Bool) ?? false
        let contentType = state["contentType"] as? String
        if active {
            if !forgeView.isFirstResponder {
                forgeView.seedMirror(from: state)
                // Content-type traits (secure entry, autocorrect,
                // spell-check) must land BEFORE `becomeFirstResponder()` —
                // UIKit reads them when it stands up the keyboard for this
                // responder, not continuously afterward, so setting them
                // after would leave the wrong keyboard configuration live for
                // this focus session.
                applyImeContentType(contentType)
                lastAppliedContentType = contentType
                forgeView.becomeFirstResponder()
            } else if contentType != lastAppliedContentType {
                // Same responder, no focus edge, but the classification
                // changed underneath it (obscure-toggle on one field, or
                // focus moved straight to a differently-classified field —
                // see this function's doc). Re-seed the mirror first (the
                // ordering rule above), then re-apply the traits;
                // `applyImeContentType` alone is not enough here — see its doc
                // for the resign/become cycle this requires. Seed rather than
                // reconcile: this is the analogue of Android's `restartInput`
                // → `onCreateInputConnection` → `seed(state)`, an
                // unconditional re-seed paired with a fresh keyboard
                // configuration.
                forgeView.seedMirror(from: state)
                applyImeContentType(contentType)
                lastAppliedContentType = contentType
                forgeView.resignFirstResponder()
                forgeView.becomeFirstResponder()
            } else {
                // Steady active, same classification: reconcile the mirror to
                // the focused field's published state — a field switch between
                // two identically-classified fields, a caret moved by a tap, or
                // a whole-field text change from a submit-clear, none of which
                // any `UITextInput` callback originated. Divergence-guarded and
                // composition-safe (see `reconcileMirror(to:)`), so the common
                // case — mirror already agrees with Rust — costs one string and
                // two range compares and notifies nothing.
                forgeView.reconcileMirror(to: state)
            }
        } else if forgeView.isFirstResponder {
            forgeView.resignFirstResponder()
            lastAppliedContentType = nil
        }
    }

    /// Map the wire `"contentType"` string (`"normal"` / `"password"` /
    /// `"noSuggestions"` — encoded on the Rust side by
    /// `frust_shell_ios::ffi_glue::content_type_wire` from
    /// `frust_core::event::ImeContentType`) onto the UIKit text-input traits
    /// that actually suppress the QuickType suggestion bar and keyboard
    /// learning (FINDINGS #31).
    ///
    /// `isSecureTextEntry` is the load-bearing flag for `"password"`: it is
    /// what stops UIKit from echoing typed characters into the suggestion
    /// strip and from persisting them into the personalized-learning
    /// dictionary — the exact leak this finding closes. `textContentType =
    /// .password` layers the system's password-manager/autofill heuristics
    /// on top. `"noSuggestions"` is the non-secret sibling: entry stays
    /// visible (no `isSecureTextEntry`), but autocorrect/spell-check/learning
    /// are still switched off.
    ///
    /// `ImeContentType` has exactly three variants today (no dedicated
    /// "new password" or "one-time code" hint yet), so this does not reach
    /// for `.newPassword`/`.oneTimeCode` — `.oneTimeCode` in particular
    /// actively invites a QuickType suggestion (SMS-code autofill), which
    /// would fight `"noSuggestions"`'s whole purpose. Revisit this mapping if
    /// `ImeContentType` grows a variant those fit.
    ///
    /// Any wire value this switch doesn't recognize — including `nil` (no
    /// `"contentType"` key, which should not happen once the core always
    /// populates the field, but a shell must not trust wire input) — falls
    /// through to the `"password"` arm: the same fail-closed rule
    /// `content_type_wire`'s doc comment states on the Rust side, applied
    /// here at the boundary that actually renders it. A field that state-sync
    /// forgot to classify becomes stricter than intended, never a secret
    /// field that got de-classified into a plaintext keyboard.
    ///
    /// **Assigning these properties alone is not sufficient on a `UITextInput`
    /// that is already first responder.** `syncImeFocus` calls this function
    /// from two sites: once before the *first* `becomeFirstResponder()` of a
    /// focus session (traits land before the keyboard stands up — the normal
    /// case, and the only one where a bare assignment works), and once more
    /// on a steady-active field whose classification changed mid-session. For
    /// that second call, `syncImeFocus` wraps it in a
    /// `resignFirstResponder()` / `becomeFirstResponder()` cycle — required
    /// because `isSecureTextEntry` is documented by Apple
    /// (`UITextInputTraits.isSecureTextEntry`) to take effect only when set
    /// *before* the object becomes first responder; there is no supported
    /// "reload traits on a live responder" call (`reloadInputViews()` only
    /// re-queries `inputView`/`inputAccessoryView`, not
    /// `UITextInputTraits`). The cycle is the conservative, Apple-sanctioned
    /// choice over a trait assignment that silently fails to take effect on
    /// exactly the security-relevant path this whole mechanism exists for.
    ///
    /// This does mean a mid-session classification change visibly cycles the
    /// keyboard: `forgeView`'s own state (`mirror`, `selectedRange`,
    /// `markedRange`) lives on the view instance and is untouched by the
    /// resign/become cycle, so no text or caret position is lost, but a
    /// resign/become pair is a real (if typically very brief, same-run-loop)
    /// first-responder transition and cannot be guaranteed flicker-free on
    /// every iOS version — this file is compile- and device-unverified (see
    /// this task's completion notes), so the actual on-device visual is
    /// unconfirmed either way. That cost was judged acceptable against the
    /// alternative: a stale `isSecureTextEntry`/`textContentType` silently
    /// leaking a secret field's keystrokes into QuickType and keyboard
    /// learning is a worse failure mode than a visible keyboard blink.
    private func applyImeContentType(_ wire: String?) {
        switch wire {
        case "normal":
            forgeView.isSecureTextEntry = false
            forgeView.textContentType = nil
            forgeView.autocorrectionType = .yes
            forgeView.spellCheckingType = .default
        case "noSuggestions":
            forgeView.isSecureTextEntry = false
            forgeView.textContentType = nil
            forgeView.autocorrectionType = .no
            forgeView.spellCheckingType = .no
        default:  // "password", nil, or any unrecognized future value.
            forgeView.isSecureTextEntry = true
            forgeView.textContentType = .password
            forgeView.autocorrectionType = .no
            forgeView.spellCheckingType = .no
        }
    }

    private func startDisplayLink() {
        guard displayLink == nil else { return }
        let link = CADisplayLink(target: self, selector: #selector(renderFrame(_:)))
        // Enable up to 120Hz on ProMotion hardware (iOS 15+): request the device's
        // maximum refresh rate with a minimum of 30fps to let the system down-clock
        // on idle/thermal throttle (the framework's own dirty-gate is
        // what actually saves power on skipped frames).
        link.preferredFrameRateRange = CAFrameRateRange(
            minimum: 30,
            maximum: Float(UIScreen.main.maximumFramesPerSecond),
            preferred: Float(UIScreen.main.maximumFramesPerSecond)
        )
        link.add(to: .main, forMode: .common)
        displayLink = link
    }

    // MARK: - System UI / SystemChrome

    /// Per-tick poll of the process-wide system-UI override slot
    /// (`frust::set_system_ui_mode`) — decodes `frust_system_ui_state`'s
    /// packed `(generation, mode)` `u64` and updates
    /// [statusBarHidden]/[homeIndicatorAutoHidden] only when the generation
    /// has advanced since the last poll, then nudges UIKit to re-query both
    /// via `setNeedsStatusBarAppearanceUpdate()` /
    /// `setNeedsUpdateOfHomeIndicatorAutoHidden()`. Generation `0` (never
    /// called) applies nothing — platform defaults stand until the app calls
    /// the API. See the `frust_system_ui_state` doc comment (Rust
    /// side) for the full iOS mapping table: every hiding mode
    /// (`Immersive`/`ImmersiveSticky`/`LeanBack`) collapses to the same
    /// status-bar-hidden + home-indicator-auto-hide behavior (iOS has no
    /// sticky/non-sticky or lean-back distinction, and no *force*-hide of
    /// the home indicator); `Manual { top, bottom }` splits status bar
    /// (`!top`) from home-indicator auto-hide (`!bottom`).
    private func pollSystemUiState() {
        guard let handle else { return }
        let encoded = frust_system_ui_state(handle)
        let generation = encoded >> 8
        guard generation != lastSystemUiGeneration else { return }
        lastSystemUiGeneration = generation
        guard generation != 0 else { return }

        let low = encoded & 0xFF
        let discriminant = low & 0x0F
        switch discriminant {
        case 0:  // EdgeToEdge
            statusBarHidden = false
            homeIndicatorAutoHidden = false
        case 1, 2, 3:  // Immersive / ImmersiveSticky / LeanBack
            statusBarHidden = true
            homeIndicatorAutoHidden = true
        default:  // Manual { top, bottom }
            let top = (low & 0x10) != 0
            let bottom = (low & 0x20) != 0
            statusBarHidden = !top
            homeIndicatorAutoHidden = !bottom
        }
        setNeedsStatusBarAppearanceUpdate()
        setNeedsUpdateOfHomeIndicatorAutoHidden()
    }

    public override var prefersStatusBarHidden: Bool { statusBarHidden }

    public override var prefersHomeIndicatorAutoHidden: Bool { homeIndicatorAutoHidden }

    @objc private func renderFrame(_ link: CADisplayLink) {
        guard let handle else { return }
        // Cheap, generation-gated per-tick poll: applied
        // only on an actual `set_system_ui_mode` change.
        pollSystemUiState()
        // `link.timestamp` is a `CFTimeInterval` (seconds); the Rust side wants
        // the shell-owned monotonic frame clock in nanoseconds. The
        // f64 * 1e9 multiply/round is tolerated here because Rust only ever
        // *differences* two FrameTimes (never reads one as an absolute
        // wall-clock value) — see frust-core::anim's FrameTime contract.
        // Don't "fix" this by reordering the multiply/cast without reading
        // that contract first.
        let alive = frust_render_frame(handle, UInt64(link.timestamp * 1_000_000_000))
        if alive == 0 {
            // A 0 return is a FATAL, unrecoverable render-thread failure (the
            // first surface install could not succeed) — latch it exactly like a
            // failed `frust_init` (so `updateSurface`'s `!initFailed` guard never
            // re-runs a doomed init) and stop the display link rather than drive
            // doomed frames against a permanent black screen.
            initFailed = true
            displayLink?.invalidate()
            displayLink = nil
            NSLog("Frust: render thread reported a fatal error — rendering disabled for this session")
            return
        }
        // Per-frame IME reconcile — the direct analogue of Android's
        // `pollImeAfterDispatch()` call from `doFrame`
        // (`FrustSurfaceView.kt`), placed in the same position: after the
        // native frame call, before the platform-view work.
        //
        // **Why a per-frame site is required.** Focus changes that no touch
        // originated are the common case, not the edge case: pressing Return
        // moves focus to the next field entirely through the `imeRoundTrip`
        // closure, and `frust::request_focus`-style programmatic moves have no
        // UIKit event at all. With `onTouch` as the only call site,
        // `syncImeFocus` never re-runs on those paths — the previous field's
        // `isSecureTextEntry` stays live for the new field, and the mirror
        // keeps the previous field's text.
        //
        // **Why here and not inside `imeRoundTrip`.** `imeRoundTrip` runs
        // *inside* a `UITextInput` callback (`insertText`, `setMarkedText`, …)
        // via `FrustView.syncToRust()`; calling `syncImeFocus` there would
        // resign/become the first responder re-entrantly while UIKit is
        // mid-edit, and would mutate the mirror the caller is about to
        // reconcile. The frame tick reaches the same state at most one display
        // refresh later (≤8.3ms at 120Hz) with no re-entrancy.
        //
        // **Cost.** One `frust_ime_state_json` FFI call (a `pump_reactive` plus
        // a small JSON build) and one `JSONSerialization` parse per tick —
        // the same shape and the same per-frame budget Android's
        // `pollImeAfterDispatch` already spends on `nativeImeState`. There is
        // no cheaper generation-gated probe for IME state (unlike
        // `pollSystemUiState`'s packed `u64`), so this is a real, if small,
        // per-frame allocation. It does **not** rewrite anything on a steady
        // field: every mutating path below is guarded — traits only on a
        // classification change, the mirror only on genuine divergence, and
        // never through a live composition.
        syncImeFocus()
        // Platform views: apply this frame's compositor command
        // batch (create/reposition/dispose native sibling views) right after
        // the Frust surface has painted, so native views and Frust content
        // land in the same visual frame. Cheap when idle (null poll).
        //
        // Present-sync: when armed, Frust's own
        // `[drawable present]` and the sibling geometry that frame painted must
        // commit in ONE transaction, on this (the committing) thread — that is
        // the entire contract `presentsWithTransaction` asks for.
        //
        // **Order is load-bearing: present FIRST, then poll.**
        // `frust_present_frame` presents the frame the render thread parked
        // (typically the previous tick's, since the render thread runs a tick
        // behind) and records its id; the `poll` that follows then releases
        // exactly *that* frame's geometry batch and no later one — so pixels
        // and geometry that belong together land in the same commit. Polling
        // first would pair this tick's geometry with the previous tick's pixels
        // and merely invert the desync. Unarmed, this is byte-for-byte the
        // previous behavior: poll alone, inside UIKit's own implicit
        // main-thread transaction.
        if presentSyncArmed {
            CATransaction.begin()
            frust_present_frame(handle)
            platformViewHost?.poll(handle: handle)
            CATransaction.commit()
        } else {
            platformViewHost?.poll(handle: handle)
        }
    }

    @objc private func appWillResignActive() {
        displayLink?.isPaused = true
        if let handle { frust_pause(handle) }
    }

    @objc private func appDidBecomeActive() {
        if let handle { frust_resume(handle) }
        displayLink?.isPaused = false
        // Re-read the reduce-motion preference on every foreground: a
        // suspended app is not guaranteed to have been delivered the
        // notification for a toggle made while it was away (the user has to
        // leave for Settings to flip it, so this is a routine path, not an
        // edge case).
        pushReduceMotion()
    }

    /// The platform's light/dark appearance preference changed —
    /// re-seed the theme's brightness.
    ///
    /// Appearance only: reduce motion is an `UIAccessibility` preference, not a
    /// `UITraitCollection` trait, so it never reports here — see
    /// `reduceMotionDidChange`.
    public override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
        super.traitCollectionDidChange(previousTraitCollection)
        guard let handle else { return }
        frust_set_appearance(handle, traitCollection.userInterfaceStyle == .dark ? 1 : 0)
    }

    /// The platform's reduce-motion accessibility preference changed
    /// (`UIAccessibility.reduceMotionStatusDidChangeNotification`) — re-push it
    /// so the theme's motion tokens collapse (or un-collapse) live.
    @objc private func reduceMotionDidChange() {
        pushReduceMotion()
    }

    /// Push `UIAccessibility.isReduceMotionEnabled` to Rust as the C ABI's
    /// `0`/`1`. A missing handle is a no-op — `updateSurface` pushes once
    /// `frust_init` has returned one, mirroring the appearance seed.
    private func pushReduceMotion() {
        guard let handle else { return }
        frust_set_reduce_motion(handle, UIAccessibility.isReduceMotionEnabled ? 1 : 0)
    }

    deinit {
        displayLink?.invalidate()
        displayLink = nil
        NotificationCenter.default.removeObserver(self)
        if let handle {
            frust_destroy(handle)
        }
    }
}
