import UIKit

// Generated by `frust create`. The `UITextInput`
// conformance for `FrustView`, implemented Flutter-style over a UTF-16
// `NSMutableString` mirror (declared on the view in `FrustView.swift`).
//
// Adopting the *full* protocol — not just `UIKeyInput` — is what unlocks
// autocorrect, the predictive bar, CJK marked text, and dictation. Every member
// below is mechanical over the mirror; positions/ranges are UTF-16 code-unit
// offsets, marked text maps directly onto the framework's composing region, and
// geometry is approximated from the caret rect Rust publishes.
//
// The clipboard verbs are NOT here. Copy/Cut/Paste/Select All are
// `UIResponderStandardEditActions`, not `UITextInput` members, and live on
// `FrustView` itself (see `FrustView.swift`) — which is what routes UIKit's own
// edit menu and a hardware keyboard's Cmd+C/X/V/A to them, and what keeps every
// paste on the system-initiated path iOS exempts from its paste-permission
// alert. They deliberately bypass the mirror below: each hands the verb to the
// focused Rust widget, which owns the selection and the text, and the resulting
// change arrives back here the way any other change no UIKit callback
// originated does — through `reconcileMirror(to:)` on the controller's
// per-frame poll.

// MARK: - Position / range / selection-rect value types

/// A caret position as a UTF-16 offset into the mirror.
final class FrustTextPosition: UITextPosition {
    let index: Int
    init(_ index: Int) { self.index = index }
}

/// A text range as an ordered pair of UTF-16 offsets.
final class FrustTextRange: UITextRange {
    let from: Int
    let to: Int

    init(from: Int, to: Int) {
        self.from = min(from, to)
        self.to = max(from, to)
    }

    override var start: UITextPosition { FrustTextPosition(from) }
    override var end: UITextPosition { FrustTextPosition(to) }
    override var isEmpty: Bool { from == to }
}

/// A single approximated selection rectangle (v1 returns one covering rect).
final class FrustTextSelectionRect: UITextSelectionRect {
    private let _rect: CGRect
    init(rect: CGRect) { _rect = rect }

    override var rect: CGRect { _rect }
    override var writingDirection: NSWritingDirection { .leftToRight }
    override var containsStart: Bool { true }
    override var containsEnd: Bool { true }
    override var isVertical: Bool { false }
}

// MARK: - State sync

extension FrustView {
    /// Push the current mirror state to Rust and reconcile against the value Rust
    /// produces (autocorrect, clamping, composing normalization, ...). Called
    /// after every local mutation.
    func syncToRust() {
        let selBase = selectedRange.location
        let selExt = selectedRange.location + selectedRange.length
        let (compBase, compExt): (Int, Int)
        if markedRange.location == NSNotFound {
            (compBase, compExt) = (-1, -1)
        } else {
            (compBase, compExt) = (markedRange.location, markedRange.location + markedRange.length)
        }
        // `imeRoundTrip?(...)` is doubly-optional (optional closure returning an
        // optional dict); `?? nil` flattens it before unwrapping.
        guard
            let reconciled =
                imeRoundTrip?(mirror as String, selBase, selExt, compBase, compExt) ?? nil
        else { return }
        applyReconciled(reconciled)
    }

    /// Seed the mirror + selection/marked/caret from a Rust editing state without
    /// notifying the input delegate — used when the field first becomes focused.
    func seedMirror(from state: [String: Any]) {
        if let text = state["text"] as? String { mirror.setString(text) }
        selectedRange = selection(from: state)
        markedRange = marked(from: state)
        lastCaretRect = caret(from: state)
    }

    /// Reconcile the mirror against a Rust-published editing state that the
    /// platform did **not** originate — the iOS counterpart of Android's
    /// `FrustSurfaceView.FrustInputConnection.reconcileTo`, and the seam
    /// `FrustViewController.syncImeFocus` drives on a steady-active field.
    ///
    /// Why this exists at all: `forgeView` is the *one* shared `UITextInput`
    /// responder for the whole tree, so focus moving from field A to field B
    /// never trips `!isFirstResponder` and never reaches `seedMirror`. Without
    /// a divergence-guarded reconcile the mirror keeps **field A's text**, and
    /// the first edit in B round-trips `A_text + char` through
    /// `frust_ime_apply` — which applies to whatever widget is focused *now*,
    /// with no widget-identity check, replacing B's content with A's.
    ///
    /// Cheap and non-destructive by construction: it delegates to
    /// `applyReconciled`, which compares text/selection/marked against the LIVE
    /// mirror and returns without touching anything (and without notifying the
    /// input delegate) when they already agree — the mismatch guard that makes
    /// a per-frame call site affordable, exactly as `reconcileTo` does on
    /// Android. Normal typing is a no-op here: `syncToRust` already pushed the
    /// mirror and applied Rust's echo.
    ///
    /// **A live composition is skipped entirely.** While `markedRange` is set,
    /// the user is mid-composition (CJK/dictation) and UIKit owns that region;
    /// rewriting the mirror underneath it would abandon the composition and
    /// move the caret. The composition path round-trips through `syncToRust` on
    /// every `setMarkedText`, so the mirror is already authoritative there, and
    /// the reconcile resumes the moment `unmarkText`/`insertText` commits.
    /// (Android's `reconcileTo` reaches the same outcome differently: it
    /// reconciles selection without a `restartInput` precisely so an active
    /// composition is not dropped.)
    func reconcileMirror(to state: [String: Any]) {
        guard markedRange.location == NSNotFound else { return }
        applyReconciled(state)
    }

    /// Reconcile the mirror against a Rust editing state, notifying the input
    /// delegate only around the parts that actually changed (the common typing
    /// echo — Rust returning exactly what we pushed — is a no-op).
    private func applyReconciled(_ state: [String: Any]) {
        let newText = (state["text"] as? String) ?? (mirror as String)
        let newSelection = selection(from: state)
        let newMarked = marked(from: state)
        lastCaretRect = caret(from: state)

        let textChanged = !mirror.isEqual(to: newText)
        let selectionChanged = !NSEqualRanges(selectedRange, newSelection)
        let markedChanged = !NSEqualRanges(markedRange, newMarked)

        if !textChanged && !selectionChanged && !markedChanged { return }

        if textChanged { inputDelegate?.textWillChange(self) }
        if selectionChanged { inputDelegate?.selectionWillChange(self) }

        if textChanged { mirror.setString(newText) }
        selectedRange = newSelection
        markedRange = newMarked

        if selectionChanged { inputDelegate?.selectionDidChange(self) }
        if textChanged { inputDelegate?.textDidChange(self) }
    }

    /// The selection range from a Rust editing state (UTF-16, ordered, clamped).
    private func selection(from state: [String: Any]) -> NSRange {
        let base = (state["selBase"] as? Int) ?? 0
        let ext = (state["selExt"] as? Int) ?? base
        let lo = max(0, min(min(base, ext), mirror.length))
        let hi = max(0, min(max(base, ext), mirror.length))
        return NSRange(location: lo, length: hi - lo)
    }

    /// The composing range from a Rust editing state, or `NSNotFound` when none.
    private func marked(from state: [String: Any]) -> NSRange {
        guard let base = state["compBase"] as? Int, let ext = state["compExt"] as? Int,
            base >= 0, ext >= 0
        else {
            return NSRange(location: NSNotFound, length: 0)
        }
        let lo = max(0, min(min(base, ext), mirror.length))
        let hi = max(0, min(max(base, ext), mirror.length))
        return NSRange(location: lo, length: hi - lo)
    }

    /// The caret rect from a Rust editing state (logical px == view points).
    private func caret(from state: [String: Any]) -> CGRect? {
        guard let x = state["caretX"] as? Double, let y = state["caretY"] as? Double,
            let w = state["caretW"] as? Double, let h = state["caretH"] as? Double
        else { return nil }
        return CGRect(x: x, y: y, width: w, height: h)
    }

    /// Clamp an arbitrary range to the mirror's bounds.
    fileprivate func clamp(_ range: NSRange) -> NSRange {
        let lo = max(0, min(range.location, mirror.length))
        let hi = max(lo, min(range.location + range.length, mirror.length))
        return NSRange(location: lo, length: hi - lo)
    }

    /// A never-null fallback caret (a thin bar at the origin) so `caretRect` never
    /// hands UIKit `CGRect.null`, which suppresses the caret entirely.
    fileprivate func fallbackCaretRect() -> CGRect {
        CGRect(x: 0, y: 0, width: 2, height: 16)
    }
}

// MARK: - UIKeyInput

extension FrustView {
    var hasText: Bool { mirror.length > 0 }

    func insertText(_ text: String) {
        // The `.done` Return key arrives here as a lone "\n"; forward it as a
        // newline insert — the Rust `TextInput` widget maps a single-line newline
        // insert to its `on_submit` trigger (contract shared with the Rust glue).
        let target = markedRange.location != NSNotFound ? markedRange : selectedRange
        mirror.replaceCharacters(in: target, with: text)
        let caret = target.location + (text as NSString).length
        selectedRange = NSRange(location: caret, length: 0)
        markedRange = NSRange(location: NSNotFound, length: 0)
        syncToRust()
    }

    func deleteBackward() {
        if selectedRange.length > 0 {
            mirror.replaceCharacters(in: selectedRange, with: "")
            selectedRange = NSRange(location: selectedRange.location, length: 0)
        } else if selectedRange.location > 0 {
            // Delete one composed character (grapheme) before the caret, so an
            // emoji / combining sequence is removed as a unit.
            let deleteRange = mirror.rangeOfComposedCharacterSequence(
                at: selectedRange.location - 1)
            mirror.replaceCharacters(in: deleteRange, with: "")
            selectedRange = NSRange(location: deleteRange.location, length: 0)
        }
        markedRange = NSRange(location: NSNotFound, length: 0)
        syncToRust()
    }
}

// MARK: - UITextInput

extension FrustView: UITextInput {
    // --- Text access ---

    func text(in range: UITextRange) -> String? {
        guard let r = range as? FrustTextRange else { return nil }
        return mirror.substring(with: clamp(NSRange(location: r.from, length: r.to - r.from)))
    }

    func replace(_ range: UITextRange, withText text: String) {
        guard let r = range as? FrustTextRange else { return }
        mirror.replaceCharacters(
            in: clamp(NSRange(location: r.from, length: r.to - r.from)), with: text)
        selectedRange = NSRange(location: r.from + (text as NSString).length, length: 0)
        markedRange = NSRange(location: NSNotFound, length: 0)
        syncToRust()
    }

    // --- Selection / marked text ---

    var selectedTextRange: UITextRange? {
        get {
            FrustTextRange(
                from: selectedRange.location, to: selectedRange.location + selectedRange.length)
        }
        set {
            if let r = newValue as? FrustTextRange {
                let clamped = clamp(NSRange(location: r.from, length: r.to - r.from))
                selectedRange = clamped
            } else {
                selectedRange = NSRange(location: mirror.length, length: 0)
            }
            markedRange = NSRange(location: NSNotFound, length: 0)
            syncToRust()
        }
    }

    var markedTextRange: UITextRange? {
        guard markedRange.location != NSNotFound else { return nil }
        return FrustTextRange(
            from: markedRange.location, to: markedRange.location + markedRange.length)
    }

    func setMarkedText(_ markedText: String?, selectedRange: NSRange) {
        let text = markedText ?? ""
        let target = markedRange.location != NSNotFound ? markedRange : self.selectedRange
        mirror.replaceCharacters(in: target, with: text)
        markedRange = NSRange(location: target.location, length: (text as NSString).length)
        // `selectedRange` is relative to the freshly-inserted marked text.
        self.selectedRange = clamp(
            NSRange(location: target.location + selectedRange.location, length: selectedRange.length))
        syncToRust()
    }

    func unmarkText() {
        guard markedRange.location != NSNotFound else { return }
        // Commit the composition: caret moves to the end of the former marked run.
        selectedRange = NSRange(location: markedRange.location + markedRange.length, length: 0)
        markedRange = NSRange(location: NSNotFound, length: 0)
        syncToRust()
    }

    // --- Document endpoints & range/position arithmetic ---

    var beginningOfDocument: UITextPosition { FrustTextPosition(0) }
    var endOfDocument: UITextPosition { FrustTextPosition(mirror.length) }

    func textRange(from fromPosition: UITextPosition, to toPosition: UITextPosition) -> UITextRange?
    {
        guard let f = fromPosition as? FrustTextPosition,
            let t = toPosition as? FrustTextPosition
        else { return nil }
        return FrustTextRange(from: f.index, to: t.index)
    }

    func position(from position: UITextPosition, offset: Int) -> UITextPosition? {
        guard let p = position as? FrustTextPosition else { return nil }
        let idx = p.index + offset
        guard idx >= 0, idx <= mirror.length else { return nil }
        return FrustTextPosition(idx)
    }

    func position(
        from position: UITextPosition, in direction: UITextLayoutDirection, offset: Int
    ) -> UITextPosition? {
        guard let p = position as? FrustTextPosition else { return nil }
        let delta: Int
        switch direction {
        case .right, .down: delta = offset
        case .left, .up: delta = -offset
        @unknown default: delta = offset
        }
        let idx = p.index + delta
        guard idx >= 0, idx <= mirror.length else { return nil }
        return FrustTextPosition(idx)
    }

    func compare(_ position: UITextPosition, to other: UITextPosition) -> ComparisonResult {
        guard let a = position as? FrustTextPosition, let b = other as? FrustTextPosition
        else { return .orderedSame }
        if a.index < b.index { return .orderedAscending }
        if a.index > b.index { return .orderedDescending }
        return .orderedSame
    }

    func offset(from: UITextPosition, to toPosition: UITextPosition) -> Int {
        guard let a = from as? FrustTextPosition, let b = toPosition as? FrustTextPosition
        else { return 0 }
        return b.index - a.index
    }

    // --- Writing direction (single-line LTR v1: stubs) ---

    func position(within range: UITextRange, farthestIn direction: UITextLayoutDirection)
        -> UITextPosition?
    {
        guard let r = range as? FrustTextRange else { return nil }
        switch direction {
        case .left, .up: return FrustTextPosition(r.from)
        case .right, .down: return FrustTextPosition(r.to)
        @unknown default: return FrustTextPosition(r.to)
        }
    }

    func characterRange(byExtending position: UITextPosition, in direction: UITextLayoutDirection)
        -> UITextRange?
    {
        guard let p = position as? FrustTextPosition else { return nil }
        switch direction {
        case .left, .up: return FrustTextRange(from: max(0, p.index - 1), to: p.index)
        case .right, .down:
            return FrustTextRange(from: p.index, to: min(mirror.length, p.index + 1))
        @unknown default: return FrustTextRange(from: p.index, to: p.index)
        }
    }

    func baseWritingDirection(for position: UITextPosition, in direction: UITextStorageDirection)
        -> NSWritingDirection
    {
        .natural
    }

    func setBaseWritingDirection(_ writingDirection: NSWritingDirection, for range: UITextRange) {
        // No-op: single-line LTR in v1.
    }

    // --- Geometry (approximated from the caret rect Rust publishes) ---

    func firstRect(for range: UITextRange) -> CGRect {
        lastCaretRect ?? fallbackCaretRect()
    }

    func caretRect(for position: UITextPosition) -> CGRect {
        // Never CGRect.null — that hides the caret; fall back to a thin bar.
        lastCaretRect ?? fallbackCaretRect()
    }

    func selectionRects(for range: UITextRange) -> [UITextSelectionRect] {
        [FrustTextSelectionRect(rect: lastCaretRect ?? fallbackCaretRect())]
    }

    func closestPosition(to point: CGPoint) -> UITextPosition? {
        // Nearest-clamp approximation: v1 has no per-glyph hit-testing on the
        // Swift side, so snap to the current caret.
        FrustTextPosition(min(selectedRange.location, mirror.length))
    }

    func closestPosition(to point: CGPoint, within range: UITextRange) -> UITextPosition? {
        guard let r = range as? FrustTextRange else { return closestPosition(to: point) }
        let clamped = min(max(selectedRange.location, r.from), r.to)
        return FrustTextPosition(clamped)
    }

    func characterRange(at point: CGPoint) -> UITextRange? {
        let loc = min(selectedRange.location, mirror.length)
        return FrustTextRange(from: loc, to: min(mirror.length, loc + 1))
    }
}
