package it.f0x.shadertoy

import android.content.Intent
import android.os.Bundle
import android.util.Log
import androidx.activity.ComponentActivity
import androidx.activity.OnBackPressedCallback
import androidx.core.view.WindowCompat
import androidx.core.view.WindowInsetsCompat
import androidx.core.view.WindowInsetsControllerCompat
import dev.frust.FrustSurfaceView

/**
 * Generated by `frust create` (spec Phase 2 §10.1). Hosts the Frust
 * render surface as the activity's entire content view and forwards the
 * lifecycle callbacks the Choreographer render loop needs.
 *
 * `ComponentActivity` (not plain `Activity`, device-parity task 08) is the
 * base class purely for [getOnBackPressedDispatcher] — see the back-press
 * callback below; nothing else about the activity's lifecycle behavior
 * changes.
 *
 * Edge-to-edge (task 08 — RESEARCH.md "Insets / SafeArea / SystemChrome"):
 * `WindowCompat.setDecorFitsSystemWindows(window, false)` draws content
 * under the system bars, which stay **visible** (`SystemUiMode.edgeToEdge`
 * semantics — this is not a bar-hiding fullscreen mode, hence the
 * manifest's `Theme.NoTitleBar`, not `.Fullscreen`).
 * `FrustSurfaceView`'s `OnApplyWindowInsetsListener` reports the
 * resulting system-bar/cutout/IME occlusion back into the framework via
 * `nativeOnInsetsChanged`. `windowSoftInputMode="adjustResize"` (manifest)
 * is intentionally inert once edge-to-edge is on — the IME arrives as an
 * inset push instead of a window resize, matching Flutter's model.
 *
 * Deep links (task 07): cold-start delivery forwards `intent?.data` from
 * [onCreate]; a running instance receives a link via [onNewIntent] instead
 * (this activity's manifest entry declares `android:launchMode="singleTop"`
 * precisely so a warm relaunch reuses this instance rather than creating a
 * new one). Both funnel into [FrustSurfaceView.onDeepLink], which queues
 * the link until the native handle exists if it arrives first (cold-start
 * routinely races ahead of `nativeInit`, since that only runs once the
 * `SurfaceHolder` callback fires).
 *
 * Back (task 08 — RESEARCH.md "Android back"): a single always-enabled
 * `onBackPressedDispatcher` callback offers every press to the framework
 * first (`FrustSurfaceView.dispatchBackPress`, wrapping
 * `nativeOnBackPress`). When the framework didn't consume it (no navigator,
 * or already at the root — matches Flutter's `bubble` case), the callback
 * disables itself and re-dispatches so the next-priority callback in the
 * chain runs — `ComponentActivity`'s own default handler, which finishes
 * the activity — then re-enables itself for the next press.
 *
 * System UI / SystemChrome (task 03/09/14/17 — RESEARCH.md "Insets /
 * SafeArea / SystemChrome", Flutter `SystemChrome.setEnabledSystemUIMode`
 * parity): this Activity owns the `Window` a `WindowInsetsControllerCompat`
 * needs, so [FrustSurfaceView] (which owns `doFrame` and therefore the
 * per-frame poll) hands a decoded mode to [applySystemUiMode] via
 * [FrustSurfaceView.onSystemUiModeChanged], wired up in [onCreate]. Replaces
 * this app's former hardcoded immersive-on-launch block — the shell
 * (`lib.rs`) now drives immersive-sticky from the shader view and
 * edge-to-edge from the menu via `frust::set_system_ui_mode`.
 */
class MainActivity : ComponentActivity() {
    private lateinit var surfaceView: FrustSurfaceView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        // Perf instrumentation (spec §14 phase 7.A, task 08): a single fixed
        // marker at activity-create entry, under the same "frust" logcat
        // tag the Rust side's `frust-perf startup ...`/`frust-perf
        // frame ...` lines use, so the Kotlin-side gap (process start ->
        // surfaceCreated -> native init) is measurable from the same
        // logcat stream. No other behavior change.
        Log.i("frust", "frust-perf activity-create")
        WindowCompat.setDecorFitsSystemWindows(window, false)
        surfaceView = FrustSurfaceView(this)
        surfaceView.onSystemUiModeChanged = ::applySystemUiMode
        setContentView(surfaceView)
        surfaceView.onDeepLink(intent?.data?.toString())

        onBackPressedDispatcher.addCallback(
            this,
            object : OnBackPressedCallback(true) {
                override fun handleOnBackPressed() {
                    if (!surfaceView.dispatchBackPress()) {
                        isEnabled = false
                        onBackPressedDispatcher.onBackPressed()
                        isEnabled = true
                    }
                }
            },
        )
    }

    /**
     * Apply a decoded [FrustSurfaceView.SystemUiMode] via
     * `WindowInsetsControllerCompat` (task 03/09/14/17 — RESEARCH.md "Insets /
     * SafeArea / SystemChrome"), Flutter `SystemChrome.setEnabledSystemUIMode`
     * parity. Mirrors [FrustSurfaceView]'s own `updateSystemBarsAppearance`
     * (same `WindowCompat.getInsetsController` call, driving bar visibility
     * here instead of icon contrast there).
     *
     * `LeanBack` has no `WindowInsetsControllerCompat` tap-to-reveal
     * equivalent — like `Immersive`, it maps to
     * [WindowInsetsControllerCompat.BEHAVIOR_DEFAULT] (any edge swipe
     * reveals the bars); only `ImmersiveSticky` gets the transient-swipe
     * behavior. See `frust_shell_common::system_ui`'s module docs (task 03)
     * for the full platform-parity notes, including the Android 16/API
     * 36+ forced-edge-to-edge caveat this Activity cannot work around.
     */
    private fun applySystemUiMode(mode: FrustSurfaceView.SystemUiMode) {
        val controller = WindowCompat.getInsetsController(window, surfaceView)
        when (mode) {
            is FrustSurfaceView.SystemUiMode.EdgeToEdge -> {
                controller.show(WindowInsetsCompat.Type.systemBars())
            }
            is FrustSurfaceView.SystemUiMode.Immersive -> {
                controller.systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_DEFAULT
                controller.hide(WindowInsetsCompat.Type.systemBars())
            }
            is FrustSurfaceView.SystemUiMode.ImmersiveSticky -> {
                controller.systemBarsBehavior =
                    WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
                controller.hide(WindowInsetsCompat.Type.systemBars())
            }
            is FrustSurfaceView.SystemUiMode.LeanBack -> {
                controller.systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_DEFAULT
                controller.hide(WindowInsetsCompat.Type.systemBars())
            }
            is FrustSurfaceView.SystemUiMode.Manual -> {
                if (mode.top) {
                    controller.show(WindowInsetsCompat.Type.statusBars())
                } else {
                    controller.hide(WindowInsetsCompat.Type.statusBars())
                }
                if (mode.bottom) {
                    controller.show(WindowInsetsCompat.Type.navigationBars())
                } else {
                    controller.hide(WindowInsetsCompat.Type.navigationBars())
                }
            }
        }
    }

    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        setIntent(intent)
        surfaceView.onDeepLink(intent.data?.toString())
    }

    override fun onResume() {
        super.onResume()
        surfaceView.onResume()
    }

    override fun onPause() {
        surfaceView.onPause()
        super.onPause()
    }

    override fun onDestroy() {
        surfaceView.onDestroy()
        super.onDestroy()
    }
}