import UIKit

// Generated by `frust create`. The plugin-facing
// contract for hosting a native UIKit view underneath/above the Frust
// render surface — the iOS mirror of Android's `dev.frust.
// FrustPlatformViewFactory` interface. Both platforms expose ONE contract
// (same method names/order) so plugin docs describe it once.
//
// A factory is an `NSObject` subclass conforming to this protocol and
// annotated `@objc(ExplicitName)`:
//
//     @objc(MyMapViewFactory)
//     final class MyMapViewFactory: NSObject, FrustPlatformViewFactory {
//         func createView(paramsJson: String) -> UIView { ... }
//     }
//
// The `@objc(ExplicitName)` annotation is REQUIRED: it fixes the ObjC
// runtime name so `NSClassFromString("MyMapViewFactory")` (how
// `FrustViewHost` resolves a factory from the `viewType` string in the
// command channel) is stable regardless of the app's Swift module name.
// Without it, the mangled name embeds the module and the lookup breaks in
// a renamed app.
//
// Input routing (v1): hosted views receive OS-routed touches directly
// (UIKit hit-testing is view-level), so there is no gesture-forwarding
// hook here — a hosted view either handles a touch itself or it falls
// through to the Frust surface behind/in front of it. Frust never
// intercepts a touch destined for a hosted view.
// The explicit `@objc(FrustPlatformViewFactory)` name is LOAD-BEARING for the
// same reason the class annotation above is: without it, Swift registers the
// protocol with the ObjC runtime under its MANGLED name
// (`_TtP14FrustEmbedding24FrustPlatformViewFactory_`), so a non-Swift
// implementor (e.g. a Rust `define_class!` factory attaching conformance by
// name via `objc_getProtocol`) can never match the object
// `class_conformsToProtocol` checks against. Swift-side conformances are
// by-type and unaffected.
@objc(FrustPlatformViewFactory) public protocol FrustPlatformViewFactory {
    /// Create the native view for a freshly-created slot. Called on the main
    /// thread; must not block. `paramsJson` is the app-supplied parameter
    /// blob (the same JSON the Rust `platform_view` widget was given) — the
    /// factory decides its own schema. The returned view is positioned,
    /// sized, clipped, and shown/hidden entirely by `FrustViewHost` from the
    /// command channel; the factory should not set its own frame.
    ///
    /// **The return value is non-optional, and that is a real contract a
    /// non-Swift factory must honour by hand.** `FrustViewHost.applyCreate`
    /// calls `wrapper.addSubview(content)` on the result with no nil check —
    /// correct, since this method neither returns an optional nor throws. A
    /// factory written in Swift gets that guarantee from the compiler; a
    /// factory implemented in **Objective-C or Rust** (`objc2`'s
    /// `define_class!` — `frust-native-widgets` is the in-repo precedent) does
    /// **not**, because Objective-C does not enforce nullability, and a nil
    /// returned into this non-optional binding is an unchecked crash at first
    /// use.
    ///
    /// So a non-Swift factory MUST return an **empty placeholder `UIView` on
    /// every failure path** — a failed create, a caught panic, unreadable
    /// params, anything — rather than nil. The host then positions an
    /// invisible, inert slot: a dead slot, not a crashed frame loop. This
    /// mirrors what Android's `FrustPlatformViewFactory.createView` gets by
    /// throwing into `FrustViewHost`'s `catch (Throwable)`; iOS has no
    /// exception channel here, so the placeholder return is the equivalent.
    func createView(paramsJson: String) -> UIView

    /// A params-only change (no reposition) for an already-created view.
    /// Optional — omit it if the view has no mutable parameters. Called on
    /// the main thread.
    @objc optional func updateParams(_ view: UIView, paramsJson: String)

    /// Tear-down hook, called on the main thread right before the host
    /// removes the view from the hierarchy (slot disposed). Optional —
    /// omit it if the view needs no explicit cleanup.
    @objc optional func disposeView(_ view: UIView)
}
