import UIKit
import QuartzCore

// Generated by `forgekit create` (spec Phase 3 §10.2). Hosts the ForgeKit
// render surface and drives it from a `CADisplayLink`, bridging UIKit's
// view/scene lifecycle (and touch input) to the seven `forgekit_*` FFI calls.
//
// Contract enforced here (mirrored on the Rust side, belt-and-suspenders):
//   - `forgekit_init` is called exactly once, on the first valid layout;
//     every later size change goes through `forgekit_resize`.
//   - The display link (and the native renderer via `forgekit_pause`) is
//     paused when the app resigns active — submitting Metal work from a
//     backgrounded app can get the process killed.
//   - `forgekit_destroy` reclaims the native handle before the view is gone.
final class ForgeKitViewController: UIViewController {
    private var forgeView: ForgeKitView { view as! ForgeKitView }
    private var displayLink: CADisplayLink?
    private var handle: UnsafeMutableRawPointer?
    private var lastDrawableSize: CGSize = .zero
    // `forgekit_init` failure is session-permanent by design: the shell has
    // no transient failure mode (the one observed cause, a simulator GPU
    // missing a required Metal feature, cannot change mid-process). Once
    // `forgekit_init` returns nil, latch here so every later UIKit layout
    // pass (rotation, keyboard, autolayout churn, ...) is a no-op instead of
    // re-running a doomed synchronous `pollster::block_on` adapter/device
    // request and re-logging the failure. If a transient failure mode is
    // ever introduced on the Rust side, this is the place to revisit.
    private var initFailed = false

    override func loadView() {
        view = ForgeKitView()
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        let scale = UIScreen.main.scale
        view.contentScaleFactor = scale
        forgeView.metalLayer.contentsScale = scale

        // Bridge the view's raw touch callbacks into the native tree (spec §9).
        // `location` is already logical points, so it is passed through without
        // any scale division (contrast Android's physical-pixel touch path).
        forgeView.onTouch = { [weak self] phase, location in
            guard let self, let handle = self.handle else { return }
            forgekit_dispatch_touch(handle, phase, Float(location.x), Float(location.y))
        }

        NotificationCenter.default.addObserver(
            self,
            selector: #selector(appWillResignActive),
            name: UIApplication.willResignActiveNotification,
            object: nil
        )
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(appDidBecomeActive),
            name: UIApplication.didBecomeActiveNotification,
            object: nil
        )
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        updateSurface()
    }

    override func viewWillTransition(
        to size: CGSize,
        with coordinator: UIViewControllerTransitionCoordinator
    ) {
        super.viewWillTransition(to: size, with: coordinator)
        coordinator.animate(alongsideTransition: nil) { [weak self] _ in
            self?.updateSurface()
        }
    }

    /// Sizes the drawable to the view's pixel bounds and either creates the
    /// native renderer (first valid layout) or resizes it (thereafter).
    private func updateSurface() {
        guard !initFailed else { return }

        let scale = view.contentScaleFactor
        let bounds = view.bounds.size
        let pixelSize = CGSize(
            width: bounds.width * scale,
            height: bounds.height * scale
        )
        guard pixelSize.width > 0, pixelSize.height > 0 else { return }

        let layer = forgeView.metalLayer
        layer.contentsScale = scale
        layer.drawableSize = pixelSize

        let width = UInt32(pixelSize.width)
        let height = UInt32(pixelSize.height)

        if handle == nil {
            handle = forgekit_init(
                Unmanaged.passUnretained(layer).toOpaque(),
                width,
                height,
                Float(scale)
            )
            guard handle != nil else {
                initFailed = true
                displayLink?.invalidate()
                displayLink = nil
                NSLog("ForgeKit: GPU init failed — rendering disabled for this session")
                return
            }
            startDisplayLink()
        } else if pixelSize != lastDrawableSize {
            forgekit_resize(handle, width, height, Float(scale))
        }
        lastDrawableSize = pixelSize
    }

    private func startDisplayLink() {
        guard displayLink == nil else { return }
        let link = CADisplayLink(target: self, selector: #selector(renderFrame))
        link.add(to: .main, forMode: .common)
        displayLink = link
    }

    @objc private func renderFrame() {
        guard let handle else { return }
        forgekit_render_frame(handle)
    }

    @objc private func appWillResignActive() {
        displayLink?.isPaused = true
        if let handle { forgekit_pause(handle) }
    }

    @objc private func appDidBecomeActive() {
        if let handle { forgekit_resume(handle) }
        displayLink?.isPaused = false
    }

    deinit {
        displayLink?.invalidate()
        displayLink = nil
        NotificationCenter.default.removeObserver(self)
        if let handle {
            forgekit_destroy(handle)
        }
    }
}
