import UIKit
import QuartzCore

// Generated by `forgekit create` (spec Phase 3 §10.2). Hosts the ForgeKit
// render surface and drives it from a `CADisplayLink`, bridging UIKit's
// view/scene lifecycle (touch + text input) to the `forgekit_*` FFI calls.
//
// Contract enforced here (mirrored on the Rust side, belt-and-suspenders):
//   - `forgekit_init` is called exactly once, on the first valid layout;
//     every later size change goes through `forgekit_resize`.
//   - The display link (and the native renderer via `forgekit_pause`) is
//     paused when the app resigns active — submitting Metal work from a
//     backgrounded app can get the process killed.
//   - `forgekit_destroy` reclaims the native handle before the view is gone.
final class ForgeKitViewController: UIViewController {
    private var forgeView: ForgeKitView { view as! ForgeKitView }
    private var displayLink: CADisplayLink?
    private var handle: UnsafeMutableRawPointer?
    private var lastDrawableSize: CGSize = .zero
    // `forgekit_init` failure is session-permanent by design: the shell has
    // no transient failure mode (the one observed cause, a simulator GPU
    // missing a required Metal feature, cannot change mid-process). Once
    // `forgekit_init` returns nil, latch here so every later UIKit layout
    // pass (rotation, keyboard, autolayout churn, ...) is a no-op instead of
    // re-running a doomed synchronous `pollster::block_on` adapter/device
    // request and re-logging the failure. If a transient failure mode is
    // ever introduced on the Rust side, this is the place to revisit.
    private var initFailed = false

    /// A deep link delivered (by `SceneDelegate`) before `forgekit_init` has
    /// returned a handle — cold-start links routinely arrive this early,
    /// since `connectionOptions.urlContexts` is available in
    /// `scene(_:willConnectTo:options:)`, well before the first
    /// `viewDidLayoutSubviews` triggers `updateSurface()`/`forgekit_init`.
    /// Held here and flushed the moment `handle` becomes non-nil (task 07's
    /// queue-until-handle-ready contract, mirroring Android's
    /// `ForgeKitSurfaceView.pendingDeepLink`).
    private var pendingDeepLink: String?

    override func loadView() {
        view = ForgeKitView()
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        let scale = UIScreen.main.scale
        view.contentScaleFactor = scale
        forgeView.metalLayer.contentsScale = scale

        // Bridge the view's raw touch callbacks into the native tree (spec §9).
        // `location` is already logical points, so it is passed through without
        // any scale division (contrast Android's physical-pixel touch path).
        forgeView.onTouch = { [weak self] phase, location in
            guard let self, let handle = self.handle else { return }
            forgekit_dispatch_touch(handle, phase, Float(location.x), Float(location.y))
            // A touch may have focused/blurred an editable widget; reconcile the
            // keyboard/first-responder state with what the tree now reports.
            self.syncImeFocus()
        }

        // Bridge the view's UITextInput mirror into the native IME (spec §9): push
        // the whole editing value, then read back the reconciled state as JSON.
        forgeView.imeRoundTrip = { [weak self] text, selBase, selExt, compBase, compExt in
            guard let self, let handle = self.handle else { return nil }
            text.withCString { cstr in
                forgekit_ime_apply(
                    handle, cstr, Int32(selBase), Int32(selExt), Int32(compBase), Int32(compExt))
            }
            return self.fetchImeState()
        }

        NotificationCenter.default.addObserver(
            self,
            selector: #selector(appWillResignActive),
            name: UIApplication.willResignActiveNotification,
            object: nil
        )
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(appDidBecomeActive),
            name: UIApplication.didBecomeActiveNotification,
            object: nil
        )
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        updateSurface()
    }

    override func viewWillTransition(
        to size: CGSize,
        with coordinator: UIViewControllerTransitionCoordinator
    ) {
        super.viewWillTransition(to: size, with: coordinator)
        coordinator.animate(alongsideTransition: nil) { [weak self] _ in
            self?.updateSurface()
        }
    }

    /// Sizes the drawable to the view's pixel bounds and either creates the
    /// native renderer (first valid layout) or resizes it (thereafter).
    private func updateSurface() {
        guard !initFailed else { return }

        let scale = view.contentScaleFactor
        let bounds = view.bounds.size
        let pixelSize = CGSize(
            width: bounds.width * scale,
            height: bounds.height * scale
        )
        guard pixelSize.width > 0, pixelSize.height > 0 else { return }

        let layer = forgeView.metalLayer
        layer.contentsScale = scale
        layer.drawableSize = pixelSize

        let width = UInt32(pixelSize.width)
        let height = UInt32(pixelSize.height)

        if handle == nil {
            handle = forgekit_init(
                Unmanaged.passUnretained(layer).toOpaque(),
                width,
                height,
                Float(scale)
            )
            guard handle != nil else {
                initFailed = true
                displayLink?.invalidate()
                displayLink = nil
                NSLog("ForgeKit: GPU init failed — rendering disabled for this session")
                return
            }
            // Seed the theme's brightness from the platform's current
            // appearance before the first frame (task 08); live changes
            // arrive later via `traitCollectionDidChange`.
            forgekit_set_appearance(handle, traitCollection.userInterfaceStyle == .dark ? 1 : 0)
            startDisplayLink()
            // Flush a deep link that arrived before this handle existed
            // (see `pendingDeepLink`'s doc comment) — a cold-start link
            // must not be silently dropped just because it raced ahead of
            // `forgekit_init`.
            if let pending = pendingDeepLink {
                pendingDeepLink = nil
                deliverDeepLink(pending)
            }
        } else if pixelSize != lastDrawableSize {
            forgekit_resize(handle, width, height, Float(scale))
        }
        lastDrawableSize = pixelSize
    }

    // MARK: - Deep links (task 07)

    /// Deliver a platform deep link — called by `SceneDelegate` for both the
    /// cold-start link (`connectionOptions.urlContexts`, in
    /// `scene(_:willConnectTo:options:)`) and a running-app link
    /// (`scene(_:openURLContexts:)`) uniformly. Queues until `forgekit_init`
    /// has returned a handle if the link arrives first (see
    /// `pendingDeepLink`).
    func handleDeepLink(_ url: URL) {
        deliverDeepLink(url.absoluteString)
    }

    private func deliverDeepLink(_ url: String) {
        guard let handle else {
            pendingDeepLink = url
            return
        }
        url.withCString { cstr in
            forgekit_on_deep_link(handle, cstr)
        }
    }

    // MARK: - Text input (spec §9, Phase 4B)

    /// Read the focused field's IME surface from Rust as a parsed dictionary,
    /// freeing the returned C string (the Rust side transfers ownership).
    private func fetchImeState() -> [String: Any]? {
        guard let handle, let raw = forgekit_ime_state_json(handle) else { return nil }
        defer { forgekit_string_free(raw) }
        let data = Data(bytes: raw, count: strlen(raw))
        return (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
    }

    /// Reconcile keyboard/first-responder state with the tree: a newly-focused
    /// field seeds the mirror and shows the keyboard; a blurred field resigns.
    private func syncImeFocus() {
        guard let state = fetchImeState() else { return }
        let active = (state["active"] as? Bool) ?? false
        if active {
            if !forgeView.isFirstResponder {
                forgeView.seedMirror(from: state)
                forgeView.becomeFirstResponder()
            }
        } else if forgeView.isFirstResponder {
            forgeView.resignFirstResponder()
        }
    }

    private func startDisplayLink() {
        guard displayLink == nil else { return }
        let link = CADisplayLink(target: self, selector: #selector(renderFrame(_:)))
        link.add(to: .main, forMode: .common)
        displayLink = link
    }

    @objc private func renderFrame(_ link: CADisplayLink) {
        guard let handle else { return }
        // `link.timestamp` is a `CFTimeInterval` (seconds); the Rust side wants
        // the shell-owned monotonic frame clock in nanoseconds (spec §8). The
        // f64 * 1e9 multiply/round is tolerated here because Rust only ever
        // *differences* two FrameTimes (never reads one as an absolute
        // wall-clock value) — see forgekit-core::anim's FrameTime contract.
        // Don't "fix" this by reordering the multiply/cast without reading
        // that contract first.
        forgekit_render_frame(handle, UInt64(link.timestamp * 1_000_000_000))
    }

    @objc private func appWillResignActive() {
        displayLink?.isPaused = true
        if let handle { forgekit_pause(handle) }
    }

    @objc private func appDidBecomeActive() {
        if let handle { forgekit_resume(handle) }
        displayLink?.isPaused = false
    }

    /// The platform's light/dark appearance preference changed (task 08) —
    /// re-seed the theme's brightness.
    override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
        super.traitCollectionDidChange(previousTraitCollection)
        guard let handle else { return }
        forgekit_set_appearance(handle, traitCollection.userInterfaceStyle == .dark ? 1 : 0)
    }

    deinit {
        displayLink?.invalidate()
        displayLink = nil
        NotificationCenter.default.removeObserver(self)
        if let handle {
            forgekit_destroy(handle)
        }
    }
}
