import UIKit
import QuartzCore

// Generated by `forgekit create` (spec Phase 3 §10.2). A UIView whose backing
// layer is a `CAMetalLayer`, so ForgeKit's wgpu/Metal renderer can draw
// directly into it (the layer pointer is handed to `forgekit_init`).
final class ForgeKitView: UIView {
    override class var layerClass: AnyClass {
        return CAMetalLayer.self
    }

    var metalLayer: CAMetalLayer {
        // Safe: `layerClass` guarantees the backing layer is a CAMetalLayer.
        return layer as! CAMetalLayer
    }
}
