import UIKit
import QuartzCore

// Generated by `forgekit create` (spec Phase 3 §10.2). Hosts the ForgeKit
// render surface and drives it from a `CADisplayLink`, bridging UIKit's
// view/scene lifecycle to the six `forgekit_*` FFI calls.
//
// Contract enforced here (mirrored on the Rust side, belt-and-suspenders):
//   - `forgekit_init` is called exactly once, on the first valid layout;
//     every later size change goes through `forgekit_resize`.
//   - The display link (and the native renderer via `forgekit_pause`) is
//     paused when the app resigns active — submitting Metal work from a
//     backgrounded app can get the process killed.
//   - `forgekit_destroy` reclaims the native handle before the view is gone.
final class ForgeKitViewController: UIViewController {
    private var forgeView: ForgeKitView { view as! ForgeKitView }
    private var displayLink: CADisplayLink?
    private var handle: UnsafeMutableRawPointer?
    private var lastDrawableSize: CGSize = .zero

    override func loadView() {
        view = ForgeKitView()
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        let scale = UIScreen.main.scale
        view.contentScaleFactor = scale
        forgeView.metalLayer.contentsScale = scale

        NotificationCenter.default.addObserver(
            self,
            selector: #selector(appWillResignActive),
            name: UIApplication.willResignActiveNotification,
            object: nil
        )
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(appDidBecomeActive),
            name: UIApplication.didBecomeActiveNotification,
            object: nil
        )
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        updateSurface()
    }

    override func viewWillTransition(
        to size: CGSize,
        with coordinator: UIViewControllerTransitionCoordinator
    ) {
        super.viewWillTransition(to: size, with: coordinator)
        coordinator.animate(alongsideTransition: nil) { [weak self] _ in
            self?.updateSurface()
        }
    }

    /// Sizes the drawable to the view's pixel bounds and either creates the
    /// native renderer (first valid layout) or resizes it (thereafter).
    private func updateSurface() {
        let scale = view.contentScaleFactor
        let bounds = view.bounds.size
        let pixelSize = CGSize(
            width: bounds.width * scale,
            height: bounds.height * scale
        )
        guard pixelSize.width > 0, pixelSize.height > 0 else { return }

        let layer = forgeView.metalLayer
        layer.contentsScale = scale
        layer.drawableSize = pixelSize

        let width = UInt32(pixelSize.width)
        let height = UInt32(pixelSize.height)

        if handle == nil {
            handle = forgekit_init(
                Unmanaged.passUnretained(layer).toOpaque(),
                width,
                height,
                Float(scale)
            )
            startDisplayLink()
        } else if pixelSize != lastDrawableSize {
            forgekit_resize(handle, width, height, Float(scale))
        }
        lastDrawableSize = pixelSize
    }

    private func startDisplayLink() {
        guard displayLink == nil else { return }
        let link = CADisplayLink(target: self, selector: #selector(renderFrame))
        link.add(to: .main, forMode: .common)
        displayLink = link
    }

    @objc private func renderFrame() {
        guard let handle else { return }
        forgekit_render_frame(handle)
    }

    @objc private func appWillResignActive() {
        displayLink?.isPaused = true
        if let handle { forgekit_pause(handle) }
    }

    @objc private func appDidBecomeActive() {
        if let handle { forgekit_resume(handle) }
        displayLink?.isPaused = false
    }

    deinit {
        displayLink?.invalidate()
        displayLink = nil
        NotificationCenter.default.removeObserver(self)
        if let handle {
            forgekit_destroy(handle)
        }
    }
}
