import UIKit

// Generated by `frust create` (spec Phase 3 §10.2). Roots the window at
// the Frust render surface's view controller.
//
// Deep links (task 07): this app is scene-based (see Info.plist's
// `UIApplicationSceneManifest`), so — per Apple's documented deep-link
// contract for scene apps — a cold-start link arrives as
// `connectionOptions.urlContexts` here, and a running-app link arrives via
// `scene(_:openURLContexts:)` below; `AppDelegate.application(_:open:)` is
// NOT called for a scene-based app and is therefore not used for this.
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
    var window: UIWindow?

    func scene(
        _ scene: UIScene,
        willConnectTo session: UISceneSession,
        options connectionOptions: UIScene.ConnectionOptions
    ) {
        guard let windowScene = scene as? UIWindowScene else { return }
        let window = UIWindow(windowScene: windowScene)
        let controller = FrustViewController()
        window.rootViewController = controller
        self.window = window
        window.makeKeyAndVisible()

        // Cold-start deep link, if the app was launched via a URL. Queued
        // by the controller until `frust_init` has a handle (it hasn't
        // run yet at this point — see `FrustViewController.pendingDeepLink`).
        if let url = connectionOptions.urlContexts.first?.url {
            controller.handleDeepLink(url)
        }
    }

    /// A running app's deep link (the app was already foregrounded/
    /// backgrounded, not launched fresh). First URL only — this app opens a
    /// single scene/window, so `URLContexts` has at most one entry in
    /// practice.
    func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
        guard let url = URLContexts.first?.url,
            let controller = window?.rootViewController as? FrustViewController
        else { return }
        controller.handleDeepLink(url)
    }
}
