import UIKit

// Generated by `forgekit create` (spec Phase 3 §10.2). Roots the window at
// the ForgeKit render surface's view controller.
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
    var window: UIWindow?

    func scene(
        _ scene: UIScene,
        willConnectTo session: UISceneSession,
        options connectionOptions: UIScene.ConnectionOptions
    ) {
        guard let windowScene = scene as? UIWindowScene else { return }
        let window = UIWindow(windowScene: windowScene)
        window.rootViewController = ForgeKitViewController()
        self.window = window
        window.makeKeyAndVisible()
    }
}
