# Generated by `frust create` (Phase 7 task 12 — release packaging).
# Applied on top of `proguard-android-optimize.txt` (AGP's default R8 rule
# set, still handles everything not covered below: Android framework
# callbacks, `Parcelable`/`Serializable`, enum `values()`/`valueOf`, etc.).
# Both build.gradle.kts's `release` and `profile` build types wire these in
# via `proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"),
# "proguard-rules.pro")`.

# Framework keep rules for `dev.frust.**` (JNI-referenced) and
# `dev.accesskit.android.**` (classloader-referenced) are no longer listed
# here — they now arrive via the `frust-embedding` library module's own
# `consumer-rules.pro`, merged automatically by AGP's `consumerProguardFiles`.
# Do not re-add them here; add app-specific rules below instead.
#
# `dev.frust.DemoStreamFactory` (this catalog's own Mode B demo factory,
# `dev/frust/DemoStreamFactory.kt`, resolved by name from `FrustViewHost` —
# see docs/CODE_STANDARDS.md's Naming Conventions) is a `dev.frust.**` class
# too, even though it's app-authored rather than `:frust-embedding`-owned, so
# the module's `-keep class dev.frust.** { *; }` consumer rule (broad by
# design — see task 07) already protects it. No extra rule needed here.
