//! The shared mock dataset the whole Huddle app renders (PLAN.md's
//! "All data mocked/static").
//!
//! This is a **hub file finalized in the skeleton (task 10)** — Phase C screen
//! tasks READ this dataset through the accessor functions below but never edit
//! this module (see `src/README-phase-c.md`). It is plain `&'static`/const data
//! plus accessor `fn`s that materialize owned [`User`]/[`Channel`]/[`Dm`]/
//! [`Message`]/[`ActivityItem`] values; there is **no reactive state here** —
//! controllers (Phase C) own the signals, seeding them from these accessors.
//!
//! # Shape (per PLAN)
//!
//! - 10 [`users`] (name, initials, [`UserStatus`]).
//! - 6 [`channels`], one of them [`Channel::private`].
//! - 9 [`dms`] (each a 1:1 conversation with a [`User`]) — one of them
//!   (`dm-9`) deliberately carries no messages, so the channel feed's
//!   empty-conversation state ("No messages yet — say hi") has a real
//!   destination (task 22's empty-states audit; the frozen-hub rule is lifted
//!   for this one addition).
//! - ~40 [`messages`] spread across the channels (varied: text lengths, a
//!   link, a file stub, reactions).
//! - one 120-message channel ([`FIREHOSE_ID`], `#firehose`) for pagination,
//!   generated by [`firehose_messages`].
//! - an [`activity`] feed derived from the messages that mention the current
//!   user ([`CURRENT_USER_ID`]).

/// A member's presence state (the status dot in avatars and roster rows).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum UserStatus {
    /// Available.
    Online,
    /// Idle / away.
    Away,
    /// Do not disturb.
    Dnd,
}

impl UserStatus {
    /// A short human label for the status.
    pub fn label(self) -> &'static str {
        match self {
            UserStatus::Online => "Online",
            UserStatus::Away => "Away",
            UserStatus::Dnd => "Do not disturb",
        }
    }
}

/// A workspace member.
#[derive(Clone, Copy, Debug)]
pub struct User {
    /// Stable numeric id (used in `/user/:id` deep links).
    pub id: u32,
    /// Display name.
    pub name: &'static str,
    /// Two-letter initials for the avatar escape-hatch paint.
    pub initials: &'static str,
    /// Presence.
    pub status: UserStatus,
}

/// A channel (a named, possibly private, multi-member conversation).
#[derive(Clone, Copy, Debug)]
pub struct Channel {
    /// Stable string id (used in `/channel/:id`).
    pub id: &'static str,
    /// Display name (without the leading `#`).
    pub name: &'static str,
    /// Whether the channel is private (rendered with a lock icon).
    pub private: bool,
    /// One-line channel topic.
    pub topic: &'static str,
}

/// A direct message conversation (1:1 with a [`User`]).
#[derive(Clone, Copy, Debug)]
pub struct Dm {
    /// Stable string id (used in `/channel/:id`, DMs route through the same
    /// feed screen as channels).
    pub id: &'static str,
    /// The other participant.
    pub user_id: u32,
    /// A short preview of the latest message (roster subtitle).
    pub preview: &'static str,
}

/// The body of a [`Message`] — text, a link preview stub, or a file stub.
#[derive(Clone, Copy, Debug)]
pub enum MessageBody {
    /// Plain text (may include an `@mention`).
    Text(&'static str),
    /// A link with a preview title (a `Card`-rendered link preview in Phase C).
    Link {
        /// The URL.
        url: &'static str,
        /// A human title for the preview card.
        title: &'static str,
    },
    /// A file attachment stub (no real bytes — a non-goal per PLAN).
    File {
        /// The file name.
        name: &'static str,
        /// A human size string (e.g. `"2.4 MB"`).
        size: &'static str,
    },
}

/// A single emoji reaction with a count.
#[derive(Clone, Copy, Debug)]
pub struct Reaction {
    /// The emoji (color-glyph rendering is a Phase A/C item).
    pub emoji: &'static str,
    /// How many members reacted.
    pub count: u32,
}

/// A message in a channel or DM.
#[derive(Clone, Copy, Debug)]
pub struct Message {
    /// Stable numeric id.
    pub id: u32,
    /// The channel or DM this message belongs to.
    pub channel_id: &'static str,
    /// The author.
    pub author_id: u32,
    /// The message body.
    pub body: MessageBody,
    /// Reactions attached to the message.
    pub reactions: &'static [Reaction],
}

/// An item in the Activity tab — a mention derived from the message stream.
#[derive(Clone, Copy, Debug)]
pub struct ActivityItem {
    /// The message that produced this activity item.
    pub message_id: u32,
    /// The channel the mention happened in.
    pub channel_id: &'static str,
    /// Who mentioned the current user.
    pub author_id: u32,
    /// The mention text.
    pub text: &'static str,
}

/// The "me" user whose mentions drive the [`activity`] feed.
pub const CURRENT_USER_ID: u32 = 1;

/// The id of the 120-message pagination channel (`#firehose`).
pub const FIREHOSE_ID: &str = "firehose";

/// How many messages the [`FIREHOSE_ID`] channel holds (the pagination target).
pub const FIREHOSE_COUNT: u32 = 120;

// ---------------------------------------------------------------------------
// Static tables
// ---------------------------------------------------------------------------

const USERS: [User; 10] = [
    User {
        id: 1,
        name: "Ada Lovelace",
        initials: "AL",
        status: UserStatus::Online,
    },
    User {
        id: 2,
        name: "Grace Hopper",
        initials: "GH",
        status: UserStatus::Online,
    },
    User {
        id: 3,
        name: "Alan Turing",
        initials: "AT",
        status: UserStatus::Away,
    },
    User {
        id: 4,
        name: "Katherine Johnson",
        initials: "KJ",
        status: UserStatus::Dnd,
    },
    User {
        id: 5,
        name: "Linus Torvalds",
        initials: "LT",
        status: UserStatus::Online,
    },
    User {
        id: 6,
        name: "Margaret Hamilton",
        initials: "MH",
        status: UserStatus::Away,
    },
    User {
        id: 7,
        name: "Dennis Ritchie",
        initials: "DR",
        status: UserStatus::Online,
    },
    User {
        id: 8,
        name: "Barbara Liskov",
        initials: "BL",
        status: UserStatus::Dnd,
    },
    User {
        id: 9,
        name: "Ken Thompson",
        initials: "KT",
        status: UserStatus::Away,
    },
    User {
        id: 10,
        name: "Radia Perlman",
        initials: "RP",
        status: UserStatus::Online,
    },
];

const CHANNELS: [Channel; 6] = [
    Channel {
        id: "general",
        name: "general",
        private: false,
        topic: "Company-wide announcements",
    },
    Channel {
        id: "engineering",
        name: "engineering",
        private: false,
        topic: "Builds, bugs, and design",
    },
    Channel {
        id: "design",
        name: "design",
        private: false,
        topic: "Pixels and prototypes",
    },
    Channel {
        id: "random",
        name: "random",
        private: false,
        topic: "Off-topic and watercooler",
    },
    Channel {
        id: "leadership",
        name: "leadership",
        private: true,
        topic: "Private leadership sync",
    },
    Channel {
        id: FIREHOSE_ID,
        name: "firehose",
        private: false,
        topic: "Everything, all at once",
    },
];

const DMS: [Dm; 9] = [
    Dm {
        id: "dm-2",
        user_id: 2,
        preview: "Ship it when you're ready.",
    },
    Dm {
        id: "dm-3",
        user_id: 3,
        preview: "The proof checks out.",
    },
    Dm {
        id: "dm-4",
        user_id: 4,
        preview: "Numbers look good.",
    },
    Dm {
        id: "dm-5",
        user_id: 5,
        preview: "Merged to main.",
    },
    Dm {
        id: "dm-6",
        user_id: 6,
        preview: "Guidance is green.",
    },
    Dm {
        id: "dm-7",
        user_id: 7,
        preview: "Kept it simple.",
    },
    Dm {
        id: "dm-8",
        user_id: 8,
        preview: "Substitution holds.",
    },
    Dm {
        id: "dm-10",
        user_id: 10,
        preview: "Routes converged.",
    },
    // An empty DM: no messages in `MESSAGES`, so `messages_for("dm-9")` is
    // empty and the feed shows its empty-conversation state (task 22).
    Dm {
        id: "dm-9",
        user_id: 9,
        preview: "No messages yet",
    },
];

const NO_REACTIONS: &[Reaction] = &[];
const THUMBS: &[Reaction] = &[Reaction {
    emoji: "\u{1F44D}",
    count: 3,
}];
const PARTY: &[Reaction] = &[
    Reaction {
        emoji: "\u{1F389}",
        count: 5,
    },
    Reaction {
        emoji: "\u{1F680}",
        count: 2,
    },
];

/// The ~40 authored channel messages (the firehose's 120 are generated
/// separately — see [`firehose_messages`]).
const MESSAGES: [Message; 40] = [
    // general
    Message {
        id: 1,
        channel_id: "general",
        author_id: 2,
        body: MessageBody::Text("Morning, everyone!"),
        reactions: THUMBS,
    },
    Message {
        id: 2,
        channel_id: "general",
        author_id: 5,
        body: MessageBody::Text("@Ada Lovelace can you review the release notes?"),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 3,
        channel_id: "general",
        author_id: 4,
        body: MessageBody::Text("Reminder: all-hands at 3pm."),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 4,
        channel_id: "general",
        author_id: 7,
        body: MessageBody::Link {
            url: "https://frust.dev/blog",
            title: "Frust 1.0 is here",
        },
        reactions: PARTY,
    },
    Message {
        id: 5,
        channel_id: "general",
        author_id: 6,
        body: MessageBody::Text("Congrats to the whole team on the launch \u{1F389}"),
        reactions: PARTY,
    },
    Message {
        id: 6,
        channel_id: "general",
        author_id: 10,
        body: MessageBody::Text("Short one."),
        reactions: NO_REACTIONS,
    },
    // engineering
    Message {
        id: 7,
        channel_id: "engineering",
        author_id: 5,
        body: MessageBody::Text("The new layout pass is 20% faster on cold start."),
        reactions: THUMBS,
    },
    Message {
        id: 8,
        channel_id: "engineering",
        author_id: 3,
        body: MessageBody::Text("Nice. Did the retained-tree diff change?"),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 9,
        channel_id: "engineering",
        author_id: 5,
        body: MessageBody::Text("Only the reconciler's keyed path."),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 10,
        channel_id: "engineering",
        author_id: 8,
        body: MessageBody::Text("@Ada Lovelace the invariant you flagged is fixed."),
        reactions: THUMBS,
    },
    Message {
        id: 11,
        channel_id: "engineering",
        author_id: 7,
        body: MessageBody::File {
            name: "trace-profile.json",
            size: "2.4 MB",
        },
        reactions: NO_REACTIONS,
    },
    Message {
        id: 12,
        channel_id: "engineering",
        author_id: 9,
        body: MessageBody::Text(
            "Here's a longer one so the bubble wraps across multiple lines and we can see how the feed handles a genuinely paragraph-sized message body in the channel view.",
        ),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 13,
        channel_id: "engineering",
        author_id: 2,
        body: MessageBody::Text("LGTM."),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 14,
        channel_id: "engineering",
        author_id: 3,
        body: MessageBody::Link {
            url: "https://frust.dev/spec",
            title: "The Frust spec",
        },
        reactions: NO_REACTIONS,
    },
    // design
    Message {
        id: 15,
        channel_id: "design",
        author_id: 6,
        body: MessageBody::Text("New color roles land next sprint."),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 16,
        channel_id: "design",
        author_id: 4,
        body: MessageBody::Text("Can we get a dark-mode audit?"),
        reactions: THUMBS,
    },
    Message {
        id: 17,
        channel_id: "design",
        author_id: 6,
        body: MessageBody::File {
            name: "tokens.fig",
            size: "18 MB",
        },
        reactions: NO_REACTIONS,
    },
    Message {
        id: 18,
        channel_id: "design",
        author_id: 10,
        body: MessageBody::Text("Love the new elevation scale."),
        reactions: PARTY,
    },
    Message {
        id: 19,
        channel_id: "design",
        author_id: 8,
        body: MessageBody::Text("@Ada Lovelace thoughts on the type scale?"),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 20,
        channel_id: "design",
        author_id: 6,
        body: MessageBody::Text("k"),
        reactions: NO_REACTIONS,
    },
    // random
    Message {
        id: 21,
        channel_id: "random",
        author_id: 9,
        body: MessageBody::Text("Coffee?"),
        reactions: THUMBS,
    },
    Message {
        id: 22,
        channel_id: "random",
        author_id: 7,
        body: MessageBody::Text("Always."),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 23,
        channel_id: "random",
        author_id: 2,
        body: MessageBody::Link {
            url: "https://example.com/cat",
            title: "A very good cat",
        },
        reactions: PARTY,
    },
    Message {
        id: 24,
        channel_id: "random",
        author_id: 5,
        body: MessageBody::Text("lol"),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 25,
        channel_id: "random",
        author_id: 10,
        body: MessageBody::Text("Friday lunch spot?"),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 26,
        channel_id: "random",
        author_id: 3,
        body: MessageBody::Text("The place with the good ramen."),
        reactions: THUMBS,
    },
    // leadership (private)
    Message {
        id: 27,
        channel_id: "leadership",
        author_id: 4,
        body: MessageBody::Text("Q3 planning doc is ready for review."),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 28,
        channel_id: "leadership",
        author_id: 6,
        body: MessageBody::Text("Adding headcount notes."),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 29,
        channel_id: "leadership",
        author_id: 4,
        body: MessageBody::Link {
            url: "https://frust.dev/roadmap",
            title: "Roadmap Q3",
        },
        reactions: NO_REACTIONS,
    },
    Message {
        id: 30,
        channel_id: "leadership",
        author_id: 8,
        body: MessageBody::Text("Approved."),
        reactions: THUMBS,
    },
    // DMs (routed through the same feed screen)
    Message {
        id: 31,
        channel_id: "dm-2",
        author_id: 2,
        body: MessageBody::Text("Ship it when you're ready."),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 32,
        channel_id: "dm-2",
        author_id: 1,
        body: MessageBody::Text("On it."),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 33,
        channel_id: "dm-3",
        author_id: 3,
        body: MessageBody::Text("The proof checks out."),
        reactions: THUMBS,
    },
    Message {
        id: 34,
        channel_id: "dm-5",
        author_id: 5,
        body: MessageBody::Text("Merged to main."),
        reactions: PARTY,
    },
    Message {
        id: 35,
        channel_id: "dm-5",
        author_id: 1,
        body: MessageBody::Text("Thanks!"),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 36,
        channel_id: "dm-7",
        author_id: 7,
        body: MessageBody::Text("Kept it simple."),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 37,
        channel_id: "dm-8",
        author_id: 8,
        body: MessageBody::Text("Substitution holds."),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 38,
        channel_id: "dm-10",
        author_id: 10,
        body: MessageBody::Text("Routes converged."),
        reactions: THUMBS,
    },
    Message {
        id: 39,
        channel_id: "dm-4",
        author_id: 4,
        body: MessageBody::Text("Numbers look good."),
        reactions: NO_REACTIONS,
    },
    Message {
        id: 40,
        channel_id: "dm-6",
        author_id: 6,
        body: MessageBody::Text("Guidance is green."),
        reactions: NO_REACTIONS,
    },
];

/// The rotating text bodies the [`firehose_messages`] generator cycles through.
const FIREHOSE_BODIES: [&str; 6] = [
    "deploy started",
    "deploy finished",
    "health check passed",
    "cache warmed",
    "metrics flushed",
    "@Ada Lovelace nightly build is green",
];

// ---------------------------------------------------------------------------
// Accessors (materialize owned values — no reactive state)
// ---------------------------------------------------------------------------

/// All 10 workspace members, in roster order.
pub fn users() -> Vec<User> {
    USERS.to_vec()
}

/// Look up a member by id.
pub fn user(id: u32) -> Option<User> {
    USERS.iter().copied().find(|u| u.id == id)
}

/// All 6 channels (one of which is [`Channel::private`]).
pub fn channels() -> Vec<Channel> {
    CHANNELS.to_vec()
}

/// Look up a channel by id.
pub fn channel(id: &str) -> Option<Channel> {
    CHANNELS.iter().copied().find(|c| c.id == id)
}

/// All 9 direct-message conversations (one, `dm-9`, carries no messages).
pub fn dms() -> Vec<Dm> {
    DMS.to_vec()
}

/// Every authored channel/DM message (the 40 static ones; the firehose's 120
/// are materialized on demand by [`firehose_messages`]/[`messages_for`]).
pub fn messages() -> Vec<Message> {
    MESSAGES.to_vec()
}

/// All messages in a given channel or DM, oldest-first. For [`FIREHOSE_ID`]
/// this generates the 120-message pagination stream.
pub fn messages_for(channel_id: &str) -> Vec<Message> {
    if channel_id == FIREHOSE_ID {
        return firehose_messages();
    }
    MESSAGES
        .iter()
        .copied()
        .filter(|m| m.channel_id == channel_id)
        .collect()
}

/// The 120-message `#firehose` channel, generated for the pagination demo.
///
/// Ids start at 1000 so they never collide with the authored [`MESSAGES`].
pub fn firehose_messages() -> Vec<Message> {
    (0..FIREHOSE_COUNT)
        .map(|i| {
            let author = USERS[(i as usize) % USERS.len()].id;
            let body = FIREHOSE_BODIES[(i as usize) % FIREHOSE_BODIES.len()];
            Message {
                id: 1000 + i,
                channel_id: FIREHOSE_ID,
                author_id: author,
                body: MessageBody::Text(body),
                reactions: NO_REACTIONS,
            }
        })
        .collect()
}

/// The Activity feed: every message (authored channels + firehose) whose text
/// body mentions the current user ([`CURRENT_USER_ID`]).
pub fn activity() -> Vec<ActivityItem> {
    let me = user(CURRENT_USER_ID).map(|u| u.name).unwrap_or_default();
    let mention = format!("@{me}");
    messages()
        .into_iter()
        .chain(firehose_messages())
        .filter_map(|m| match m.body {
            MessageBody::Text(text) if text.contains(&mention) => Some(ActivityItem {
                message_id: m.id,
                channel_id: m.channel_id,
                author_id: m.author_id,
                text,
            }),
            _ => None,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dataset_matches_the_plan_shape() {
        assert_eq!(users().len(), 10, "10 users");
        assert_eq!(channels().len(), 6, "6 channels");
        assert_eq!(
            channels().iter().filter(|c| c.private).count(),
            1,
            "exactly one private channel",
        );
        assert_eq!(dms().len(), 9, "9 DMs (one an empty DM — task 22)");
        assert_eq!(messages().len(), 40, "~40 authored messages");
    }

    #[test]
    fn dm_9_is_the_empty_conversation() {
        assert!(
            dms().iter().any(|d| d.id == "dm-9"),
            "dm-9 is in the roster"
        );
        assert!(
            messages_for("dm-9").is_empty(),
            "dm-9 carries no messages (drives the empty-feed state — task 22)"
        );
    }

    #[test]
    fn firehose_channel_has_120_messages() {
        assert_eq!(firehose_messages().len(), FIREHOSE_COUNT as usize);
        assert_eq!(messages_for(FIREHOSE_ID).len(), 120);
    }

    #[test]
    fn every_message_and_dm_references_a_real_user_and_channel() {
        let channel_ids: Vec<&str> = channels().iter().map(|c| c.id).collect();
        let dm_ids: Vec<&str> = dms().iter().map(|d| d.id).collect();
        for m in messages() {
            assert!(user(m.author_id).is_some(), "author {} exists", m.author_id);
            let known = channel_ids.contains(&m.channel_id) || dm_ids.contains(&m.channel_id);
            assert!(
                known,
                "message channel {} is a real channel or DM",
                m.channel_id
            );
        }
        for d in dms() {
            assert!(user(d.user_id).is_some(), "DM peer {} exists", d.user_id);
        }
    }

    #[test]
    fn activity_feed_is_derived_from_mentions() {
        let feed = activity();
        assert!(
            !feed.is_empty(),
            "the current user is mentioned at least once"
        );
        let me = user(CURRENT_USER_ID).unwrap().name;
        let mention = format!("@{me}");
        for item in feed {
            assert!(
                item.text.contains(&mention),
                "each activity item is a mention"
            );
        }
    }
}
