import UIKit
import QuartzCore

// Generated by `frust create` (spec Phase 3 §10.2). Hosts the Frust
// render surface and drives it from a `CADisplayLink`, bridging UIKit's
// view/scene lifecycle (touch + text input) to the `frust_*` FFI calls.
//
// Contract enforced here (mirrored on the Rust side, belt-and-suspenders):
//   - `frust_init` is called exactly once, on the first valid layout;
//     every later size change goes through `frust_resize`.
//   - The display link (and the native renderer via `frust_pause`) is
//     paused when the app resigns active — submitting Metal work from a
//     backgrounded app can get the process killed.
//   - `frust_destroy` reclaims the native handle before the view is gone.
final class FrustViewController: UIViewController {
    // Shader-showcase immersive mode (example-local edit over the generated
    // baseline): hide the status bar and auto-hide the home indicator so
    // the shader owns the whole display; edge swipes still work.
    override var prefersStatusBarHidden: Bool { true }
    override var prefersHomeIndicatorAutoHidden: Bool { true }

    private var forgeView: FrustView { view as! FrustView }
    private var displayLink: CADisplayLink?
    private var handle: UnsafeMutableRawPointer?
    private var lastDrawableSize: CGSize = .zero
    // `frust_init` failure is session-permanent by design: the shell has
    // no transient failure mode (the one observed cause, a simulator GPU
    // missing a required Metal feature, cannot change mid-process). Once
    // `frust_init` returns nil, latch here so every later UIKit layout
    // pass (rotation, keyboard, autolayout churn, ...) is a no-op instead of
    // re-running a doomed synchronous `pollster::block_on` adapter/device
    // request and re-logging the failure. If a transient failure mode is
    // ever introduced on the Rust side, this is the place to revisit.
    private var initFailed = false

    /// A deep link delivered (by `SceneDelegate`) before `frust_init` has
    /// returned a handle — cold-start links routinely arrive this early,
    /// since `connectionOptions.urlContexts` is available in
    /// `scene(_:willConnectTo:options:)`, well before the first
    /// `viewDidLayoutSubviews` triggers `updateSurface()`/`frust_init`.
    /// Held here and flushed the moment `handle` becomes non-nil (task 07's
    /// queue-until-handle-ready contract, mirroring Android's
    /// `FrustSurfaceView.pendingDeepLink`).
    private var pendingDeepLink: String?

    /// The keyboard's current occlusion of this view's bottom edge, in
    /// logical points (device-parity task 08 — RESEARCH.md "Insets /
    /// SafeArea"; `FlutterViewController.mm:1593-1622` model). Computed as
    /// the intersection of the keyboard's end frame with `view.bounds`, so
    /// an undocked/split or off-screen keyboard doesn't over-report. Kept
    /// separate from `view.safeAreaInsets` (which UIKit does not include the
    /// keyboard in) so [pushInsets] can recombine both on every push.
    private var keyboardViewInsetBottom: CGFloat = 0

    override func loadView() {
        view = FrustView()
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        // Perf instrumentation (spec §14 phase 7.A task 09): marks
        // viewDidLoad's entry on the same console stream the Rust side's
        // `frust-perf startup ...`/`frust-perf frame ...` lines land
        // on (captured together via `simctl launch --console-pty`/Xcode),
        // so the app-launch-to-view-load gap is measurable from one stream
        // — mirrors the Android shell's `MainActivity.onCreate` log line
        // (task 08). Unconditional (not gated on FRUST_TRACE): this is
        // host-app Swift code the Rust `perf::enabled()` switch doesn't
        // reach, and a single log line at launch has no measurable cost.
        NSLog("frust-perf vc-load")
        let scale = UIScreen.main.scale
        view.contentScaleFactor = scale
        forgeView.metalLayer.contentsScale = scale

        // Bridge the view's raw touch callbacks into the native tree (spec §9).
        // `location` is already logical points, so it is passed through without
        // any scale division (contrast Android's physical-pixel touch path).
        forgeView.onTouch = { [weak self] phase, location in
            guard let self, let handle = self.handle else { return }
            frust_dispatch_touch(handle, phase, Float(location.x), Float(location.y))
            // A touch may have focused/blurred an editable widget; reconcile the
            // keyboard/first-responder state with what the tree now reports.
            self.syncImeFocus()
        }

        // Bridge the view's UITextInput mirror into the native IME (spec §9): push
        // the whole editing value, then read back the reconciled state as JSON.
        forgeView.imeRoundTrip = { [weak self] text, selBase, selExt, compBase, compExt in
            guard let self, let handle = self.handle else { return nil }
            text.withCString { cstr in
                frust_ime_apply(
                    handle, cstr, Int32(selBase), Int32(selExt), Int32(compBase), Int32(compExt))
            }
            return self.fetchImeState()
        }

        NotificationCenter.default.addObserver(
            self,
            selector: #selector(appWillResignActive),
            name: UIApplication.willResignActiveNotification,
            object: nil
        )
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(appDidBecomeActive),
            name: UIApplication.didBecomeActiveNotification,
            object: nil
        )

        // Insets (device-parity task 08 — RESEARCH.md "Insets / SafeArea"):
        // the keyboard's occlusion isn't part of `UIView.safeAreaInsets`, so
        // it's tracked separately via these notifications and recombined
        // with the current safe area on every `pushInsets()` call.
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(keyboardWillChangeFrame(_:)),
            name: UIResponder.keyboardWillChangeFrameNotification,
            object: nil
        )
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(keyboardWillHide(_:)),
            name: UIResponder.keyboardWillHideNotification,
            object: nil
        )
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        updateSurface()
    }

    /// SafeArea change (rotation, notch/Dynamic Island layout change, a
    /// sibling view controller's chrome) — task 08. Pushed unconditionally;
    /// `IosAppHandle::set_insets` (Rust side) no-op-guards an unchanged value.
    override func viewSafeAreaInsetsDidChange() {
        super.viewSafeAreaInsetsDidChange()
        pushInsets()
    }

    // MARK: - Insets (device-parity task 08 — RESEARCH.md "Insets / SafeArea")

    @objc private func keyboardWillChangeFrame(_ notification: Notification) {
        updateKeyboardInset(from: notification)
    }

    @objc private func keyboardWillHide(_ notification: Notification) {
        keyboardViewInsetBottom = 0
        pushInsets()
    }

    /// Computes the keyboard's occlusion of this view as the intersection of
    /// its end frame (delivered in screen/window coordinates) with
    /// `view.bounds`, converted into the view's coordinate space first
    /// (`FlutterViewController.mm:1593-1622`'s model — no animation
    /// interpolation in this v1 port).
    private func updateKeyboardInset(from notification: Notification) {
        guard
            let endFrameValue = notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey]
                as? NSValue
        else { return }
        let localFrame = view.convert(endFrameValue.cgRectValue, from: nil)
        let intersection = localFrame.intersection(view.bounds)
        keyboardViewInsetBottom = intersection.isNull ? 0 : intersection.height
        pushInsets()
    }

    /// Pushes the current `view_padding` (from `UIView.safeAreaInsets`) and
    /// `view_insets` (the keyboard occlusion tracked above) to
    /// `frust_set_insets`. Values are logical points — no scale
    /// multiplication (`frust_set_insets`'s contract mirrors
    /// `frust_dispatch_touch`'s no-scale asymmetry). A missing handle is
    /// a no-op; the next call after `frust_init` succeeds (see
    /// `updateSurface`) re-pushes the current state.
    private func pushInsets() {
        guard let handle else { return }
        let insets = view.safeAreaInsets
        frust_set_insets(
            handle,
            Float(insets.left), Float(insets.top), Float(insets.right), Float(insets.bottom),
            0, 0, 0, Float(keyboardViewInsetBottom)
        )
    }

    override func viewWillTransition(
        to size: CGSize,
        with coordinator: UIViewControllerTransitionCoordinator
    ) {
        super.viewWillTransition(to: size, with: coordinator)
        coordinator.animate(alongsideTransition: nil) { [weak self] _ in
            self?.updateSurface()
        }
    }

    /// Sizes the drawable to the view's pixel bounds and either creates the
    /// native renderer (first valid layout) or resizes it (thereafter).
    private func updateSurface() {
        guard !initFailed else { return }

        let scale = view.contentScaleFactor
        let bounds = view.bounds.size
        let pixelSize = CGSize(
            width: bounds.width * scale,
            height: bounds.height * scale
        )
        guard pixelSize.width > 0, pixelSize.height > 0 else { return }

        let layer = forgeView.metalLayer
        layer.contentsScale = scale
        layer.drawableSize = pixelSize

        let width = UInt32(pixelSize.width)
        let height = UInt32(pixelSize.height)

        if handle == nil {
            handle = frust_init(
                Unmanaged.passUnretained(layer).toOpaque(),
                width,
                height,
                Float(scale)
            )
            guard handle != nil else {
                initFailed = true
                displayLink?.invalidate()
                displayLink = nil
                NSLog("Frust: GPU init failed — rendering disabled for this session")
                return
            }
            // Attach the AccessKit adapter to this view (spec §9, phase 6d). The
            // adapter dynamically subclasses the FrustView to implement UIKit's
            // accessibility methods, so it needs the *view* pointer (not the
            // CAMetalLayer frust_init got). Do it here — once, before the view
            // is shown/focused — which is the window AccessKit's SubclassingAdapter
            // requires. Passed unretained: Rust holds the adapter only for the
            // handle's lifetime and restores the view's class on frust_destroy,
            // before this controller (and its view) is released.
            frust_init_accessibility(handle, Unmanaged.passUnretained(forgeView).toOpaque())
            // Seed the theme's brightness from the platform's current
            // appearance before the first frame (task 08); live changes
            // arrive later via `traitCollectionDidChange`.
            frust_set_appearance(handle, traitCollection.userInterfaceStyle == .dark ? 1 : 0)
            // Push the initial insets (task 08) — the first
            // `viewSafeAreaInsetsDidChange` may have already fired before
            // `handle` existed, so `pushInsets()`'s guard silently dropped
            // it; push once explicitly now that a handle is live.
            pushInsets()
            startDisplayLink()
            // Flush a deep link that arrived before this handle existed
            // (see `pendingDeepLink`'s doc comment) — a cold-start link
            // must not be silently dropped just because it raced ahead of
            // `frust_init`.
            if let pending = pendingDeepLink {
                pendingDeepLink = nil
                deliverDeepLink(pending)
            }
        } else if pixelSize != lastDrawableSize {
            frust_resize(handle, width, height, Float(scale))
        }
        lastDrawableSize = pixelSize
    }

    // MARK: - Deep links (task 07)

    /// Deliver a platform deep link — called by `SceneDelegate` for both the
    /// cold-start link (`connectionOptions.urlContexts`, in
    /// `scene(_:willConnectTo:options:)`) and a running-app link
    /// (`scene(_:openURLContexts:)`) uniformly. Queues until `frust_init`
    /// has returned a handle if the link arrives first (see
    /// `pendingDeepLink`).
    func handleDeepLink(_ url: URL) {
        deliverDeepLink(url.absoluteString)
    }

    private func deliverDeepLink(_ url: String) {
        guard let handle else {
            pendingDeepLink = url
            return
        }
        url.withCString { cstr in
            frust_on_deep_link(handle, cstr)
        }
    }

    // MARK: - Text input (spec §9, Phase 4B)

    /// Read the focused field's IME surface from Rust as a parsed dictionary,
    /// freeing the returned C string (the Rust side transfers ownership).
    private func fetchImeState() -> [String: Any]? {
        guard let handle, let raw = frust_ime_state_json(handle) else { return nil }
        defer { frust_string_free(raw) }
        let data = Data(bytes: raw, count: strlen(raw))
        return (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
    }

    /// Reconcile keyboard/first-responder state with the tree: a newly-focused
    /// field seeds the mirror and shows the keyboard; a blurred field resigns.
    private func syncImeFocus() {
        guard let state = fetchImeState() else { return }
        let active = (state["active"] as? Bool) ?? false
        if active {
            if !forgeView.isFirstResponder {
                forgeView.seedMirror(from: state)
                forgeView.becomeFirstResponder()
            }
        } else if forgeView.isFirstResponder {
            forgeView.resignFirstResponder()
        }
    }

    private func startDisplayLink() {
        guard displayLink == nil else { return }
        let link = CADisplayLink(target: self, selector: #selector(renderFrame(_:)))
        // Enable up to 120Hz on ProMotion hardware (iOS 15+): request the device's
        // maximum refresh rate with a minimum of 30fps to let the system down-clock
        // on idle/thermal throttle (the framework's own dirty-gate, task 16-18, is
        // what actually saves power on skipped frames).
        link.preferredFrameRateRange = CAFrameRateRange(
            minimum: 30,
            maximum: Float(UIScreen.main.maximumFramesPerSecond),
            preferred: Float(UIScreen.main.maximumFramesPerSecond)
        )
        link.add(to: .main, forMode: .common)
        displayLink = link
    }

    @objc private func renderFrame(_ link: CADisplayLink) {
        guard let handle else { return }
        // `link.timestamp` is a `CFTimeInterval` (seconds); the Rust side wants
        // the shell-owned monotonic frame clock in nanoseconds (spec §8). The
        // f64 * 1e9 multiply/round is tolerated here because Rust only ever
        // *differences* two FrameTimes (never reads one as an absolute
        // wall-clock value) — see frust-core::anim's FrameTime contract.
        // Don't "fix" this by reordering the multiply/cast without reading
        // that contract first.
        let alive = frust_render_frame(handle, UInt64(link.timestamp * 1_000_000_000))
        if alive == 0 {
            // A 0 return is a FATAL, unrecoverable render-thread failure (the
            // first surface install could not succeed) — latch it exactly like a
            // failed `frust_init` (so `updateSurface`'s `!initFailed` guard never
            // re-runs a doomed init) and stop the display link rather than drive
            // doomed frames against a permanent black screen.
            initFailed = true
            displayLink?.invalidate()
            displayLink = nil
            NSLog("Frust: render thread reported a fatal error — rendering disabled for this session")
        }
    }

    @objc private func appWillResignActive() {
        displayLink?.isPaused = true
        if let handle { frust_pause(handle) }
    }

    @objc private func appDidBecomeActive() {
        if let handle { frust_resume(handle) }
        displayLink?.isPaused = false
    }

    /// The platform's light/dark appearance preference changed (task 08) —
    /// re-seed the theme's brightness.
    override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
        super.traitCollectionDidChange(previousTraitCollection)
        guard let handle else { return }
        frust_set_appearance(handle, traitCollection.userInterfaceStyle == .dark ? 1 : 0)
    }

    deinit {
        displayLink?.invalidate()
        displayLink = nil
        NotificationCenter.default.removeObserver(self)
        if let handle {
            frust_destroy(handle)
        }
    }
}
